spring.application.name=dbuff

spring.datasource.url=jdbc:postgresql://localhost:5432/dbuff
spring.jpa.database=POSTGRESQL
spring.datasource.username=postgres
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

scrapper.url=http://api.scraperapi.com
scrapper.is-debug-enabled=true
scrapper.premium=false
scrapper.request-per-minute=60
scrapper.api-key=${SCRAPPER_API_KEY:}

dota-api.api-key=${DOTA_API_KEY:}
dota-api.request-per-minute=60
dota-api.is-debug-enabled=true
# Jackson configuration
spring.jackson.mapper.allow-coercion-of-scalars=true
spring.jackson.deserialization.fail-on-unknown-properties=false

# Debug logging for configuration
logging.level.com.ako.dbuff.config=DEBUG

# Cache debug logging
logging.level.org.springframework.cache=DEBUG
logging.level.com.ako.dbuff.service.constant=DEBUG




