/*
 * OpenDota API
 * # Introduction The OpenDota API provides Dota 2 related data including advanced match data extracted from match replays.  You can find data that can be used to convert hero and ability IDs and other information provided by the API from the [dotaconstants](https://github.com/odota/dotaconstants) repository.  You can use the API without a key, but registering for a key allows increased rate limits and usage. Check out the [API page](https://www.opendota.com/api-keys) to learn more.     
 *
 * The version of the OpenAPI document: 31.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ako.dbuff.dotapi.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.ako.dbuff.dotapi.model.DistributionsResponseRanks;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.ako.dbuff.dotapi.invoker.JSON;


/**
 * DistributionsResponse
 */
@JsonPropertyOrder({
  DistributionsResponse.JSON_PROPERTY_RANKS
})
@com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class DistributionsResponse {
  public static final String JSON_PROPERTY_RANKS = "ranks";
  @jakarta.annotation.Nullable
  private DistributionsResponseRanks ranks;

  public DistributionsResponse() { 
  }

  public DistributionsResponse ranks(@jakarta.annotation.Nullable DistributionsResponseRanks ranks) {
    this.ranks = ranks;
    return this;
  }

  /**
   * Get ranks
   * @return ranks
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RANKS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public DistributionsResponseRanks getRanks() {
    return ranks;
  }


  @JsonProperty(JSON_PROPERTY_RANKS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRanks(@jakarta.annotation.Nullable DistributionsResponseRanks ranks) {
    this.ranks = ranks;
  }


  /**
   * Return true if this DistributionsResponse object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DistributionsResponse distributionsResponse = (DistributionsResponse) o;
    return Objects.equals(this.ranks, distributionsResponse.ranks);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ranks);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DistributionsResponse {\n");
    sb.append("    ranks: ").append(toIndentedString(ranks)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

