/*
 * OpenDota API
 * # Introduction The OpenDota API provides Dota 2 related data including advanced match data extracted from match replays.  You can find data that can be used to convert hero and ability IDs and other information provided by the API from the [dotaconstants](https://github.com/odota/dotaconstants) repository.  Without a key, you can make 2,000 free calls per day at a rate limit of 60 requests/minute. We also offer a Premium Tier with unlimited API calls and higher rate limits. Check out the [API page](https://www.opendota.com/api-keys) to learn more.     
 *
 * The version of the OpenAPI document: 26.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ako.dbuff.dotapi.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.ako.dbuff.dotapi.invoker.JSON;


/**
 * HeroMatchupsResponse
 */
@JsonPropertyOrder({
  HeroMatchupsResponse.JSON_PROPERTY_HERO_ID,
  HeroMatchupsResponse.JSON_PROPERTY_GAMES_PLAYED,
  HeroMatchupsResponse.JSON_PROPERTY_WINS
})
@com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class HeroMatchupsResponse {
  public static final String JSON_PROPERTY_HERO_ID = "hero_id";
  @jakarta.annotation.Nullable
  private Long heroId;

  public static final String JSON_PROPERTY_GAMES_PLAYED = "games_played";
  @jakarta.annotation.Nullable
  private Long gamesPlayed;

  public static final String JSON_PROPERTY_WINS = "wins";
  @jakarta.annotation.Nullable
  private Long wins;

  public HeroMatchupsResponse() { 
  }

  public HeroMatchupsResponse heroId(@jakarta.annotation.Nullable Long heroId) {
    this.heroId = heroId;
    return this;
  }

  /**
   * The ID value of the hero played
   * @return heroId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_HERO_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getHeroId() {
    return heroId;
  }


  @JsonProperty(JSON_PROPERTY_HERO_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHeroId(@jakarta.annotation.Nullable Long heroId) {
    this.heroId = heroId;
  }


  public HeroMatchupsResponse gamesPlayed(@jakarta.annotation.Nullable Long gamesPlayed) {
    this.gamesPlayed = gamesPlayed;
    return this;
  }

  /**
   * Number of games played
   * @return gamesPlayed
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_GAMES_PLAYED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getGamesPlayed() {
    return gamesPlayed;
  }


  @JsonProperty(JSON_PROPERTY_GAMES_PLAYED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setGamesPlayed(@jakarta.annotation.Nullable Long gamesPlayed) {
    this.gamesPlayed = gamesPlayed;
  }


  public HeroMatchupsResponse wins(@jakarta.annotation.Nullable Long wins) {
    this.wins = wins;
    return this;
  }

  /**
   * Number of games won
   * @return wins
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_WINS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getWins() {
    return wins;
  }


  @JsonProperty(JSON_PROPERTY_WINS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setWins(@jakarta.annotation.Nullable Long wins) {
    this.wins = wins;
  }


  /**
   * Return true if this HeroMatchupsResponse object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HeroMatchupsResponse heroMatchupsResponse = (HeroMatchupsResponse) o;
    return Objects.equals(this.heroId, heroMatchupsResponse.heroId) &&
        Objects.equals(this.gamesPlayed, heroMatchupsResponse.gamesPlayed) &&
        Objects.equals(this.wins, heroMatchupsResponse.wins);
  }

  @Override
  public int hashCode() {
    return Objects.hash(heroId, gamesPlayed, wins);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class HeroMatchupsResponse {\n");
    sb.append("    heroId: ").append(toIndentedString(heroId)).append("\n");
    sb.append("    gamesPlayed: ").append(toIndentedString(gamesPlayed)).append("\n");
    sb.append("    wins: ").append(toIndentedString(wins)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

