/*
 * OpenDota API
 * # Introduction The OpenDota API provides Dota 2 related data including advanced match data extracted from match replays.  You can find data that can be used to convert hero and ability IDs and other information provided by the API from the [dotaconstants](https://github.com/odota/dotaconstants) repository.  You can use the API without a key, but registering for a key allows increased rate limits and usage. Check out the [API page](https://www.opendota.com/api-keys) to learn more.     
 *
 * The version of the OpenAPI document: 31.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ako.dbuff.dotapi.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.ako.dbuff.dotapi.model.HeroItemPopularityResponseEarlyGameItems;
import com.ako.dbuff.dotapi.model.HeroItemPopularityResponseLateGameItems;
import com.ako.dbuff.dotapi.model.HeroItemPopularityResponseMidGameItems;
import com.ako.dbuff.dotapi.model.HeroItemPopularityResponseStartGameItems;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.ako.dbuff.dotapi.invoker.JSON;


/**
 * HeroItemPopularityResponse
 */
@JsonPropertyOrder({
  HeroItemPopularityResponse.JSON_PROPERTY_START_GAME_ITEMS,
  HeroItemPopularityResponse.JSON_PROPERTY_EARLY_GAME_ITEMS,
  HeroItemPopularityResponse.JSON_PROPERTY_MID_GAME_ITEMS,
  HeroItemPopularityResponse.JSON_PROPERTY_LATE_GAME_ITEMS
})
@com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class HeroItemPopularityResponse {
  public static final String JSON_PROPERTY_START_GAME_ITEMS = "start_game_items";
  @jakarta.annotation.Nullable
  private HeroItemPopularityResponseStartGameItems startGameItems;

  public static final String JSON_PROPERTY_EARLY_GAME_ITEMS = "early_game_items";
  @jakarta.annotation.Nullable
  private HeroItemPopularityResponseEarlyGameItems earlyGameItems;

  public static final String JSON_PROPERTY_MID_GAME_ITEMS = "mid_game_items";
  @jakarta.annotation.Nullable
  private HeroItemPopularityResponseMidGameItems midGameItems;

  public static final String JSON_PROPERTY_LATE_GAME_ITEMS = "late_game_items";
  @jakarta.annotation.Nullable
  private HeroItemPopularityResponseLateGameItems lateGameItems;

  public HeroItemPopularityResponse() { 
  }

  public HeroItemPopularityResponse startGameItems(@jakarta.annotation.Nullable HeroItemPopularityResponseStartGameItems startGameItems) {
    this.startGameItems = startGameItems;
    return this;
  }

  /**
   * Get startGameItems
   * @return startGameItems
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_START_GAME_ITEMS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public HeroItemPopularityResponseStartGameItems getStartGameItems() {
    return startGameItems;
  }


  @JsonProperty(JSON_PROPERTY_START_GAME_ITEMS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStartGameItems(@jakarta.annotation.Nullable HeroItemPopularityResponseStartGameItems startGameItems) {
    this.startGameItems = startGameItems;
  }


  public HeroItemPopularityResponse earlyGameItems(@jakarta.annotation.Nullable HeroItemPopularityResponseEarlyGameItems earlyGameItems) {
    this.earlyGameItems = earlyGameItems;
    return this;
  }

  /**
   * Get earlyGameItems
   * @return earlyGameItems
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EARLY_GAME_ITEMS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public HeroItemPopularityResponseEarlyGameItems getEarlyGameItems() {
    return earlyGameItems;
  }


  @JsonProperty(JSON_PROPERTY_EARLY_GAME_ITEMS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEarlyGameItems(@jakarta.annotation.Nullable HeroItemPopularityResponseEarlyGameItems earlyGameItems) {
    this.earlyGameItems = earlyGameItems;
  }


  public HeroItemPopularityResponse midGameItems(@jakarta.annotation.Nullable HeroItemPopularityResponseMidGameItems midGameItems) {
    this.midGameItems = midGameItems;
    return this;
  }

  /**
   * Get midGameItems
   * @return midGameItems
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MID_GAME_ITEMS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public HeroItemPopularityResponseMidGameItems getMidGameItems() {
    return midGameItems;
  }


  @JsonProperty(JSON_PROPERTY_MID_GAME_ITEMS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMidGameItems(@jakarta.annotation.Nullable HeroItemPopularityResponseMidGameItems midGameItems) {
    this.midGameItems = midGameItems;
  }


  public HeroItemPopularityResponse lateGameItems(@jakarta.annotation.Nullable HeroItemPopularityResponseLateGameItems lateGameItems) {
    this.lateGameItems = lateGameItems;
    return this;
  }

  /**
   * Get lateGameItems
   * @return lateGameItems
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LATE_GAME_ITEMS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public HeroItemPopularityResponseLateGameItems getLateGameItems() {
    return lateGameItems;
  }


  @JsonProperty(JSON_PROPERTY_LATE_GAME_ITEMS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLateGameItems(@jakarta.annotation.Nullable HeroItemPopularityResponseLateGameItems lateGameItems) {
    this.lateGameItems = lateGameItems;
  }


  /**
   * Return true if this HeroItemPopularityResponse object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HeroItemPopularityResponse heroItemPopularityResponse = (HeroItemPopularityResponse) o;
    return Objects.equals(this.startGameItems, heroItemPopularityResponse.startGameItems) &&
        Objects.equals(this.earlyGameItems, heroItemPopularityResponse.earlyGameItems) &&
        Objects.equals(this.midGameItems, heroItemPopularityResponse.midGameItems) &&
        Objects.equals(this.lateGameItems, heroItemPopularityResponse.lateGameItems);
  }

  @Override
  public int hashCode() {
    return Objects.hash(startGameItems, earlyGameItems, midGameItems, lateGameItems);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class HeroItemPopularityResponse {\n");
    sb.append("    startGameItems: ").append(toIndentedString(startGameItems)).append("\n");
    sb.append("    earlyGameItems: ").append(toIndentedString(earlyGameItems)).append("\n");
    sb.append("    midGameItems: ").append(toIndentedString(midGameItems)).append("\n");
    sb.append("    lateGameItems: ").append(toIndentedString(lateGameItems)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

