/*
 * OpenDota API
 * # Introduction The OpenDota API provides Dota 2 related data including advanced match data extracted from match replays.  You can find data that can be used to convert hero and ability IDs and other information provided by the API from the [dotaconstants](https://github.com/odota/dotaconstants) repository.  You can use the API without a key, but registering for a key allows increased rate limits and usage. Check out the [API page](https://www.opendota.com/api-keys) to learn more.     
 *
 * The version of the OpenAPI document: 31.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ako.dbuff.dotapi.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.ako.dbuff.dotapi.invoker.JSON;


/**
 * MatchResponsePlayersInnerCosmeticsInner
 */
@JsonPropertyOrder({
  MatchResponsePlayersInnerCosmeticsInner.JSON_PROPERTY_ITEM_ID,
  MatchResponsePlayersInnerCosmeticsInner.JSON_PROPERTY_NAME,
  MatchResponsePlayersInnerCosmeticsInner.JSON_PROPERTY_PREFAB,
  MatchResponsePlayersInnerCosmeticsInner.JSON_PROPERTY_CREATION_DATE,
  MatchResponsePlayersInnerCosmeticsInner.JSON_PROPERTY_IMAGE_INVENTORY,
  MatchResponsePlayersInnerCosmeticsInner.JSON_PROPERTY_IMAGE_PATH,
  MatchResponsePlayersInnerCosmeticsInner.JSON_PROPERTY_ITEM_DESCRIPTION,
  MatchResponsePlayersInnerCosmeticsInner.JSON_PROPERTY_ITEM_NAME,
  MatchResponsePlayersInnerCosmeticsInner.JSON_PROPERTY_ITEM_RARITY,
  MatchResponsePlayersInnerCosmeticsInner.JSON_PROPERTY_ITEM_TYPE_NAME,
  MatchResponsePlayersInnerCosmeticsInner.JSON_PROPERTY_USED_BY_HEROES
})
@JsonTypeName("MatchResponse_players_inner_cosmetics_inner")
@com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class MatchResponsePlayersInnerCosmeticsInner {
  public static final String JSON_PROPERTY_ITEM_ID = "item_id";
  @jakarta.annotation.Nullable
  private Long itemId;

  public static final String JSON_PROPERTY_NAME = "name";
  private JsonNullable<String> name = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_PREFAB = "prefab";
  @jakarta.annotation.Nullable
  private String prefab;

  public static final String JSON_PROPERTY_CREATION_DATE = "creation_date";
  private JsonNullable<OffsetDateTime> creationDate = JsonNullable.<OffsetDateTime>undefined();

  public static final String JSON_PROPERTY_IMAGE_INVENTORY = "image_inventory";
  private JsonNullable<String> imageInventory = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_IMAGE_PATH = "image_path";
  private JsonNullable<String> imagePath = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_ITEM_DESCRIPTION = "item_description";
  private JsonNullable<String> itemDescription = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_ITEM_NAME = "item_name";
  @jakarta.annotation.Nullable
  private String itemName;

  public static final String JSON_PROPERTY_ITEM_RARITY = "item_rarity";
  private JsonNullable<String> itemRarity = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_ITEM_TYPE_NAME = "item_type_name";
  private JsonNullable<String> itemTypeName = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_USED_BY_HEROES = "used_by_heroes";
  private JsonNullable<String> usedByHeroes = JsonNullable.<String>undefined();

  public MatchResponsePlayersInnerCosmeticsInner() { 
  }

  public MatchResponsePlayersInnerCosmeticsInner itemId(@jakarta.annotation.Nullable Long itemId) {
    this.itemId = itemId;
    return this;
  }

  /**
   * Get itemId
   * @return itemId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ITEM_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getItemId() {
    return itemId;
  }


  @JsonProperty(JSON_PROPERTY_ITEM_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setItemId(@jakarta.annotation.Nullable Long itemId) {
    this.itemId = itemId;
  }


  public MatchResponsePlayersInnerCosmeticsInner name(@jakarta.annotation.Nullable String name) {
    this.name = JsonNullable.<String>of(name);
    return this;
  }

  /**
   * name
   * @return name
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getName() {
        return name.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getName_JsonNullable() {
    return name;
  }
  
  @JsonProperty(JSON_PROPERTY_NAME)
  public void setName_JsonNullable(JsonNullable<String> name) {
    this.name = name;
  }

  public void setName(@jakarta.annotation.Nullable String name) {
    this.name = JsonNullable.<String>of(name);
  }


  public MatchResponsePlayersInnerCosmeticsInner prefab(@jakarta.annotation.Nullable String prefab) {
    this.prefab = prefab;
    return this;
  }

  /**
   * Get prefab
   * @return prefab
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PREFAB)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPrefab() {
    return prefab;
  }


  @JsonProperty(JSON_PROPERTY_PREFAB)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPrefab(@jakarta.annotation.Nullable String prefab) {
    this.prefab = prefab;
  }


  public MatchResponsePlayersInnerCosmeticsInner creationDate(@jakarta.annotation.Nullable OffsetDateTime creationDate) {
    this.creationDate = JsonNullable.<OffsetDateTime>of(creationDate);
    return this;
  }

  /**
   * Get creationDate
   * @return creationDate
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public OffsetDateTime getCreationDate() {
        return creationDate.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_CREATION_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<OffsetDateTime> getCreationDate_JsonNullable() {
    return creationDate;
  }
  
  @JsonProperty(JSON_PROPERTY_CREATION_DATE)
  public void setCreationDate_JsonNullable(JsonNullable<OffsetDateTime> creationDate) {
    this.creationDate = creationDate;
  }

  public void setCreationDate(@jakarta.annotation.Nullable OffsetDateTime creationDate) {
    this.creationDate = JsonNullable.<OffsetDateTime>of(creationDate);
  }


  public MatchResponsePlayersInnerCosmeticsInner imageInventory(@jakarta.annotation.Nullable String imageInventory) {
    this.imageInventory = JsonNullable.<String>of(imageInventory);
    return this;
  }

  /**
   * Get imageInventory
   * @return imageInventory
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getImageInventory() {
        return imageInventory.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_IMAGE_INVENTORY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getImageInventory_JsonNullable() {
    return imageInventory;
  }
  
  @JsonProperty(JSON_PROPERTY_IMAGE_INVENTORY)
  public void setImageInventory_JsonNullable(JsonNullable<String> imageInventory) {
    this.imageInventory = imageInventory;
  }

  public void setImageInventory(@jakarta.annotation.Nullable String imageInventory) {
    this.imageInventory = JsonNullable.<String>of(imageInventory);
  }


  public MatchResponsePlayersInnerCosmeticsInner imagePath(@jakarta.annotation.Nullable String imagePath) {
    this.imagePath = JsonNullable.<String>of(imagePath);
    return this;
  }

  /**
   * Get imagePath
   * @return imagePath
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getImagePath() {
        return imagePath.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_IMAGE_PATH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getImagePath_JsonNullable() {
    return imagePath;
  }
  
  @JsonProperty(JSON_PROPERTY_IMAGE_PATH)
  public void setImagePath_JsonNullable(JsonNullable<String> imagePath) {
    this.imagePath = imagePath;
  }

  public void setImagePath(@jakarta.annotation.Nullable String imagePath) {
    this.imagePath = JsonNullable.<String>of(imagePath);
  }


  public MatchResponsePlayersInnerCosmeticsInner itemDescription(@jakarta.annotation.Nullable String itemDescription) {
    this.itemDescription = JsonNullable.<String>of(itemDescription);
    return this;
  }

  /**
   * Get itemDescription
   * @return itemDescription
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getItemDescription() {
        return itemDescription.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_ITEM_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getItemDescription_JsonNullable() {
    return itemDescription;
  }
  
  @JsonProperty(JSON_PROPERTY_ITEM_DESCRIPTION)
  public void setItemDescription_JsonNullable(JsonNullable<String> itemDescription) {
    this.itemDescription = itemDescription;
  }

  public void setItemDescription(@jakarta.annotation.Nullable String itemDescription) {
    this.itemDescription = JsonNullable.<String>of(itemDescription);
  }


  public MatchResponsePlayersInnerCosmeticsInner itemName(@jakarta.annotation.Nullable String itemName) {
    this.itemName = itemName;
    return this;
  }

  /**
   * Get itemName
   * @return itemName
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ITEM_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getItemName() {
    return itemName;
  }


  @JsonProperty(JSON_PROPERTY_ITEM_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setItemName(@jakarta.annotation.Nullable String itemName) {
    this.itemName = itemName;
  }


  public MatchResponsePlayersInnerCosmeticsInner itemRarity(@jakarta.annotation.Nullable String itemRarity) {
    this.itemRarity = JsonNullable.<String>of(itemRarity);
    return this;
  }

  /**
   * Get itemRarity
   * @return itemRarity
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getItemRarity() {
        return itemRarity.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_ITEM_RARITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getItemRarity_JsonNullable() {
    return itemRarity;
  }
  
  @JsonProperty(JSON_PROPERTY_ITEM_RARITY)
  public void setItemRarity_JsonNullable(JsonNullable<String> itemRarity) {
    this.itemRarity = itemRarity;
  }

  public void setItemRarity(@jakarta.annotation.Nullable String itemRarity) {
    this.itemRarity = JsonNullable.<String>of(itemRarity);
  }


  public MatchResponsePlayersInnerCosmeticsInner itemTypeName(@jakarta.annotation.Nullable String itemTypeName) {
    this.itemTypeName = JsonNullable.<String>of(itemTypeName);
    return this;
  }

  /**
   * Get itemTypeName
   * @return itemTypeName
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getItemTypeName() {
        return itemTypeName.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_ITEM_TYPE_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getItemTypeName_JsonNullable() {
    return itemTypeName;
  }
  
  @JsonProperty(JSON_PROPERTY_ITEM_TYPE_NAME)
  public void setItemTypeName_JsonNullable(JsonNullable<String> itemTypeName) {
    this.itemTypeName = itemTypeName;
  }

  public void setItemTypeName(@jakarta.annotation.Nullable String itemTypeName) {
    this.itemTypeName = JsonNullable.<String>of(itemTypeName);
  }


  public MatchResponsePlayersInnerCosmeticsInner usedByHeroes(@jakarta.annotation.Nullable String usedByHeroes) {
    this.usedByHeroes = JsonNullable.<String>of(usedByHeroes);
    return this;
  }

  /**
   * Get usedByHeroes
   * @return usedByHeroes
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getUsedByHeroes() {
        return usedByHeroes.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_USED_BY_HEROES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getUsedByHeroes_JsonNullable() {
    return usedByHeroes;
  }
  
  @JsonProperty(JSON_PROPERTY_USED_BY_HEROES)
  public void setUsedByHeroes_JsonNullable(JsonNullable<String> usedByHeroes) {
    this.usedByHeroes = usedByHeroes;
  }

  public void setUsedByHeroes(@jakarta.annotation.Nullable String usedByHeroes) {
    this.usedByHeroes = JsonNullable.<String>of(usedByHeroes);
  }


  /**
   * Return true if this MatchResponse_players_inner_cosmetics_inner object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MatchResponsePlayersInnerCosmeticsInner matchResponsePlayersInnerCosmeticsInner = (MatchResponsePlayersInnerCosmeticsInner) o;
    return Objects.equals(this.itemId, matchResponsePlayersInnerCosmeticsInner.itemId) &&
        equalsNullable(this.name, matchResponsePlayersInnerCosmeticsInner.name) &&
        Objects.equals(this.prefab, matchResponsePlayersInnerCosmeticsInner.prefab) &&
        equalsNullable(this.creationDate, matchResponsePlayersInnerCosmeticsInner.creationDate) &&
        equalsNullable(this.imageInventory, matchResponsePlayersInnerCosmeticsInner.imageInventory) &&
        equalsNullable(this.imagePath, matchResponsePlayersInnerCosmeticsInner.imagePath) &&
        equalsNullable(this.itemDescription, matchResponsePlayersInnerCosmeticsInner.itemDescription) &&
        Objects.equals(this.itemName, matchResponsePlayersInnerCosmeticsInner.itemName) &&
        equalsNullable(this.itemRarity, matchResponsePlayersInnerCosmeticsInner.itemRarity) &&
        equalsNullable(this.itemTypeName, matchResponsePlayersInnerCosmeticsInner.itemTypeName) &&
        equalsNullable(this.usedByHeroes, matchResponsePlayersInnerCosmeticsInner.usedByHeroes);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(itemId, hashCodeNullable(name), prefab, hashCodeNullable(creationDate), hashCodeNullable(imageInventory), hashCodeNullable(imagePath), hashCodeNullable(itemDescription), itemName, hashCodeNullable(itemRarity), hashCodeNullable(itemTypeName), hashCodeNullable(usedByHeroes));
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MatchResponsePlayersInnerCosmeticsInner {\n");
    sb.append("    itemId: ").append(toIndentedString(itemId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    prefab: ").append(toIndentedString(prefab)).append("\n");
    sb.append("    creationDate: ").append(toIndentedString(creationDate)).append("\n");
    sb.append("    imageInventory: ").append(toIndentedString(imageInventory)).append("\n");
    sb.append("    imagePath: ").append(toIndentedString(imagePath)).append("\n");
    sb.append("    itemDescription: ").append(toIndentedString(itemDescription)).append("\n");
    sb.append("    itemName: ").append(toIndentedString(itemName)).append("\n");
    sb.append("    itemRarity: ").append(toIndentedString(itemRarity)).append("\n");
    sb.append("    itemTypeName: ").append(toIndentedString(itemTypeName)).append("\n");
    sb.append("    usedByHeroes: ").append(toIndentedString(usedByHeroes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

