/*
 * OpenDota API
 * # Introduction The OpenDota API provides Dota 2 related data including advanced match data extracted from match replays.  You can find data that can be used to convert hero and ability IDs and other information provided by the API from the [dotaconstants](https://github.com/odota/dotaconstants) repository.  You can use the API without a key, but registering for a key allows increased rate limits and usage. Check out the [API page](https://www.opendota.com/api-keys) to learn more.     
 *
 * The version of the OpenAPI document: 31.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ako.dbuff.dotapi.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.ako.dbuff.dotapi.invoker.JSON;


/**
 * MatchResponseChatInner
 */
@JsonPropertyOrder({
  MatchResponseChatInner.JSON_PROPERTY_TIME,
  MatchResponseChatInner.JSON_PROPERTY_UNIT,
  MatchResponseChatInner.JSON_PROPERTY_KEY,
  MatchResponseChatInner.JSON_PROPERTY_SLOT,
  MatchResponseChatInner.JSON_PROPERTY_PLAYER_SLOT
})
@JsonTypeName("MatchResponse_chat_inner")
@com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class MatchResponseChatInner {
  public static final String JSON_PROPERTY_TIME = "time";
  @jakarta.annotation.Nullable
  private Long time;

  public static final String JSON_PROPERTY_UNIT = "unit";
  @jakarta.annotation.Nullable
  private String unit;

  public static final String JSON_PROPERTY_KEY = "key";
  @jakarta.annotation.Nullable
  private String key;

  public static final String JSON_PROPERTY_SLOT = "slot";
  @jakarta.annotation.Nullable
  private Long slot;

  public static final String JSON_PROPERTY_PLAYER_SLOT = "player_slot";
  private JsonNullable<Long> playerSlot = JsonNullable.<Long>undefined();

  public MatchResponseChatInner() { 
  }

  public MatchResponseChatInner time(@jakarta.annotation.Nullable Long time) {
    this.time = time;
    return this;
  }

  /**
   * Time in seconds at which the message was said
   * @return time
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getTime() {
    return time;
  }


  @JsonProperty(JSON_PROPERTY_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTime(@jakarta.annotation.Nullable Long time) {
    this.time = time;
  }


  public MatchResponseChatInner unit(@jakarta.annotation.Nullable String unit) {
    this.unit = unit;
    return this;
  }

  /**
   * Name of the player who sent the message
   * @return unit
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_UNIT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUnit() {
    return unit;
  }


  @JsonProperty(JSON_PROPERTY_UNIT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUnit(@jakarta.annotation.Nullable String unit) {
    this.unit = unit;
  }


  public MatchResponseChatInner key(@jakarta.annotation.Nullable String key) {
    this.key = key;
    return this;
  }

  /**
   * The message the player sent
   * @return key
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_KEY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getKey() {
    return key;
  }


  @JsonProperty(JSON_PROPERTY_KEY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setKey(@jakarta.annotation.Nullable String key) {
    this.key = key;
  }


  public MatchResponseChatInner slot(@jakarta.annotation.Nullable Long slot) {
    this.slot = slot;
    return this;
  }

  /**
   * slot
   * @return slot
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SLOT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getSlot() {
    return slot;
  }


  @JsonProperty(JSON_PROPERTY_SLOT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSlot(@jakarta.annotation.Nullable Long slot) {
    this.slot = slot;
  }


  public MatchResponseChatInner playerSlot(@jakarta.annotation.Nullable Long playerSlot) {
    this.playerSlot = JsonNullable.<Long>of(playerSlot);
    return this;
  }

  /**
   * Which slot the player is in. 0-127 are Radiant, 128-255 are Dire
   * @return playerSlot
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Long getPlayerSlot() {
        return playerSlot.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_PLAYER_SLOT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Long> getPlayerSlot_JsonNullable() {
    return playerSlot;
  }
  
  @JsonProperty(JSON_PROPERTY_PLAYER_SLOT)
  public void setPlayerSlot_JsonNullable(JsonNullable<Long> playerSlot) {
    this.playerSlot = playerSlot;
  }

  public void setPlayerSlot(@jakarta.annotation.Nullable Long playerSlot) {
    this.playerSlot = JsonNullable.<Long>of(playerSlot);
  }


  /**
   * Return true if this MatchResponse_chat_inner object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MatchResponseChatInner matchResponseChatInner = (MatchResponseChatInner) o;
    return Objects.equals(this.time, matchResponseChatInner.time) &&
        Objects.equals(this.unit, matchResponseChatInner.unit) &&
        Objects.equals(this.key, matchResponseChatInner.key) &&
        Objects.equals(this.slot, matchResponseChatInner.slot) &&
        equalsNullable(this.playerSlot, matchResponseChatInner.playerSlot);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(time, unit, key, slot, hashCodeNullable(playerSlot));
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MatchResponseChatInner {\n");
    sb.append("    time: ").append(toIndentedString(time)).append("\n");
    sb.append("    unit: ").append(toIndentedString(unit)).append("\n");
    sb.append("    key: ").append(toIndentedString(key)).append("\n");
    sb.append("    slot: ").append(toIndentedString(slot)).append("\n");
    sb.append("    playerSlot: ").append(toIndentedString(playerSlot)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

