/*
 * OpenDota API
 * # Introduction The OpenDota API provides Dota 2 related data including advanced match data extracted from match replays.  You can find data that can be used to convert hero and ability IDs and other information provided by the API from the [dotaconstants](https://github.com/odota/dotaconstants) repository.  Without a key, you can make 2,000 free calls per day at a rate limit of 60 requests/minute. We also offer a Premium Tier with unlimited API calls and higher rate limits. Check out the [API page](https://www.opendota.com/api-keys) to learn more.     
 *
 * The version of the OpenAPI document: 26.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ako.dbuff.dotapi.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.ako.dbuff.dotapi.model.MatchResponseChatInner;
import com.ako.dbuff.dotapi.model.MatchResponseDraftTimingsInner;
import com.ako.dbuff.dotapi.model.MatchResponsePicksBansInner;
import com.ako.dbuff.dotapi.model.MatchResponsePlayersInner;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.ako.dbuff.dotapi.invoker.JSON;


/**
 * MatchResponse
 */
@JsonPropertyOrder({
  MatchResponse.JSON_PROPERTY_MATCH_ID,
  MatchResponse.JSON_PROPERTY_BARRACKS_STATUS_DIRE,
  MatchResponse.JSON_PROPERTY_BARRACKS_STATUS_RADIANT,
  MatchResponse.JSON_PROPERTY_CHAT,
  MatchResponse.JSON_PROPERTY_CLUSTER,
  MatchResponse.JSON_PROPERTY_COSMETICS,
  MatchResponse.JSON_PROPERTY_DIRE_SCORE,
  MatchResponse.JSON_PROPERTY_DRAFT_TIMINGS,
  MatchResponse.JSON_PROPERTY_DURATION,
  MatchResponse.JSON_PROPERTY_ENGINE,
  MatchResponse.JSON_PROPERTY_FIRST_BLOOD_TIME,
  MatchResponse.JSON_PROPERTY_GAME_MODE,
  MatchResponse.JSON_PROPERTY_HUMAN_PLAYERS,
  MatchResponse.JSON_PROPERTY_LEAGUEID,
  MatchResponse.JSON_PROPERTY_LOBBY_TYPE,
  MatchResponse.JSON_PROPERTY_MATCH_SEQ_NUM,
  MatchResponse.JSON_PROPERTY_NEGATIVE_VOTES,
  MatchResponse.JSON_PROPERTY_OBJECTIVES,
  MatchResponse.JSON_PROPERTY_PICKS_BANS,
  MatchResponse.JSON_PROPERTY_POSITIVE_VOTES,
  MatchResponse.JSON_PROPERTY_RADIANT_GOLD_ADV,
  MatchResponse.JSON_PROPERTY_RADIANT_SCORE,
  MatchResponse.JSON_PROPERTY_RADIANT_WIN,
  MatchResponse.JSON_PROPERTY_RADIANT_XP_ADV,
  MatchResponse.JSON_PROPERTY_START_TIME,
  MatchResponse.JSON_PROPERTY_TEAMFIGHTS,
  MatchResponse.JSON_PROPERTY_TOWER_STATUS_DIRE,
  MatchResponse.JSON_PROPERTY_TOWER_STATUS_RADIANT,
  MatchResponse.JSON_PROPERTY_VERSION,
  MatchResponse.JSON_PROPERTY_REPLAY_SALT,
  MatchResponse.JSON_PROPERTY_SERIES_ID,
  MatchResponse.JSON_PROPERTY_SERIES_TYPE,
  MatchResponse.JSON_PROPERTY_RADIANT_TEAM,
  MatchResponse.JSON_PROPERTY_DIRE_TEAM,
  MatchResponse.JSON_PROPERTY_LEAGUE,
  MatchResponse.JSON_PROPERTY_SKILL,
  MatchResponse.JSON_PROPERTY_PLAYERS,
  MatchResponse.JSON_PROPERTY_PATCH,
  MatchResponse.JSON_PROPERTY_REGION,
  MatchResponse.JSON_PROPERTY_ALL_WORD_COUNTS,
  MatchResponse.JSON_PROPERTY_MY_WORD_COUNTS,
  MatchResponse.JSON_PROPERTY_THROW,
  MatchResponse.JSON_PROPERTY_COMEBACK,
  MatchResponse.JSON_PROPERTY_LOSS,
  MatchResponse.JSON_PROPERTY_WIN,
  MatchResponse.JSON_PROPERTY_REPLAY_URL
})
@com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class MatchResponse {
  public static final String JSON_PROPERTY_MATCH_ID = "match_id";
  @jakarta.annotation.Nullable
  private Long matchId;

  public static final String JSON_PROPERTY_BARRACKS_STATUS_DIRE = "barracks_status_dire";
  @jakarta.annotation.Nullable
  private Long barracksStatusDire;

  public static final String JSON_PROPERTY_BARRACKS_STATUS_RADIANT = "barracks_status_radiant";
  @jakarta.annotation.Nullable
  private Long barracksStatusRadiant;

  public static final String JSON_PROPERTY_CHAT = "chat";
  @jakarta.annotation.Nullable
  private List<MatchResponseChatInner> chat = new ArrayList<>();

  public static final String JSON_PROPERTY_CLUSTER = "cluster";
  @jakarta.annotation.Nullable
  private Long cluster;

  public static final String JSON_PROPERTY_COSMETICS = "cosmetics";
  @jakarta.annotation.Nullable
  private Map<String, Long> cosmetics = new HashMap<>();

  public static final String JSON_PROPERTY_DIRE_SCORE = "dire_score";
  @jakarta.annotation.Nullable
  private Long direScore;

  public static final String JSON_PROPERTY_DRAFT_TIMINGS = "draft_timings";
  @jakarta.annotation.Nullable
  private List<MatchResponseDraftTimingsInner> draftTimings = new ArrayList<>();

  public static final String JSON_PROPERTY_DURATION = "duration";
  @jakarta.annotation.Nullable
  private Long duration;

  public static final String JSON_PROPERTY_ENGINE = "engine";
  @jakarta.annotation.Nullable
  private Long engine;

  public static final String JSON_PROPERTY_FIRST_BLOOD_TIME = "first_blood_time";
  @jakarta.annotation.Nullable
  private Long firstBloodTime;

  public static final String JSON_PROPERTY_GAME_MODE = "game_mode";
  @jakarta.annotation.Nullable
  private Long gameMode;

  public static final String JSON_PROPERTY_HUMAN_PLAYERS = "human_players";
  @jakarta.annotation.Nullable
  private Long humanPlayers;

  public static final String JSON_PROPERTY_LEAGUEID = "leagueid";
  @jakarta.annotation.Nullable
  private Long leagueid;

  public static final String JSON_PROPERTY_LOBBY_TYPE = "lobby_type";
  @jakarta.annotation.Nullable
  private Long lobbyType;

  public static final String JSON_PROPERTY_MATCH_SEQ_NUM = "match_seq_num";
  @jakarta.annotation.Nullable
  private Long matchSeqNum;

  public static final String JSON_PROPERTY_NEGATIVE_VOTES = "negative_votes";
  @jakarta.annotation.Nullable
  private Long negativeVotes;

  public static final String JSON_PROPERTY_OBJECTIVES = "objectives";
  @jakarta.annotation.Nullable
  private List<Object> objectives = new ArrayList<>();

  public static final String JSON_PROPERTY_PICKS_BANS = "picks_bans";
  @jakarta.annotation.Nullable
  private List<MatchResponsePicksBansInner> picksBans = new ArrayList<>();

  public static final String JSON_PROPERTY_POSITIVE_VOTES = "positive_votes";
  @jakarta.annotation.Nullable
  private Long positiveVotes;

  public static final String JSON_PROPERTY_RADIANT_GOLD_ADV = "radiant_gold_adv";
  @jakarta.annotation.Nullable
  private List<BigDecimal> radiantGoldAdv = new ArrayList<>();

  public static final String JSON_PROPERTY_RADIANT_SCORE = "radiant_score";
  @jakarta.annotation.Nullable
  private Long radiantScore;

  public static final String JSON_PROPERTY_RADIANT_WIN = "radiant_win";
  private JsonNullable<Boolean> radiantWin = JsonNullable.<Boolean>undefined();

  public static final String JSON_PROPERTY_RADIANT_XP_ADV = "radiant_xp_adv";
  @jakarta.annotation.Nullable
  private List<BigDecimal> radiantXpAdv = new ArrayList<>();

  public static final String JSON_PROPERTY_START_TIME = "start_time";
  @jakarta.annotation.Nullable
  private Long startTime;

  public static final String JSON_PROPERTY_TEAMFIGHTS = "teamfights";
  private JsonNullable<List<Object>> teamfights = JsonNullable.<List<Object>>undefined();

  public static final String JSON_PROPERTY_TOWER_STATUS_DIRE = "tower_status_dire";
  @jakarta.annotation.Nullable
  private Long towerStatusDire;

  public static final String JSON_PROPERTY_TOWER_STATUS_RADIANT = "tower_status_radiant";
  @jakarta.annotation.Nullable
  private Long towerStatusRadiant;

  public static final String JSON_PROPERTY_VERSION = "version";
  @jakarta.annotation.Nullable
  private Long version;

  public static final String JSON_PROPERTY_REPLAY_SALT = "replay_salt";
  @jakarta.annotation.Nullable
  private Long replaySalt;

  public static final String JSON_PROPERTY_SERIES_ID = "series_id";
  @jakarta.annotation.Nullable
  private Long seriesId;

  public static final String JSON_PROPERTY_SERIES_TYPE = "series_type";
  @jakarta.annotation.Nullable
  private Long seriesType;

  public static final String JSON_PROPERTY_RADIANT_TEAM = "radiant_team";
  @jakarta.annotation.Nullable
  private Object radiantTeam;

  public static final String JSON_PROPERTY_DIRE_TEAM = "dire_team";
  @jakarta.annotation.Nullable
  private Object direTeam;

  public static final String JSON_PROPERTY_LEAGUE = "league";
  @jakarta.annotation.Nullable
  private Object league;

  public static final String JSON_PROPERTY_SKILL = "skill";
  private JsonNullable<Long> skill = JsonNullable.<Long>undefined();

  public static final String JSON_PROPERTY_PLAYERS = "players";
  @jakarta.annotation.Nullable
  private List<MatchResponsePlayersInner> players = new ArrayList<>();

  public static final String JSON_PROPERTY_PATCH = "patch";
  @jakarta.annotation.Nullable
  private Long patch;

  public static final String JSON_PROPERTY_REGION = "region";
  @jakarta.annotation.Nullable
  private Long region;

  public static final String JSON_PROPERTY_ALL_WORD_COUNTS = "all_word_counts";
  @jakarta.annotation.Nullable
  private Object allWordCounts;

  public static final String JSON_PROPERTY_MY_WORD_COUNTS = "my_word_counts";
  @jakarta.annotation.Nullable
  private Object myWordCounts;

  public static final String JSON_PROPERTY_THROW = "throw";
  @jakarta.annotation.Nullable
  private Long _throw;

  public static final String JSON_PROPERTY_COMEBACK = "comeback";
  @jakarta.annotation.Nullable
  private Long comeback;

  public static final String JSON_PROPERTY_LOSS = "loss";
  @jakarta.annotation.Nullable
  private Long loss;

  public static final String JSON_PROPERTY_WIN = "win";
  @jakarta.annotation.Nullable
  private Long win;

  public static final String JSON_PROPERTY_REPLAY_URL = "replay_url";
  @jakarta.annotation.Nullable
  private String replayUrl;

  public MatchResponse() { 
  }

  public MatchResponse matchId(@jakarta.annotation.Nullable Long matchId) {
    this.matchId = matchId;
    return this;
  }

  /**
   * The ID number of the match assigned by Valve
   * @return matchId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MATCH_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getMatchId() {
    return matchId;
  }


  @JsonProperty(JSON_PROPERTY_MATCH_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMatchId(@jakarta.annotation.Nullable Long matchId) {
    this.matchId = matchId;
  }


  public MatchResponse barracksStatusDire(@jakarta.annotation.Nullable Long barracksStatusDire) {
    this.barracksStatusDire = barracksStatusDire;
    return this;
  }

  /**
   * Bitmask. An integer that represents a binary of which barracks are still standing. 63 would mean all barracks still stand at the end of the game.
   * @return barracksStatusDire
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_BARRACKS_STATUS_DIRE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getBarracksStatusDire() {
    return barracksStatusDire;
  }


  @JsonProperty(JSON_PROPERTY_BARRACKS_STATUS_DIRE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBarracksStatusDire(@jakarta.annotation.Nullable Long barracksStatusDire) {
    this.barracksStatusDire = barracksStatusDire;
  }


  public MatchResponse barracksStatusRadiant(@jakarta.annotation.Nullable Long barracksStatusRadiant) {
    this.barracksStatusRadiant = barracksStatusRadiant;
    return this;
  }

  /**
   * Bitmask. An integer that represents a binary of which barracks are still standing. 63 would mean all barracks still stand at the end of the game.
   * @return barracksStatusRadiant
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_BARRACKS_STATUS_RADIANT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getBarracksStatusRadiant() {
    return barracksStatusRadiant;
  }


  @JsonProperty(JSON_PROPERTY_BARRACKS_STATUS_RADIANT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBarracksStatusRadiant(@jakarta.annotation.Nullable Long barracksStatusRadiant) {
    this.barracksStatusRadiant = barracksStatusRadiant;
  }


  public MatchResponse chat(@jakarta.annotation.Nullable List<MatchResponseChatInner> chat) {
    this.chat = chat;
    return this;
  }

  public MatchResponse addChatItem(MatchResponseChatInner chatItem) {
    if (this.chat == null) {
      this.chat = new ArrayList<>();
    }
    this.chat.add(chatItem);
    return this;
  }

  /**
   * Array containing information on the chat of the game
   * @return chat
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CHAT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<MatchResponseChatInner> getChat() {
    return chat;
  }


  @JsonProperty(JSON_PROPERTY_CHAT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setChat(@jakarta.annotation.Nullable List<MatchResponseChatInner> chat) {
    this.chat = chat;
  }


  public MatchResponse cluster(@jakarta.annotation.Nullable Long cluster) {
    this.cluster = cluster;
    return this;
  }

  /**
   * cluster
   * @return cluster
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CLUSTER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getCluster() {
    return cluster;
  }


  @JsonProperty(JSON_PROPERTY_CLUSTER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCluster(@jakarta.annotation.Nullable Long cluster) {
    this.cluster = cluster;
  }


  public MatchResponse cosmetics(@jakarta.annotation.Nullable Map<String, Long> cosmetics) {
    this.cosmetics = cosmetics;
    return this;
  }

  public MatchResponse putCosmeticsItem(String key, Long cosmeticsItem) {
    if (this.cosmetics == null) {
      this.cosmetics = new HashMap<>();
    }
    this.cosmetics.put(key, cosmeticsItem);
    return this;
  }

  /**
   * cosmetics
   * @return cosmetics
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_COSMETICS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Map<String, Long> getCosmetics() {
    return cosmetics;
  }


  @JsonProperty(JSON_PROPERTY_COSMETICS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCosmetics(@jakarta.annotation.Nullable Map<String, Long> cosmetics) {
    this.cosmetics = cosmetics;
  }


  public MatchResponse direScore(@jakarta.annotation.Nullable Long direScore) {
    this.direScore = direScore;
    return this;
  }

  /**
   * Number of kills the Dire team had when the match ended
   * @return direScore
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DIRE_SCORE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getDireScore() {
    return direScore;
  }


  @JsonProperty(JSON_PROPERTY_DIRE_SCORE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDireScore(@jakarta.annotation.Nullable Long direScore) {
    this.direScore = direScore;
  }


  public MatchResponse draftTimings(@jakarta.annotation.Nullable List<MatchResponseDraftTimingsInner> draftTimings) {
    this.draftTimings = draftTimings;
    return this;
  }

  public MatchResponse addDraftTimingsItem(MatchResponseDraftTimingsInner draftTimingsItem) {
    if (this.draftTimings == null) {
      this.draftTimings = new ArrayList<>();
    }
    this.draftTimings.add(draftTimingsItem);
    return this;
  }

  /**
   * draft_timings
   * @return draftTimings
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DRAFT_TIMINGS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<MatchResponseDraftTimingsInner> getDraftTimings() {
    return draftTimings;
  }


  @JsonProperty(JSON_PROPERTY_DRAFT_TIMINGS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDraftTimings(@jakarta.annotation.Nullable List<MatchResponseDraftTimingsInner> draftTimings) {
    this.draftTimings = draftTimings;
  }


  public MatchResponse duration(@jakarta.annotation.Nullable Long duration) {
    this.duration = duration;
    return this;
  }

  /**
   * Duration of the game in seconds
   * @return duration
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DURATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getDuration() {
    return duration;
  }


  @JsonProperty(JSON_PROPERTY_DURATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDuration(@jakarta.annotation.Nullable Long duration) {
    this.duration = duration;
  }


  public MatchResponse engine(@jakarta.annotation.Nullable Long engine) {
    this.engine = engine;
    return this;
  }

  /**
   * engine
   * @return engine
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ENGINE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getEngine() {
    return engine;
  }


  @JsonProperty(JSON_PROPERTY_ENGINE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEngine(@jakarta.annotation.Nullable Long engine) {
    this.engine = engine;
  }


  public MatchResponse firstBloodTime(@jakarta.annotation.Nullable Long firstBloodTime) {
    this.firstBloodTime = firstBloodTime;
    return this;
  }

  /**
   * Time in seconds at which first blood occurred
   * @return firstBloodTime
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FIRST_BLOOD_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getFirstBloodTime() {
    return firstBloodTime;
  }


  @JsonProperty(JSON_PROPERTY_FIRST_BLOOD_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFirstBloodTime(@jakarta.annotation.Nullable Long firstBloodTime) {
    this.firstBloodTime = firstBloodTime;
  }


  public MatchResponse gameMode(@jakarta.annotation.Nullable Long gameMode) {
    this.gameMode = gameMode;
    return this;
  }

  /**
   * Integer corresponding to game mode played. List of constants can be found here: https://github.com/odota/dotaconstants/blob/master/json/game_mode.json
   * @return gameMode
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_GAME_MODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getGameMode() {
    return gameMode;
  }


  @JsonProperty(JSON_PROPERTY_GAME_MODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setGameMode(@jakarta.annotation.Nullable Long gameMode) {
    this.gameMode = gameMode;
  }


  public MatchResponse humanPlayers(@jakarta.annotation.Nullable Long humanPlayers) {
    this.humanPlayers = humanPlayers;
    return this;
  }

  /**
   * Number of human players in the game
   * @return humanPlayers
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_HUMAN_PLAYERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getHumanPlayers() {
    return humanPlayers;
  }


  @JsonProperty(JSON_PROPERTY_HUMAN_PLAYERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHumanPlayers(@jakarta.annotation.Nullable Long humanPlayers) {
    this.humanPlayers = humanPlayers;
  }


  public MatchResponse leagueid(@jakarta.annotation.Nullable Long leagueid) {
    this.leagueid = leagueid;
    return this;
  }

  /**
   * leagueid
   * @return leagueid
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LEAGUEID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getLeagueid() {
    return leagueid;
  }


  @JsonProperty(JSON_PROPERTY_LEAGUEID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLeagueid(@jakarta.annotation.Nullable Long leagueid) {
    this.leagueid = leagueid;
  }


  public MatchResponse lobbyType(@jakarta.annotation.Nullable Long lobbyType) {
    this.lobbyType = lobbyType;
    return this;
  }

  /**
   * Integer corresponding to lobby type of match. List of constants can be found here: https://github.com/odota/dotaconstants/blob/master/json/lobby_type.json
   * @return lobbyType
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LOBBY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getLobbyType() {
    return lobbyType;
  }


  @JsonProperty(JSON_PROPERTY_LOBBY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLobbyType(@jakarta.annotation.Nullable Long lobbyType) {
    this.lobbyType = lobbyType;
  }


  public MatchResponse matchSeqNum(@jakarta.annotation.Nullable Long matchSeqNum) {
    this.matchSeqNum = matchSeqNum;
    return this;
  }

  /**
   * match_seq_num
   * @return matchSeqNum
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MATCH_SEQ_NUM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getMatchSeqNum() {
    return matchSeqNum;
  }


  @JsonProperty(JSON_PROPERTY_MATCH_SEQ_NUM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMatchSeqNum(@jakarta.annotation.Nullable Long matchSeqNum) {
    this.matchSeqNum = matchSeqNum;
  }


  public MatchResponse negativeVotes(@jakarta.annotation.Nullable Long negativeVotes) {
    this.negativeVotes = negativeVotes;
    return this;
  }

  /**
   * Number of negative votes the replay received in the in-game client
   * @return negativeVotes
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NEGATIVE_VOTES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getNegativeVotes() {
    return negativeVotes;
  }


  @JsonProperty(JSON_PROPERTY_NEGATIVE_VOTES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNegativeVotes(@jakarta.annotation.Nullable Long negativeVotes) {
    this.negativeVotes = negativeVotes;
  }


  public MatchResponse objectives(@jakarta.annotation.Nullable List<Object> objectives) {
    this.objectives = objectives;
    return this;
  }

  public MatchResponse addObjectivesItem(Object objectivesItem) {
    if (this.objectives == null) {
      this.objectives = new ArrayList<>();
    }
    this.objectives.add(objectivesItem);
    return this;
  }

  /**
   * objectives
   * @return objectives
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_OBJECTIVES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Object> getObjectives() {
    return objectives;
  }


  @JsonProperty(JSON_PROPERTY_OBJECTIVES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setObjectives(@jakarta.annotation.Nullable List<Object> objectives) {
    this.objectives = objectives;
  }


  public MatchResponse picksBans(@jakarta.annotation.Nullable List<MatchResponsePicksBansInner> picksBans) {
    this.picksBans = picksBans;
    return this;
  }

  public MatchResponse addPicksBansItem(MatchResponsePicksBansInner picksBansItem) {
    if (this.picksBans == null) {
      this.picksBans = new ArrayList<>();
    }
    this.picksBans.add(picksBansItem);
    return this;
  }

  /**
   * Array containing information on the draft. Each item contains a boolean relating to whether the choice is a pick or a ban, the hero ID, the team the picked or banned it, and the order.
   * @return picksBans
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PICKS_BANS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<MatchResponsePicksBansInner> getPicksBans() {
    return picksBans;
  }


  @JsonProperty(JSON_PROPERTY_PICKS_BANS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPicksBans(@jakarta.annotation.Nullable List<MatchResponsePicksBansInner> picksBans) {
    this.picksBans = picksBans;
  }


  public MatchResponse positiveVotes(@jakarta.annotation.Nullable Long positiveVotes) {
    this.positiveVotes = positiveVotes;
    return this;
  }

  /**
   * Number of positive votes the replay received in the in-game client
   * @return positiveVotes
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_POSITIVE_VOTES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getPositiveVotes() {
    return positiveVotes;
  }


  @JsonProperty(JSON_PROPERTY_POSITIVE_VOTES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPositiveVotes(@jakarta.annotation.Nullable Long positiveVotes) {
    this.positiveVotes = positiveVotes;
  }


  public MatchResponse radiantGoldAdv(@jakarta.annotation.Nullable List<BigDecimal> radiantGoldAdv) {
    this.radiantGoldAdv = radiantGoldAdv;
    return this;
  }

  public MatchResponse addRadiantGoldAdvItem(BigDecimal radiantGoldAdvItem) {
    if (this.radiantGoldAdv == null) {
      this.radiantGoldAdv = new ArrayList<>();
    }
    this.radiantGoldAdv.add(radiantGoldAdvItem);
    return this;
  }

  /**
   * Array of the Radiant gold advantage at each minute in the game. A negative number means that Radiant is behind, and thus it is their gold disadvantage. 
   * @return radiantGoldAdv
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RADIANT_GOLD_ADV)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<BigDecimal> getRadiantGoldAdv() {
    return radiantGoldAdv;
  }


  @JsonProperty(JSON_PROPERTY_RADIANT_GOLD_ADV)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRadiantGoldAdv(@jakarta.annotation.Nullable List<BigDecimal> radiantGoldAdv) {
    this.radiantGoldAdv = radiantGoldAdv;
  }


  public MatchResponse radiantScore(@jakarta.annotation.Nullable Long radiantScore) {
    this.radiantScore = radiantScore;
    return this;
  }

  /**
   * Number of kills the Radiant team had when the match ended
   * @return radiantScore
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RADIANT_SCORE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getRadiantScore() {
    return radiantScore;
  }


  @JsonProperty(JSON_PROPERTY_RADIANT_SCORE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRadiantScore(@jakarta.annotation.Nullable Long radiantScore) {
    this.radiantScore = radiantScore;
  }


  public MatchResponse radiantWin(@jakarta.annotation.Nullable Boolean radiantWin) {
    this.radiantWin = JsonNullable.<Boolean>of(radiantWin);
    return this;
  }

  /**
   * Boolean indicating whether Radiant won the match
   * @return radiantWin
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Boolean getRadiantWin() {
        return radiantWin.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_RADIANT_WIN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Boolean> getRadiantWin_JsonNullable() {
    return radiantWin;
  }
  
  @JsonProperty(JSON_PROPERTY_RADIANT_WIN)
  public void setRadiantWin_JsonNullable(JsonNullable<Boolean> radiantWin) {
    this.radiantWin = radiantWin;
  }

  public void setRadiantWin(@jakarta.annotation.Nullable Boolean radiantWin) {
    this.radiantWin = JsonNullable.<Boolean>of(radiantWin);
  }


  public MatchResponse radiantXpAdv(@jakarta.annotation.Nullable List<BigDecimal> radiantXpAdv) {
    this.radiantXpAdv = radiantXpAdv;
    return this;
  }

  public MatchResponse addRadiantXpAdvItem(BigDecimal radiantXpAdvItem) {
    if (this.radiantXpAdv == null) {
      this.radiantXpAdv = new ArrayList<>();
    }
    this.radiantXpAdv.add(radiantXpAdvItem);
    return this;
  }

  /**
   * Array of the Radiant experience advantage at each minute in the game. A negative number means that Radiant is behind, and thus it is their experience disadvantage. 
   * @return radiantXpAdv
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RADIANT_XP_ADV)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<BigDecimal> getRadiantXpAdv() {
    return radiantXpAdv;
  }


  @JsonProperty(JSON_PROPERTY_RADIANT_XP_ADV)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRadiantXpAdv(@jakarta.annotation.Nullable List<BigDecimal> radiantXpAdv) {
    this.radiantXpAdv = radiantXpAdv;
  }


  public MatchResponse startTime(@jakarta.annotation.Nullable Long startTime) {
    this.startTime = startTime;
    return this;
  }

  /**
   * The Unix timestamp at which the game started
   * @return startTime
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_START_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getStartTime() {
    return startTime;
  }


  @JsonProperty(JSON_PROPERTY_START_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStartTime(@jakarta.annotation.Nullable Long startTime) {
    this.startTime = startTime;
  }


  public MatchResponse teamfights(@jakarta.annotation.Nullable List<Object> teamfights) {
    this.teamfights = JsonNullable.<List<Object>>of(teamfights);
    return this;
  }

  public MatchResponse addTeamfightsItem(Object teamfightsItem) {
    if (this.teamfights == null || !this.teamfights.isPresent()) {
      this.teamfights = JsonNullable.<List<Object>>of(new ArrayList<>());
    }
    try {
      this.teamfights.get().add(teamfightsItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * teamfights
   * @return teamfights
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public List<Object> getTeamfights() {
        return teamfights.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_TEAMFIGHTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<List<Object>> getTeamfights_JsonNullable() {
    return teamfights;
  }
  
  @JsonProperty(JSON_PROPERTY_TEAMFIGHTS)
  public void setTeamfights_JsonNullable(JsonNullable<List<Object>> teamfights) {
    this.teamfights = teamfights;
  }

  public void setTeamfights(@jakarta.annotation.Nullable List<Object> teamfights) {
    this.teamfights = JsonNullable.<List<Object>>of(teamfights);
  }


  public MatchResponse towerStatusDire(@jakarta.annotation.Nullable Long towerStatusDire) {
    this.towerStatusDire = towerStatusDire;
    return this;
  }

  /**
   * Bitmask. An integer that represents a binary of which Dire towers are still standing.
   * @return towerStatusDire
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TOWER_STATUS_DIRE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getTowerStatusDire() {
    return towerStatusDire;
  }


  @JsonProperty(JSON_PROPERTY_TOWER_STATUS_DIRE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTowerStatusDire(@jakarta.annotation.Nullable Long towerStatusDire) {
    this.towerStatusDire = towerStatusDire;
  }


  public MatchResponse towerStatusRadiant(@jakarta.annotation.Nullable Long towerStatusRadiant) {
    this.towerStatusRadiant = towerStatusRadiant;
    return this;
  }

  /**
   * Bitmask. An integer that represents a binary of which Radiant towers are still standing.
   * @return towerStatusRadiant
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TOWER_STATUS_RADIANT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getTowerStatusRadiant() {
    return towerStatusRadiant;
  }


  @JsonProperty(JSON_PROPERTY_TOWER_STATUS_RADIANT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTowerStatusRadiant(@jakarta.annotation.Nullable Long towerStatusRadiant) {
    this.towerStatusRadiant = towerStatusRadiant;
  }


  public MatchResponse version(@jakarta.annotation.Nullable Long version) {
    this.version = version;
    return this;
  }

  /**
   * Parse version, used internally by OpenDota
   * @return version
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VERSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getVersion() {
    return version;
  }


  @JsonProperty(JSON_PROPERTY_VERSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVersion(@jakarta.annotation.Nullable Long version) {
    this.version = version;
  }


  public MatchResponse replaySalt(@jakarta.annotation.Nullable Long replaySalt) {
    this.replaySalt = replaySalt;
    return this;
  }

  /**
   * replay_salt
   * @return replaySalt
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REPLAY_SALT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getReplaySalt() {
    return replaySalt;
  }


  @JsonProperty(JSON_PROPERTY_REPLAY_SALT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setReplaySalt(@jakarta.annotation.Nullable Long replaySalt) {
    this.replaySalt = replaySalt;
  }


  public MatchResponse seriesId(@jakarta.annotation.Nullable Long seriesId) {
    this.seriesId = seriesId;
    return this;
  }

  /**
   * series_id
   * @return seriesId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SERIES_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getSeriesId() {
    return seriesId;
  }


  @JsonProperty(JSON_PROPERTY_SERIES_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSeriesId(@jakarta.annotation.Nullable Long seriesId) {
    this.seriesId = seriesId;
  }


  public MatchResponse seriesType(@jakarta.annotation.Nullable Long seriesType) {
    this.seriesType = seriesType;
    return this;
  }

  /**
   * series_type
   * @return seriesType
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SERIES_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getSeriesType() {
    return seriesType;
  }


  @JsonProperty(JSON_PROPERTY_SERIES_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSeriesType(@jakarta.annotation.Nullable Long seriesType) {
    this.seriesType = seriesType;
  }


  public MatchResponse radiantTeam(@jakarta.annotation.Nullable Object radiantTeam) {
    this.radiantTeam = radiantTeam;
    return this;
  }

  /**
   * radiant_team
   * @return radiantTeam
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RADIANT_TEAM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Object getRadiantTeam() {
    return radiantTeam;
  }


  @JsonProperty(JSON_PROPERTY_RADIANT_TEAM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRadiantTeam(@jakarta.annotation.Nullable Object radiantTeam) {
    this.radiantTeam = radiantTeam;
  }


  public MatchResponse direTeam(@jakarta.annotation.Nullable Object direTeam) {
    this.direTeam = direTeam;
    return this;
  }

  /**
   * dire_team
   * @return direTeam
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DIRE_TEAM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Object getDireTeam() {
    return direTeam;
  }


  @JsonProperty(JSON_PROPERTY_DIRE_TEAM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDireTeam(@jakarta.annotation.Nullable Object direTeam) {
    this.direTeam = direTeam;
  }


  public MatchResponse league(@jakarta.annotation.Nullable Object league) {
    this.league = league;
    return this;
  }

  /**
   * league
   * @return league
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LEAGUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Object getLeague() {
    return league;
  }


  @JsonProperty(JSON_PROPERTY_LEAGUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLeague(@jakarta.annotation.Nullable Object league) {
    this.league = league;
  }


  public MatchResponse skill(@jakarta.annotation.Nullable Long skill) {
    this.skill = JsonNullable.<Long>of(skill);
    return this;
  }

  /**
   * Skill bracket assigned by Valve (Normal, High, Very High)
   * @return skill
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Long getSkill() {
        return skill.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_SKILL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Long> getSkill_JsonNullable() {
    return skill;
  }
  
  @JsonProperty(JSON_PROPERTY_SKILL)
  public void setSkill_JsonNullable(JsonNullable<Long> skill) {
    this.skill = skill;
  }

  public void setSkill(@jakarta.annotation.Nullable Long skill) {
    this.skill = JsonNullable.<Long>of(skill);
  }


  public MatchResponse players(@jakarta.annotation.Nullable List<MatchResponsePlayersInner> players) {
    this.players = players;
    return this;
  }

  public MatchResponse addPlayersItem(MatchResponsePlayersInner playersItem) {
    if (this.players == null) {
      this.players = new ArrayList<>();
    }
    this.players.add(playersItem);
    return this;
  }

  /**
   * Array of information on individual players
   * @return players
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PLAYERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<MatchResponsePlayersInner> getPlayers() {
    return players;
  }


  @JsonProperty(JSON_PROPERTY_PLAYERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPlayers(@jakarta.annotation.Nullable List<MatchResponsePlayersInner> players) {
    this.players = players;
  }


  public MatchResponse patch(@jakarta.annotation.Nullable Long patch) {
    this.patch = patch;
    return this;
  }

  /**
   * Patch ID, from dotaconstants
   * @return patch
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PATCH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getPatch() {
    return patch;
  }


  @JsonProperty(JSON_PROPERTY_PATCH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPatch(@jakarta.annotation.Nullable Long patch) {
    this.patch = patch;
  }


  public MatchResponse region(@jakarta.annotation.Nullable Long region) {
    this.region = region;
    return this;
  }

  /**
   * Integer corresponding to the region the game was played on
   * @return region
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REGION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getRegion() {
    return region;
  }


  @JsonProperty(JSON_PROPERTY_REGION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRegion(@jakarta.annotation.Nullable Long region) {
    this.region = region;
  }


  public MatchResponse allWordCounts(@jakarta.annotation.Nullable Object allWordCounts) {
    this.allWordCounts = allWordCounts;
    return this;
  }

  /**
   * Word counts of the all chat messages in the player&#39;s games
   * @return allWordCounts
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ALL_WORD_COUNTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Object getAllWordCounts() {
    return allWordCounts;
  }


  @JsonProperty(JSON_PROPERTY_ALL_WORD_COUNTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAllWordCounts(@jakarta.annotation.Nullable Object allWordCounts) {
    this.allWordCounts = allWordCounts;
  }


  public MatchResponse myWordCounts(@jakarta.annotation.Nullable Object myWordCounts) {
    this.myWordCounts = myWordCounts;
    return this;
  }

  /**
   * Word counts of the player&#39;s all chat messages
   * @return myWordCounts
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MY_WORD_COUNTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Object getMyWordCounts() {
    return myWordCounts;
  }


  @JsonProperty(JSON_PROPERTY_MY_WORD_COUNTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMyWordCounts(@jakarta.annotation.Nullable Object myWordCounts) {
    this.myWordCounts = myWordCounts;
  }


  public MatchResponse _throw(@jakarta.annotation.Nullable Long _throw) {
    this._throw = _throw;
    return this;
  }

  /**
   * Maximum gold advantage of the player&#39;s team if they lost the match
   * @return _throw
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_THROW)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getThrow() {
    return _throw;
  }


  @JsonProperty(JSON_PROPERTY_THROW)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setThrow(@jakarta.annotation.Nullable Long _throw) {
    this._throw = _throw;
  }


  public MatchResponse comeback(@jakarta.annotation.Nullable Long comeback) {
    this.comeback = comeback;
    return this;
  }

  /**
   * Maximum gold disadvantage of the player&#39;s team if they won the match
   * @return comeback
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_COMEBACK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getComeback() {
    return comeback;
  }


  @JsonProperty(JSON_PROPERTY_COMEBACK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setComeback(@jakarta.annotation.Nullable Long comeback) {
    this.comeback = comeback;
  }


  public MatchResponse loss(@jakarta.annotation.Nullable Long loss) {
    this.loss = loss;
    return this;
  }

  /**
   * Maximum gold disadvantage of the player&#39;s team if they lost the match
   * @return loss
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LOSS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getLoss() {
    return loss;
  }


  @JsonProperty(JSON_PROPERTY_LOSS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLoss(@jakarta.annotation.Nullable Long loss) {
    this.loss = loss;
  }


  public MatchResponse win(@jakarta.annotation.Nullable Long win) {
    this.win = win;
    return this;
  }

  /**
   * Maximum gold advantage of the player&#39;s team if they won the match
   * @return win
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_WIN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getWin() {
    return win;
  }


  @JsonProperty(JSON_PROPERTY_WIN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setWin(@jakarta.annotation.Nullable Long win) {
    this.win = win;
  }


  public MatchResponse replayUrl(@jakarta.annotation.Nullable String replayUrl) {
    this.replayUrl = replayUrl;
    return this;
  }

  /**
   * replay_url
   * @return replayUrl
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REPLAY_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getReplayUrl() {
    return replayUrl;
  }


  @JsonProperty(JSON_PROPERTY_REPLAY_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setReplayUrl(@jakarta.annotation.Nullable String replayUrl) {
    this.replayUrl = replayUrl;
  }


  /**
   * Return true if this MatchResponse object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MatchResponse matchResponse = (MatchResponse) o;
    return Objects.equals(this.matchId, matchResponse.matchId) &&
        Objects.equals(this.barracksStatusDire, matchResponse.barracksStatusDire) &&
        Objects.equals(this.barracksStatusRadiant, matchResponse.barracksStatusRadiant) &&
        Objects.equals(this.chat, matchResponse.chat) &&
        Objects.equals(this.cluster, matchResponse.cluster) &&
        Objects.equals(this.cosmetics, matchResponse.cosmetics) &&
        Objects.equals(this.direScore, matchResponse.direScore) &&
        Objects.equals(this.draftTimings, matchResponse.draftTimings) &&
        Objects.equals(this.duration, matchResponse.duration) &&
        Objects.equals(this.engine, matchResponse.engine) &&
        Objects.equals(this.firstBloodTime, matchResponse.firstBloodTime) &&
        Objects.equals(this.gameMode, matchResponse.gameMode) &&
        Objects.equals(this.humanPlayers, matchResponse.humanPlayers) &&
        Objects.equals(this.leagueid, matchResponse.leagueid) &&
        Objects.equals(this.lobbyType, matchResponse.lobbyType) &&
        Objects.equals(this.matchSeqNum, matchResponse.matchSeqNum) &&
        Objects.equals(this.negativeVotes, matchResponse.negativeVotes) &&
        Objects.equals(this.objectives, matchResponse.objectives) &&
        Objects.equals(this.picksBans, matchResponse.picksBans) &&
        Objects.equals(this.positiveVotes, matchResponse.positiveVotes) &&
        Objects.equals(this.radiantGoldAdv, matchResponse.radiantGoldAdv) &&
        Objects.equals(this.radiantScore, matchResponse.radiantScore) &&
        equalsNullable(this.radiantWin, matchResponse.radiantWin) &&
        Objects.equals(this.radiantXpAdv, matchResponse.radiantXpAdv) &&
        Objects.equals(this.startTime, matchResponse.startTime) &&
        equalsNullable(this.teamfights, matchResponse.teamfights) &&
        Objects.equals(this.towerStatusDire, matchResponse.towerStatusDire) &&
        Objects.equals(this.towerStatusRadiant, matchResponse.towerStatusRadiant) &&
        Objects.equals(this.version, matchResponse.version) &&
        Objects.equals(this.replaySalt, matchResponse.replaySalt) &&
        Objects.equals(this.seriesId, matchResponse.seriesId) &&
        Objects.equals(this.seriesType, matchResponse.seriesType) &&
        Objects.equals(this.radiantTeam, matchResponse.radiantTeam) &&
        Objects.equals(this.direTeam, matchResponse.direTeam) &&
        Objects.equals(this.league, matchResponse.league) &&
        equalsNullable(this.skill, matchResponse.skill) &&
        Objects.equals(this.players, matchResponse.players) &&
        Objects.equals(this.patch, matchResponse.patch) &&
        Objects.equals(this.region, matchResponse.region) &&
        Objects.equals(this.allWordCounts, matchResponse.allWordCounts) &&
        Objects.equals(this.myWordCounts, matchResponse.myWordCounts) &&
        Objects.equals(this._throw, matchResponse._throw) &&
        Objects.equals(this.comeback, matchResponse.comeback) &&
        Objects.equals(this.loss, matchResponse.loss) &&
        Objects.equals(this.win, matchResponse.win) &&
        Objects.equals(this.replayUrl, matchResponse.replayUrl);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(matchId, barracksStatusDire, barracksStatusRadiant, chat, cluster, cosmetics, direScore, draftTimings, duration, engine, firstBloodTime, gameMode, humanPlayers, leagueid, lobbyType, matchSeqNum, negativeVotes, objectives, picksBans, positiveVotes, radiantGoldAdv, radiantScore, hashCodeNullable(radiantWin), radiantXpAdv, startTime, hashCodeNullable(teamfights), towerStatusDire, towerStatusRadiant, version, replaySalt, seriesId, seriesType, radiantTeam, direTeam, league, hashCodeNullable(skill), players, patch, region, allWordCounts, myWordCounts, _throw, comeback, loss, win, replayUrl);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MatchResponse {\n");
    sb.append("    matchId: ").append(toIndentedString(matchId)).append("\n");
    sb.append("    barracksStatusDire: ").append(toIndentedString(barracksStatusDire)).append("\n");
    sb.append("    barracksStatusRadiant: ").append(toIndentedString(barracksStatusRadiant)).append("\n");
    sb.append("    chat: ").append(toIndentedString(chat)).append("\n");
    sb.append("    cluster: ").append(toIndentedString(cluster)).append("\n");
    sb.append("    cosmetics: ").append(toIndentedString(cosmetics)).append("\n");
    sb.append("    direScore: ").append(toIndentedString(direScore)).append("\n");
    sb.append("    draftTimings: ").append(toIndentedString(draftTimings)).append("\n");
    sb.append("    duration: ").append(toIndentedString(duration)).append("\n");
    sb.append("    engine: ").append(toIndentedString(engine)).append("\n");
    sb.append("    firstBloodTime: ").append(toIndentedString(firstBloodTime)).append("\n");
    sb.append("    gameMode: ").append(toIndentedString(gameMode)).append("\n");
    sb.append("    humanPlayers: ").append(toIndentedString(humanPlayers)).append("\n");
    sb.append("    leagueid: ").append(toIndentedString(leagueid)).append("\n");
    sb.append("    lobbyType: ").append(toIndentedString(lobbyType)).append("\n");
    sb.append("    matchSeqNum: ").append(toIndentedString(matchSeqNum)).append("\n");
    sb.append("    negativeVotes: ").append(toIndentedString(negativeVotes)).append("\n");
    sb.append("    objectives: ").append(toIndentedString(objectives)).append("\n");
    sb.append("    picksBans: ").append(toIndentedString(picksBans)).append("\n");
    sb.append("    positiveVotes: ").append(toIndentedString(positiveVotes)).append("\n");
    sb.append("    radiantGoldAdv: ").append(toIndentedString(radiantGoldAdv)).append("\n");
    sb.append("    radiantScore: ").append(toIndentedString(radiantScore)).append("\n");
    sb.append("    radiantWin: ").append(toIndentedString(radiantWin)).append("\n");
    sb.append("    radiantXpAdv: ").append(toIndentedString(radiantXpAdv)).append("\n");
    sb.append("    startTime: ").append(toIndentedString(startTime)).append("\n");
    sb.append("    teamfights: ").append(toIndentedString(teamfights)).append("\n");
    sb.append("    towerStatusDire: ").append(toIndentedString(towerStatusDire)).append("\n");
    sb.append("    towerStatusRadiant: ").append(toIndentedString(towerStatusRadiant)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    replaySalt: ").append(toIndentedString(replaySalt)).append("\n");
    sb.append("    seriesId: ").append(toIndentedString(seriesId)).append("\n");
    sb.append("    seriesType: ").append(toIndentedString(seriesType)).append("\n");
    sb.append("    radiantTeam: ").append(toIndentedString(radiantTeam)).append("\n");
    sb.append("    direTeam: ").append(toIndentedString(direTeam)).append("\n");
    sb.append("    league: ").append(toIndentedString(league)).append("\n");
    sb.append("    skill: ").append(toIndentedString(skill)).append("\n");
    sb.append("    players: ").append(toIndentedString(players)).append("\n");
    sb.append("    patch: ").append(toIndentedString(patch)).append("\n");
    sb.append("    region: ").append(toIndentedString(region)).append("\n");
    sb.append("    allWordCounts: ").append(toIndentedString(allWordCounts)).append("\n");
    sb.append("    myWordCounts: ").append(toIndentedString(myWordCounts)).append("\n");
    sb.append("    _throw: ").append(toIndentedString(_throw)).append("\n");
    sb.append("    comeback: ").append(toIndentedString(comeback)).append("\n");
    sb.append("    loss: ").append(toIndentedString(loss)).append("\n");
    sb.append("    win: ").append(toIndentedString(win)).append("\n");
    sb.append("    replayUrl: ").append(toIndentedString(replayUrl)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

