/*
 * OpenDota API
 * # Introduction The OpenDota API provides Dota 2 related data including advanced match data extracted from match replays.  You can find data that can be used to convert hero and ability IDs and other information provided by the API from the [dotaconstants](https://github.com/odota/dotaconstants) repository.  You can use the API without a key, but registering for a key allows increased rate limits and usage. Check out the [API page](https://www.opendota.com/api-keys) to learn more.     
 *
 * The version of the OpenAPI document: 31.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ako.dbuff.dotapi.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.ako.dbuff.dotapi.invoker.JSON;


/**
 * OpenDota data availability status
 */
@JsonPropertyOrder({
  MatchResponseOdData.JSON_PROPERTY_HAS_API,
  MatchResponseOdData.JSON_PROPERTY_HAS_GCDATA,
  MatchResponseOdData.JSON_PROPERTY_HAS_PARSED,
  MatchResponseOdData.JSON_PROPERTY_HAS_ARCHIVE
})
@JsonTypeName("MatchResponse_od_data")
@com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class MatchResponseOdData {
  public static final String JSON_PROPERTY_HAS_API = "has_api";
  @jakarta.annotation.Nullable
  private Boolean hasApi;

  public static final String JSON_PROPERTY_HAS_GCDATA = "has_gcdata";
  @jakarta.annotation.Nullable
  private Boolean hasGcdata;

  public static final String JSON_PROPERTY_HAS_PARSED = "has_parsed";
  @jakarta.annotation.Nullable
  private Boolean hasParsed;

  public static final String JSON_PROPERTY_HAS_ARCHIVE = "has_archive";
  @jakarta.annotation.Nullable
  private Boolean hasArchive;

  public MatchResponseOdData() { 
  }

  public MatchResponseOdData hasApi(@jakarta.annotation.Nullable Boolean hasApi) {
    this.hasApi = hasApi;
    return this;
  }

  /**
   * Whether API data is available
   * @return hasApi
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_HAS_API)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getHasApi() {
    return hasApi;
  }


  @JsonProperty(JSON_PROPERTY_HAS_API)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHasApi(@jakarta.annotation.Nullable Boolean hasApi) {
    this.hasApi = hasApi;
  }


  public MatchResponseOdData hasGcdata(@jakarta.annotation.Nullable Boolean hasGcdata) {
    this.hasGcdata = hasGcdata;
    return this;
  }

  /**
   * Whether GC data is available
   * @return hasGcdata
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_HAS_GCDATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getHasGcdata() {
    return hasGcdata;
  }


  @JsonProperty(JSON_PROPERTY_HAS_GCDATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHasGcdata(@jakarta.annotation.Nullable Boolean hasGcdata) {
    this.hasGcdata = hasGcdata;
  }


  public MatchResponseOdData hasParsed(@jakarta.annotation.Nullable Boolean hasParsed) {
    this.hasParsed = hasParsed;
    return this;
  }

  /**
   * Whether the match replay has been parsed
   * @return hasParsed
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_HAS_PARSED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getHasParsed() {
    return hasParsed;
  }


  @JsonProperty(JSON_PROPERTY_HAS_PARSED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHasParsed(@jakarta.annotation.Nullable Boolean hasParsed) {
    this.hasParsed = hasParsed;
  }


  public MatchResponseOdData hasArchive(@jakarta.annotation.Nullable Boolean hasArchive) {
    this.hasArchive = hasArchive;
    return this;
  }

  /**
   * Whether the match has been archived
   * @return hasArchive
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_HAS_ARCHIVE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getHasArchive() {
    return hasArchive;
  }


  @JsonProperty(JSON_PROPERTY_HAS_ARCHIVE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHasArchive(@jakarta.annotation.Nullable Boolean hasArchive) {
    this.hasArchive = hasArchive;
  }


  /**
   * Return true if this MatchResponse_od_data object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MatchResponseOdData matchResponseOdData = (MatchResponseOdData) o;
    return Objects.equals(this.hasApi, matchResponseOdData.hasApi) &&
        Objects.equals(this.hasGcdata, matchResponseOdData.hasGcdata) &&
        Objects.equals(this.hasParsed, matchResponseOdData.hasParsed) &&
        Objects.equals(this.hasArchive, matchResponseOdData.hasArchive);
  }

  @Override
  public int hashCode() {
    return Objects.hash(hasApi, hasGcdata, hasParsed, hasArchive);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MatchResponseOdData {\n");
    sb.append("    hasApi: ").append(toIndentedString(hasApi)).append("\n");
    sb.append("    hasGcdata: ").append(toIndentedString(hasGcdata)).append("\n");
    sb.append("    hasParsed: ").append(toIndentedString(hasParsed)).append("\n");
    sb.append("    hasArchive: ").append(toIndentedString(hasArchive)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

