/*
 * OpenDota API
 * # Introduction The OpenDota API provides Dota 2 related data including advanced match data extracted from match replays.  You can find data that can be used to convert hero and ability IDs and other information provided by the API from the [dotaconstants](https://github.com/odota/dotaconstants) repository.  You can use the API without a key, but registering for a key allows increased rate limits and usage. Check out the [API page](https://www.opendota.com/api-keys) to learn more.     
 *
 * The version of the OpenAPI document: 31.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ako.dbuff.dotapi.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.ako.dbuff.dotapi.invoker.JSON;


/**
 * MatchObjectResponse
 */
@JsonPropertyOrder({
  MatchObjectResponse.JSON_PROPERTY_MATCH_ID,
  MatchObjectResponse.JSON_PROPERTY_DURATION,
  MatchObjectResponse.JSON_PROPERTY_START_TIME,
  MatchObjectResponse.JSON_PROPERTY_RADIANT_TEAM_ID,
  MatchObjectResponse.JSON_PROPERTY_RADIANT_NAME,
  MatchObjectResponse.JSON_PROPERTY_DIRE_TEAM_ID,
  MatchObjectResponse.JSON_PROPERTY_DIRE_NAME,
  MatchObjectResponse.JSON_PROPERTY_LEAGUEID,
  MatchObjectResponse.JSON_PROPERTY_LEAGUE_NAME,
  MatchObjectResponse.JSON_PROPERTY_SERIES_ID,
  MatchObjectResponse.JSON_PROPERTY_SERIES_TYPE,
  MatchObjectResponse.JSON_PROPERTY_RADIANT_SCORE,
  MatchObjectResponse.JSON_PROPERTY_DIRE_SCORE,
  MatchObjectResponse.JSON_PROPERTY_RADIANT_WIN,
  MatchObjectResponse.JSON_PROPERTY_RADIANT
})
@com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class MatchObjectResponse {
  public static final String JSON_PROPERTY_MATCH_ID = "match_id";
  @jakarta.annotation.Nullable
  private Long matchId;

  public static final String JSON_PROPERTY_DURATION = "duration";
  @jakarta.annotation.Nullable
  private Long duration;

  public static final String JSON_PROPERTY_START_TIME = "start_time";
  @jakarta.annotation.Nullable
  private Long startTime;

  public static final String JSON_PROPERTY_RADIANT_TEAM_ID = "radiant_team_id";
  @jakarta.annotation.Nullable
  private Long radiantTeamId;

  public static final String JSON_PROPERTY_RADIANT_NAME = "radiant_name";
  @jakarta.annotation.Nullable
  private String radiantName;

  public static final String JSON_PROPERTY_DIRE_TEAM_ID = "dire_team_id";
  @jakarta.annotation.Nullable
  private Long direTeamId;

  public static final String JSON_PROPERTY_DIRE_NAME = "dire_name";
  @jakarta.annotation.Nullable
  private String direName;

  public static final String JSON_PROPERTY_LEAGUEID = "leagueid";
  @jakarta.annotation.Nullable
  private Long leagueid;

  public static final String JSON_PROPERTY_LEAGUE_NAME = "league_name";
  @jakarta.annotation.Nullable
  private String leagueName;

  public static final String JSON_PROPERTY_SERIES_ID = "series_id";
  @jakarta.annotation.Nullable
  private Long seriesId;

  public static final String JSON_PROPERTY_SERIES_TYPE = "series_type";
  @jakarta.annotation.Nullable
  private Long seriesType;

  public static final String JSON_PROPERTY_RADIANT_SCORE = "radiant_score";
  @jakarta.annotation.Nullable
  private Long radiantScore;

  public static final String JSON_PROPERTY_DIRE_SCORE = "dire_score";
  @jakarta.annotation.Nullable
  private Long direScore;

  public static final String JSON_PROPERTY_RADIANT_WIN = "radiant_win";
  private JsonNullable<Boolean> radiantWin = JsonNullable.<Boolean>undefined();

  public static final String JSON_PROPERTY_RADIANT = "radiant";
  @jakarta.annotation.Nullable
  private Boolean radiant;

  public MatchObjectResponse() { 
  }

  public MatchObjectResponse matchId(@jakarta.annotation.Nullable Long matchId) {
    this.matchId = matchId;
    return this;
  }

  /**
   * The ID number of the match assigned by Valve
   * @return matchId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MATCH_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getMatchId() {
    return matchId;
  }


  @JsonProperty(JSON_PROPERTY_MATCH_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMatchId(@jakarta.annotation.Nullable Long matchId) {
    this.matchId = matchId;
  }


  public MatchObjectResponse duration(@jakarta.annotation.Nullable Long duration) {
    this.duration = duration;
    return this;
  }

  /**
   * Duration of the game in seconds
   * @return duration
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DURATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getDuration() {
    return duration;
  }


  @JsonProperty(JSON_PROPERTY_DURATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDuration(@jakarta.annotation.Nullable Long duration) {
    this.duration = duration;
  }


  public MatchObjectResponse startTime(@jakarta.annotation.Nullable Long startTime) {
    this.startTime = startTime;
    return this;
  }

  /**
   * The Unix timestamp at which the game started
   * @return startTime
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_START_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getStartTime() {
    return startTime;
  }


  @JsonProperty(JSON_PROPERTY_START_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStartTime(@jakarta.annotation.Nullable Long startTime) {
    this.startTime = startTime;
  }


  public MatchObjectResponse radiantTeamId(@jakarta.annotation.Nullable Long radiantTeamId) {
    this.radiantTeamId = radiantTeamId;
    return this;
  }

  /**
   * The Radiant&#39;s team_id
   * @return radiantTeamId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RADIANT_TEAM_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getRadiantTeamId() {
    return radiantTeamId;
  }


  @JsonProperty(JSON_PROPERTY_RADIANT_TEAM_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRadiantTeamId(@jakarta.annotation.Nullable Long radiantTeamId) {
    this.radiantTeamId = radiantTeamId;
  }


  public MatchObjectResponse radiantName(@jakarta.annotation.Nullable String radiantName) {
    this.radiantName = radiantName;
    return this;
  }

  /**
   * The Radiant&#39;s team name
   * @return radiantName
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RADIANT_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getRadiantName() {
    return radiantName;
  }


  @JsonProperty(JSON_PROPERTY_RADIANT_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRadiantName(@jakarta.annotation.Nullable String radiantName) {
    this.radiantName = radiantName;
  }


  public MatchObjectResponse direTeamId(@jakarta.annotation.Nullable Long direTeamId) {
    this.direTeamId = direTeamId;
    return this;
  }

  /**
   * The Dire&#39;s team_id
   * @return direTeamId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DIRE_TEAM_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getDireTeamId() {
    return direTeamId;
  }


  @JsonProperty(JSON_PROPERTY_DIRE_TEAM_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDireTeamId(@jakarta.annotation.Nullable Long direTeamId) {
    this.direTeamId = direTeamId;
  }


  public MatchObjectResponse direName(@jakarta.annotation.Nullable String direName) {
    this.direName = direName;
    return this;
  }

  /**
   * The Dire&#39;s team name
   * @return direName
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DIRE_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDireName() {
    return direName;
  }


  @JsonProperty(JSON_PROPERTY_DIRE_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDireName(@jakarta.annotation.Nullable String direName) {
    this.direName = direName;
  }


  public MatchObjectResponse leagueid(@jakarta.annotation.Nullable Long leagueid) {
    this.leagueid = leagueid;
    return this;
  }

  /**
   * Identifier for the league the match took place in
   * @return leagueid
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LEAGUEID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getLeagueid() {
    return leagueid;
  }


  @JsonProperty(JSON_PROPERTY_LEAGUEID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLeagueid(@jakarta.annotation.Nullable Long leagueid) {
    this.leagueid = leagueid;
  }


  public MatchObjectResponse leagueName(@jakarta.annotation.Nullable String leagueName) {
    this.leagueName = leagueName;
    return this;
  }

  /**
   * Name of league the match took place in
   * @return leagueName
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LEAGUE_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLeagueName() {
    return leagueName;
  }


  @JsonProperty(JSON_PROPERTY_LEAGUE_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLeagueName(@jakarta.annotation.Nullable String leagueName) {
    this.leagueName = leagueName;
  }


  public MatchObjectResponse seriesId(@jakarta.annotation.Nullable Long seriesId) {
    this.seriesId = seriesId;
    return this;
  }

  /**
   * Identifier for the series of the match
   * @return seriesId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SERIES_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getSeriesId() {
    return seriesId;
  }


  @JsonProperty(JSON_PROPERTY_SERIES_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSeriesId(@jakarta.annotation.Nullable Long seriesId) {
    this.seriesId = seriesId;
  }


  public MatchObjectResponse seriesType(@jakarta.annotation.Nullable Long seriesType) {
    this.seriesType = seriesType;
    return this;
  }

  /**
   * Type of series the match was
   * @return seriesType
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SERIES_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getSeriesType() {
    return seriesType;
  }


  @JsonProperty(JSON_PROPERTY_SERIES_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSeriesType(@jakarta.annotation.Nullable Long seriesType) {
    this.seriesType = seriesType;
  }


  public MatchObjectResponse radiantScore(@jakarta.annotation.Nullable Long radiantScore) {
    this.radiantScore = radiantScore;
    return this;
  }

  /**
   * Number of kills the Radiant team had when the match ended
   * @return radiantScore
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RADIANT_SCORE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getRadiantScore() {
    return radiantScore;
  }


  @JsonProperty(JSON_PROPERTY_RADIANT_SCORE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRadiantScore(@jakarta.annotation.Nullable Long radiantScore) {
    this.radiantScore = radiantScore;
  }


  public MatchObjectResponse direScore(@jakarta.annotation.Nullable Long direScore) {
    this.direScore = direScore;
    return this;
  }

  /**
   * Number of kills the Dire team had when the match ended
   * @return direScore
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DIRE_SCORE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getDireScore() {
    return direScore;
  }


  @JsonProperty(JSON_PROPERTY_DIRE_SCORE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDireScore(@jakarta.annotation.Nullable Long direScore) {
    this.direScore = direScore;
  }


  public MatchObjectResponse radiantWin(@jakarta.annotation.Nullable Boolean radiantWin) {
    this.radiantWin = JsonNullable.<Boolean>of(radiantWin);
    return this;
  }

  /**
   * Boolean indicating whether Radiant won the match
   * @return radiantWin
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Boolean getRadiantWin() {
        return radiantWin.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_RADIANT_WIN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Boolean> getRadiantWin_JsonNullable() {
    return radiantWin;
  }
  
  @JsonProperty(JSON_PROPERTY_RADIANT_WIN)
  public void setRadiantWin_JsonNullable(JsonNullable<Boolean> radiantWin) {
    this.radiantWin = radiantWin;
  }

  public void setRadiantWin(@jakarta.annotation.Nullable Boolean radiantWin) {
    this.radiantWin = JsonNullable.<Boolean>of(radiantWin);
  }


  public MatchObjectResponse radiant(@jakarta.annotation.Nullable Boolean radiant) {
    this.radiant = radiant;
    return this;
  }

  /**
   * Whether the team/player/hero was on Radiant
   * @return radiant
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RADIANT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getRadiant() {
    return radiant;
  }


  @JsonProperty(JSON_PROPERTY_RADIANT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRadiant(@jakarta.annotation.Nullable Boolean radiant) {
    this.radiant = radiant;
  }


  /**
   * Return true if this MatchObjectResponse object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MatchObjectResponse matchObjectResponse = (MatchObjectResponse) o;
    return Objects.equals(this.matchId, matchObjectResponse.matchId) &&
        Objects.equals(this.duration, matchObjectResponse.duration) &&
        Objects.equals(this.startTime, matchObjectResponse.startTime) &&
        Objects.equals(this.radiantTeamId, matchObjectResponse.radiantTeamId) &&
        Objects.equals(this.radiantName, matchObjectResponse.radiantName) &&
        Objects.equals(this.direTeamId, matchObjectResponse.direTeamId) &&
        Objects.equals(this.direName, matchObjectResponse.direName) &&
        Objects.equals(this.leagueid, matchObjectResponse.leagueid) &&
        Objects.equals(this.leagueName, matchObjectResponse.leagueName) &&
        Objects.equals(this.seriesId, matchObjectResponse.seriesId) &&
        Objects.equals(this.seriesType, matchObjectResponse.seriesType) &&
        Objects.equals(this.radiantScore, matchObjectResponse.radiantScore) &&
        Objects.equals(this.direScore, matchObjectResponse.direScore) &&
        equalsNullable(this.radiantWin, matchObjectResponse.radiantWin) &&
        Objects.equals(this.radiant, matchObjectResponse.radiant);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(matchId, duration, startTime, radiantTeamId, radiantName, direTeamId, direName, leagueid, leagueName, seriesId, seriesType, radiantScore, direScore, hashCodeNullable(radiantWin), radiant);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MatchObjectResponse {\n");
    sb.append("    matchId: ").append(toIndentedString(matchId)).append("\n");
    sb.append("    duration: ").append(toIndentedString(duration)).append("\n");
    sb.append("    startTime: ").append(toIndentedString(startTime)).append("\n");
    sb.append("    radiantTeamId: ").append(toIndentedString(radiantTeamId)).append("\n");
    sb.append("    radiantName: ").append(toIndentedString(radiantName)).append("\n");
    sb.append("    direTeamId: ").append(toIndentedString(direTeamId)).append("\n");
    sb.append("    direName: ").append(toIndentedString(direName)).append("\n");
    sb.append("    leagueid: ").append(toIndentedString(leagueid)).append("\n");
    sb.append("    leagueName: ").append(toIndentedString(leagueName)).append("\n");
    sb.append("    seriesId: ").append(toIndentedString(seriesId)).append("\n");
    sb.append("    seriesType: ").append(toIndentedString(seriesType)).append("\n");
    sb.append("    radiantScore: ").append(toIndentedString(radiantScore)).append("\n");
    sb.append("    direScore: ").append(toIndentedString(direScore)).append("\n");
    sb.append("    radiantWin: ").append(toIndentedString(radiantWin)).append("\n");
    sb.append("    radiant: ").append(toIndentedString(radiant)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

