/*
 * OpenDota API
 * # Introduction The OpenDota API provides Dota 2 related data including advanced match data extracted from match replays.  You can find data that can be used to convert hero and ability IDs and other information provided by the API from the [dotaconstants](https://github.com/odota/dotaconstants) repository.  You can use the API without a key, but registering for a key allows increased rate limits and usage. Check out the [API page](https://www.opendota.com/api-keys) to learn more.     
 *
 * The version of the OpenAPI document: 31.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ako.dbuff.dotapi.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.ako.dbuff.dotapi.invoker.JSON;


/**
 * MatchResponsePlayersInnerNeutralItemHistoryInner
 */
@JsonPropertyOrder({
  MatchResponsePlayersInnerNeutralItemHistoryInner.JSON_PROPERTY_TIME,
  MatchResponsePlayersInnerNeutralItemHistoryInner.JSON_PROPERTY_ITEM_NEUTRAL,
  MatchResponsePlayersInnerNeutralItemHistoryInner.JSON_PROPERTY_ITEM_NEUTRAL_ENHANCEMENT
})
@JsonTypeName("MatchResponse_players_inner_neutral_item_history_inner")
@com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class MatchResponsePlayersInnerNeutralItemHistoryInner {
  public static final String JSON_PROPERTY_TIME = "time";
  @jakarta.annotation.Nullable
  private Long time;

  public static final String JSON_PROPERTY_ITEM_NEUTRAL = "item_neutral";
  @jakarta.annotation.Nullable
  private String itemNeutral;

  public static final String JSON_PROPERTY_ITEM_NEUTRAL_ENHANCEMENT = "item_neutral_enhancement";
  @jakarta.annotation.Nullable
  private String itemNeutralEnhancement;

  public MatchResponsePlayersInnerNeutralItemHistoryInner() { 
  }

  public MatchResponsePlayersInnerNeutralItemHistoryInner time(@jakarta.annotation.Nullable Long time) {
    this.time = time;
    return this;
  }

  /**
   * Time in seconds at which the item was crafted
   * @return time
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getTime() {
    return time;
  }


  @JsonProperty(JSON_PROPERTY_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTime(@jakarta.annotation.Nullable Long time) {
    this.time = time;
  }


  public MatchResponsePlayersInnerNeutralItemHistoryInner itemNeutral(@jakarta.annotation.Nullable String itemNeutral) {
    this.itemNeutral = itemNeutral;
    return this;
  }

  /**
   * Neutral item name
   * @return itemNeutral
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ITEM_NEUTRAL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getItemNeutral() {
    return itemNeutral;
  }


  @JsonProperty(JSON_PROPERTY_ITEM_NEUTRAL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setItemNeutral(@jakarta.annotation.Nullable String itemNeutral) {
    this.itemNeutral = itemNeutral;
  }


  public MatchResponsePlayersInnerNeutralItemHistoryInner itemNeutralEnhancement(@jakarta.annotation.Nullable String itemNeutralEnhancement) {
    this.itemNeutralEnhancement = itemNeutralEnhancement;
    return this;
  }

  /**
   * Neutral enhancement name
   * @return itemNeutralEnhancement
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ITEM_NEUTRAL_ENHANCEMENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getItemNeutralEnhancement() {
    return itemNeutralEnhancement;
  }


  @JsonProperty(JSON_PROPERTY_ITEM_NEUTRAL_ENHANCEMENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setItemNeutralEnhancement(@jakarta.annotation.Nullable String itemNeutralEnhancement) {
    this.itemNeutralEnhancement = itemNeutralEnhancement;
  }


  /**
   * Return true if this MatchResponse_players_inner_neutral_item_history_inner object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MatchResponsePlayersInnerNeutralItemHistoryInner matchResponsePlayersInnerNeutralItemHistoryInner = (MatchResponsePlayersInnerNeutralItemHistoryInner) o;
    return Objects.equals(this.time, matchResponsePlayersInnerNeutralItemHistoryInner.time) &&
        Objects.equals(this.itemNeutral, matchResponsePlayersInnerNeutralItemHistoryInner.itemNeutral) &&
        Objects.equals(this.itemNeutralEnhancement, matchResponsePlayersInnerNeutralItemHistoryInner.itemNeutralEnhancement);
  }

  @Override
  public int hashCode() {
    return Objects.hash(time, itemNeutral, itemNeutralEnhancement);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MatchResponsePlayersInnerNeutralItemHistoryInner {\n");
    sb.append("    time: ").append(toIndentedString(time)).append("\n");
    sb.append("    itemNeutral: ").append(toIndentedString(itemNeutral)).append("\n");
    sb.append("    itemNeutralEnhancement: ").append(toIndentedString(itemNeutralEnhancement)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

