/*
 * OpenDota API
 * # Introduction The OpenDota API provides Dota 2 related data including advanced match data extracted from match replays.  You can find data that can be used to convert hero and ability IDs and other information provided by the API from the [dotaconstants](https://github.com/odota/dotaconstants) repository.  Without a key, you can make 2,000 free calls per day at a rate limit of 60 requests/minute. We also offer a Premium Tier with unlimited API calls and higher rate limits. Check out the [API page](https://www.opendota.com/api-keys) to learn more.     
 *
 * The version of the OpenAPI document: 26.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ako.dbuff.dotapi.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.ako.dbuff.dotapi.invoker.JSON;


/**
 * PlayerTotalsResponse
 */
@JsonPropertyOrder({
  PlayerTotalsResponse.JSON_PROPERTY_FIELD,
  PlayerTotalsResponse.JSON_PROPERTY_N,
  PlayerTotalsResponse.JSON_PROPERTY_SUM
})
@com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class PlayerTotalsResponse {
  public static final String JSON_PROPERTY_FIELD = "field";
  @jakarta.annotation.Nullable
  private String field;

  public static final String JSON_PROPERTY_N = "n";
  @jakarta.annotation.Nullable
  private Long n;

  public static final String JSON_PROPERTY_SUM = "sum";
  @jakarta.annotation.Nullable
  private BigDecimal sum;

  public PlayerTotalsResponse() { 
  }

  public PlayerTotalsResponse field(@jakarta.annotation.Nullable String field) {
    this.field = field;
    return this;
  }

  /**
   * field
   * @return field
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FIELD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getField() {
    return field;
  }


  @JsonProperty(JSON_PROPERTY_FIELD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setField(@jakarta.annotation.Nullable String field) {
    this.field = field;
  }


  public PlayerTotalsResponse n(@jakarta.annotation.Nullable Long n) {
    this.n = n;
    return this;
  }

  /**
   * number
   * @return n
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_N)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getN() {
    return n;
  }


  @JsonProperty(JSON_PROPERTY_N)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setN(@jakarta.annotation.Nullable Long n) {
    this.n = n;
  }


  public PlayerTotalsResponse sum(@jakarta.annotation.Nullable BigDecimal sum) {
    this.sum = sum;
    return this;
  }

  /**
   * sum
   * @return sum
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SUM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getSum() {
    return sum;
  }


  @JsonProperty(JSON_PROPERTY_SUM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSum(@jakarta.annotation.Nullable BigDecimal sum) {
    this.sum = sum;
  }


  /**
   * Return true if this PlayerTotalsResponse object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PlayerTotalsResponse playerTotalsResponse = (PlayerTotalsResponse) o;
    return Objects.equals(this.field, playerTotalsResponse.field) &&
        Objects.equals(this.n, playerTotalsResponse.n) &&
        Objects.equals(this.sum, playerTotalsResponse.sum);
  }

  @Override
  public int hashCode() {
    return Objects.hash(field, n, sum);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PlayerTotalsResponse {\n");
    sb.append("    field: ").append(toIndentedString(field)).append("\n");
    sb.append("    n: ").append(toIndentedString(n)).append("\n");
    sb.append("    sum: ").append(toIndentedString(sum)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

