/*
 * OpenDota API
 * # Introduction The OpenDota API provides Dota 2 related data including advanced match data extracted from match replays.  You can find data that can be used to convert hero and ability IDs and other information provided by the API from the [dotaconstants](https://github.com/odota/dotaconstants) repository.  Without a key, you can make 2,000 free calls per day at a rate limit of 60 requests/minute. We also offer a Premium Tier with unlimited API calls and higher rate limits. Check out the [API page](https://www.opendota.com/api-keys) to learn more.     
 *
 * The version of the OpenAPI document: 26.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ako.dbuff.dotapi.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.ako.dbuff.dotapi.model.PlayersResponseProfile;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.ako.dbuff.dotapi.invoker.JSON;


/**
 * PlayersResponse
 */
@JsonPropertyOrder({
  PlayersResponse.JSON_PROPERTY_SOLO_COMPETITIVE_RANK,
  PlayersResponse.JSON_PROPERTY_COMPETITIVE_RANK,
  PlayersResponse.JSON_PROPERTY_RANK_TIER,
  PlayersResponse.JSON_PROPERTY_LEADERBOARD_RANK,
  PlayersResponse.JSON_PROPERTY_PROFILE
})
@com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class PlayersResponse {
  public static final String JSON_PROPERTY_SOLO_COMPETITIVE_RANK = "solo_competitive_rank";
  private JsonNullable<Long> soloCompetitiveRank = JsonNullable.<Long>undefined();

  public static final String JSON_PROPERTY_COMPETITIVE_RANK = "competitive_rank";
  private JsonNullable<Long> competitiveRank = JsonNullable.<Long>undefined();

  public static final String JSON_PROPERTY_RANK_TIER = "rank_tier";
  private JsonNullable<BigDecimal> rankTier = JsonNullable.<BigDecimal>undefined();

  public static final String JSON_PROPERTY_LEADERBOARD_RANK = "leaderboard_rank";
  private JsonNullable<BigDecimal> leaderboardRank = JsonNullable.<BigDecimal>undefined();

  public static final String JSON_PROPERTY_PROFILE = "profile";
  @jakarta.annotation.Nullable
  private PlayersResponseProfile profile;

  public PlayersResponse() { 
  }

  public PlayersResponse soloCompetitiveRank(@jakarta.annotation.Nullable Long soloCompetitiveRank) {
    this.soloCompetitiveRank = JsonNullable.<Long>of(soloCompetitiveRank);
    return this;
  }

  /**
   * solo_competitive_rank
   * @return soloCompetitiveRank
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Long getSoloCompetitiveRank() {
        return soloCompetitiveRank.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_SOLO_COMPETITIVE_RANK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Long> getSoloCompetitiveRank_JsonNullable() {
    return soloCompetitiveRank;
  }
  
  @JsonProperty(JSON_PROPERTY_SOLO_COMPETITIVE_RANK)
  public void setSoloCompetitiveRank_JsonNullable(JsonNullable<Long> soloCompetitiveRank) {
    this.soloCompetitiveRank = soloCompetitiveRank;
  }

  public void setSoloCompetitiveRank(@jakarta.annotation.Nullable Long soloCompetitiveRank) {
    this.soloCompetitiveRank = JsonNullable.<Long>of(soloCompetitiveRank);
  }


  public PlayersResponse competitiveRank(@jakarta.annotation.Nullable Long competitiveRank) {
    this.competitiveRank = JsonNullable.<Long>of(competitiveRank);
    return this;
  }

  /**
   * competitive_rank
   * @return competitiveRank
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Long getCompetitiveRank() {
        return competitiveRank.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_COMPETITIVE_RANK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Long> getCompetitiveRank_JsonNullable() {
    return competitiveRank;
  }
  
  @JsonProperty(JSON_PROPERTY_COMPETITIVE_RANK)
  public void setCompetitiveRank_JsonNullable(JsonNullable<Long> competitiveRank) {
    this.competitiveRank = competitiveRank;
  }

  public void setCompetitiveRank(@jakarta.annotation.Nullable Long competitiveRank) {
    this.competitiveRank = JsonNullable.<Long>of(competitiveRank);
  }


  public PlayersResponse rankTier(@jakarta.annotation.Nullable BigDecimal rankTier) {
    this.rankTier = JsonNullable.<BigDecimal>of(rankTier);
    return this;
  }

  /**
   * rank_tier
   * @return rankTier
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public BigDecimal getRankTier() {
        return rankTier.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_RANK_TIER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<BigDecimal> getRankTier_JsonNullable() {
    return rankTier;
  }
  
  @JsonProperty(JSON_PROPERTY_RANK_TIER)
  public void setRankTier_JsonNullable(JsonNullable<BigDecimal> rankTier) {
    this.rankTier = rankTier;
  }

  public void setRankTier(@jakarta.annotation.Nullable BigDecimal rankTier) {
    this.rankTier = JsonNullable.<BigDecimal>of(rankTier);
  }


  public PlayersResponse leaderboardRank(@jakarta.annotation.Nullable BigDecimal leaderboardRank) {
    this.leaderboardRank = JsonNullable.<BigDecimal>of(leaderboardRank);
    return this;
  }

  /**
   * leaderboard_rank
   * @return leaderboardRank
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public BigDecimal getLeaderboardRank() {
        return leaderboardRank.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_LEADERBOARD_RANK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<BigDecimal> getLeaderboardRank_JsonNullable() {
    return leaderboardRank;
  }
  
  @JsonProperty(JSON_PROPERTY_LEADERBOARD_RANK)
  public void setLeaderboardRank_JsonNullable(JsonNullable<BigDecimal> leaderboardRank) {
    this.leaderboardRank = leaderboardRank;
  }

  public void setLeaderboardRank(@jakarta.annotation.Nullable BigDecimal leaderboardRank) {
    this.leaderboardRank = JsonNullable.<BigDecimal>of(leaderboardRank);
  }


  public PlayersResponse profile(@jakarta.annotation.Nullable PlayersResponseProfile profile) {
    this.profile = profile;
    return this;
  }

  /**
   * Get profile
   * @return profile
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PROFILE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public PlayersResponseProfile getProfile() {
    return profile;
  }


  @JsonProperty(JSON_PROPERTY_PROFILE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProfile(@jakarta.annotation.Nullable PlayersResponseProfile profile) {
    this.profile = profile;
  }


  /**
   * Return true if this PlayersResponse object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PlayersResponse playersResponse = (PlayersResponse) o;
    return equalsNullable(this.soloCompetitiveRank, playersResponse.soloCompetitiveRank) &&
        equalsNullable(this.competitiveRank, playersResponse.competitiveRank) &&
        equalsNullable(this.rankTier, playersResponse.rankTier) &&
        equalsNullable(this.leaderboardRank, playersResponse.leaderboardRank) &&
        Objects.equals(this.profile, playersResponse.profile);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(hashCodeNullable(soloCompetitiveRank), hashCodeNullable(competitiveRank), hashCodeNullable(rankTier), hashCodeNullable(leaderboardRank), profile);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PlayersResponse {\n");
    sb.append("    soloCompetitiveRank: ").append(toIndentedString(soloCompetitiveRank)).append("\n");
    sb.append("    competitiveRank: ").append(toIndentedString(competitiveRank)).append("\n");
    sb.append("    rankTier: ").append(toIndentedString(rankTier)).append("\n");
    sb.append("    leaderboardRank: ").append(toIndentedString(leaderboardRank)).append("\n");
    sb.append("    profile: ").append(toIndentedString(profile)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

