/*
 * OpenDota API
 * # Introduction The OpenDota API provides Dota 2 related data including advanced match data extracted from match replays.  You can find data that can be used to convert hero and ability IDs and other information provided by the API from the [dotaconstants](https://github.com/odota/dotaconstants) repository.  You can use the API without a key, but registering for a key allows increased rate limits and usage. Check out the [API page](https://www.opendota.com/api-keys) to learn more.     
 *
 * The version of the OpenAPI document: 31.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ako.dbuff.dotapi.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.ako.dbuff.dotapi.invoker.JSON;


/**
 * profile
 */
@JsonPropertyOrder({
  PlayersResponseProfile.JSON_PROPERTY_ACCOUNT_ID,
  PlayersResponseProfile.JSON_PROPERTY_PERSONANAME,
  PlayersResponseProfile.JSON_PROPERTY_NAME,
  PlayersResponseProfile.JSON_PROPERTY_PLUS,
  PlayersResponseProfile.JSON_PROPERTY_CHEESE,
  PlayersResponseProfile.JSON_PROPERTY_STEAMID,
  PlayersResponseProfile.JSON_PROPERTY_AVATAR,
  PlayersResponseProfile.JSON_PROPERTY_AVATARMEDIUM,
  PlayersResponseProfile.JSON_PROPERTY_AVATARFULL,
  PlayersResponseProfile.JSON_PROPERTY_PROFILEURL,
  PlayersResponseProfile.JSON_PROPERTY_LAST_LOGIN,
  PlayersResponseProfile.JSON_PROPERTY_LOCCOUNTRYCODE,
  PlayersResponseProfile.JSON_PROPERTY_IS_CONTRIBUTOR,
  PlayersResponseProfile.JSON_PROPERTY_IS_SUBSCRIBER
})
@JsonTypeName("PlayersResponse_profile")
@com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class PlayersResponseProfile {
  public static final String JSON_PROPERTY_ACCOUNT_ID = "account_id";
  @jakarta.annotation.Nullable
  private Long accountId;

  public static final String JSON_PROPERTY_PERSONANAME = "personaname";
  private JsonNullable<String> personaname = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_NAME = "name";
  private JsonNullable<String> name = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_PLUS = "plus";
  @jakarta.annotation.Nullable
  private Boolean plus;

  public static final String JSON_PROPERTY_CHEESE = "cheese";
  private JsonNullable<Long> cheese = JsonNullable.<Long>undefined();

  public static final String JSON_PROPERTY_STEAMID = "steamid";
  private JsonNullable<String> steamid = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_AVATAR = "avatar";
  private JsonNullable<String> avatar = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_AVATARMEDIUM = "avatarmedium";
  private JsonNullable<String> avatarmedium = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_AVATARFULL = "avatarfull";
  private JsonNullable<String> avatarfull = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_PROFILEURL = "profileurl";
  private JsonNullable<String> profileurl = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_LAST_LOGIN = "last_login";
  private JsonNullable<String> lastLogin = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_LOCCOUNTRYCODE = "loccountrycode";
  private JsonNullable<String> loccountrycode = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_IS_CONTRIBUTOR = "is_contributor";
  @jakarta.annotation.Nullable
  private Boolean isContributor = false;

  public static final String JSON_PROPERTY_IS_SUBSCRIBER = "is_subscriber";
  @jakarta.annotation.Nullable
  private Boolean isSubscriber = false;

  public PlayersResponseProfile() { 
  }

  public PlayersResponseProfile accountId(@jakarta.annotation.Nullable Long accountId) {
    this.accountId = accountId;
    return this;
  }

  /**
   * The player account ID
   * @return accountId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ACCOUNT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getAccountId() {
    return accountId;
  }


  @JsonProperty(JSON_PROPERTY_ACCOUNT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAccountId(@jakarta.annotation.Nullable Long accountId) {
    this.accountId = accountId;
  }


  public PlayersResponseProfile personaname(@jakarta.annotation.Nullable String personaname) {
    this.personaname = JsonNullable.<String>of(personaname);
    return this;
  }

  /**
   * Player&#39;s Steam name
   * @return personaname
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getPersonaname() {
        return personaname.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_PERSONANAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getPersonaname_JsonNullable() {
    return personaname;
  }
  
  @JsonProperty(JSON_PROPERTY_PERSONANAME)
  public void setPersonaname_JsonNullable(JsonNullable<String> personaname) {
    this.personaname = personaname;
  }

  public void setPersonaname(@jakarta.annotation.Nullable String personaname) {
    this.personaname = JsonNullable.<String>of(personaname);
  }


  public PlayersResponseProfile name(@jakarta.annotation.Nullable String name) {
    this.name = JsonNullable.<String>of(name);
    return this;
  }

  /**
   * name
   * @return name
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getName() {
        return name.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getName_JsonNullable() {
    return name;
  }
  
  @JsonProperty(JSON_PROPERTY_NAME)
  public void setName_JsonNullable(JsonNullable<String> name) {
    this.name = name;
  }

  public void setName(@jakarta.annotation.Nullable String name) {
    this.name = JsonNullable.<String>of(name);
  }


  public PlayersResponseProfile plus(@jakarta.annotation.Nullable Boolean plus) {
    this.plus = plus;
    return this;
  }

  /**
   * Boolean indicating status of current Dota Plus subscription
   * @return plus
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PLUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getPlus() {
    return plus;
  }


  @JsonProperty(JSON_PROPERTY_PLUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPlus(@jakarta.annotation.Nullable Boolean plus) {
    this.plus = plus;
  }


  public PlayersResponseProfile cheese(@jakarta.annotation.Nullable Long cheese) {
    this.cheese = JsonNullable.<Long>of(cheese);
    return this;
  }

  /**
   * cheese
   * @return cheese
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Long getCheese() {
        return cheese.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_CHEESE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Long> getCheese_JsonNullable() {
    return cheese;
  }
  
  @JsonProperty(JSON_PROPERTY_CHEESE)
  public void setCheese_JsonNullable(JsonNullable<Long> cheese) {
    this.cheese = cheese;
  }

  public void setCheese(@jakarta.annotation.Nullable Long cheese) {
    this.cheese = JsonNullable.<Long>of(cheese);
  }


  public PlayersResponseProfile steamid(@jakarta.annotation.Nullable String steamid) {
    this.steamid = JsonNullable.<String>of(steamid);
    return this;
  }

  /**
   * steamid
   * @return steamid
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getSteamid() {
        return steamid.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_STEAMID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getSteamid_JsonNullable() {
    return steamid;
  }
  
  @JsonProperty(JSON_PROPERTY_STEAMID)
  public void setSteamid_JsonNullable(JsonNullable<String> steamid) {
    this.steamid = steamid;
  }

  public void setSteamid(@jakarta.annotation.Nullable String steamid) {
    this.steamid = JsonNullable.<String>of(steamid);
  }


  public PlayersResponseProfile avatar(@jakarta.annotation.Nullable String avatar) {
    this.avatar = JsonNullable.<String>of(avatar);
    return this;
  }

  /**
   * avatar
   * @return avatar
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getAvatar() {
        return avatar.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_AVATAR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getAvatar_JsonNullable() {
    return avatar;
  }
  
  @JsonProperty(JSON_PROPERTY_AVATAR)
  public void setAvatar_JsonNullable(JsonNullable<String> avatar) {
    this.avatar = avatar;
  }

  public void setAvatar(@jakarta.annotation.Nullable String avatar) {
    this.avatar = JsonNullable.<String>of(avatar);
  }


  public PlayersResponseProfile avatarmedium(@jakarta.annotation.Nullable String avatarmedium) {
    this.avatarmedium = JsonNullable.<String>of(avatarmedium);
    return this;
  }

  /**
   * avatarmedium
   * @return avatarmedium
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getAvatarmedium() {
        return avatarmedium.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_AVATARMEDIUM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getAvatarmedium_JsonNullable() {
    return avatarmedium;
  }
  
  @JsonProperty(JSON_PROPERTY_AVATARMEDIUM)
  public void setAvatarmedium_JsonNullable(JsonNullable<String> avatarmedium) {
    this.avatarmedium = avatarmedium;
  }

  public void setAvatarmedium(@jakarta.annotation.Nullable String avatarmedium) {
    this.avatarmedium = JsonNullable.<String>of(avatarmedium);
  }


  public PlayersResponseProfile avatarfull(@jakarta.annotation.Nullable String avatarfull) {
    this.avatarfull = JsonNullable.<String>of(avatarfull);
    return this;
  }

  /**
   * avatarfull
   * @return avatarfull
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getAvatarfull() {
        return avatarfull.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_AVATARFULL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getAvatarfull_JsonNullable() {
    return avatarfull;
  }
  
  @JsonProperty(JSON_PROPERTY_AVATARFULL)
  public void setAvatarfull_JsonNullable(JsonNullable<String> avatarfull) {
    this.avatarfull = avatarfull;
  }

  public void setAvatarfull(@jakarta.annotation.Nullable String avatarfull) {
    this.avatarfull = JsonNullable.<String>of(avatarfull);
  }


  public PlayersResponseProfile profileurl(@jakarta.annotation.Nullable String profileurl) {
    this.profileurl = JsonNullable.<String>of(profileurl);
    return this;
  }

  /**
   * profileurl
   * @return profileurl
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getProfileurl() {
        return profileurl.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_PROFILEURL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getProfileurl_JsonNullable() {
    return profileurl;
  }
  
  @JsonProperty(JSON_PROPERTY_PROFILEURL)
  public void setProfileurl_JsonNullable(JsonNullable<String> profileurl) {
    this.profileurl = profileurl;
  }

  public void setProfileurl(@jakarta.annotation.Nullable String profileurl) {
    this.profileurl = JsonNullable.<String>of(profileurl);
  }


  public PlayersResponseProfile lastLogin(@jakarta.annotation.Nullable String lastLogin) {
    this.lastLogin = JsonNullable.<String>of(lastLogin);
    return this;
  }

  /**
   * last_login
   * @return lastLogin
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getLastLogin() {
        return lastLogin.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_LAST_LOGIN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getLastLogin_JsonNullable() {
    return lastLogin;
  }
  
  @JsonProperty(JSON_PROPERTY_LAST_LOGIN)
  public void setLastLogin_JsonNullable(JsonNullable<String> lastLogin) {
    this.lastLogin = lastLogin;
  }

  public void setLastLogin(@jakarta.annotation.Nullable String lastLogin) {
    this.lastLogin = JsonNullable.<String>of(lastLogin);
  }


  public PlayersResponseProfile loccountrycode(@jakarta.annotation.Nullable String loccountrycode) {
    this.loccountrycode = JsonNullable.<String>of(loccountrycode);
    return this;
  }

  /**
   * loccountrycode
   * @return loccountrycode
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getLoccountrycode() {
        return loccountrycode.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_LOCCOUNTRYCODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getLoccountrycode_JsonNullable() {
    return loccountrycode;
  }
  
  @JsonProperty(JSON_PROPERTY_LOCCOUNTRYCODE)
  public void setLoccountrycode_JsonNullable(JsonNullable<String> loccountrycode) {
    this.loccountrycode = loccountrycode;
  }

  public void setLoccountrycode(@jakarta.annotation.Nullable String loccountrycode) {
    this.loccountrycode = JsonNullable.<String>of(loccountrycode);
  }


  public PlayersResponseProfile isContributor(@jakarta.annotation.Nullable Boolean isContributor) {
    this.isContributor = isContributor;
    return this;
  }

  /**
   * Boolean indicating if the user contributed to the development of OpenDota
   * @return isContributor
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_IS_CONTRIBUTOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getIsContributor() {
    return isContributor;
  }


  @JsonProperty(JSON_PROPERTY_IS_CONTRIBUTOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIsContributor(@jakarta.annotation.Nullable Boolean isContributor) {
    this.isContributor = isContributor;
  }


  public PlayersResponseProfile isSubscriber(@jakarta.annotation.Nullable Boolean isSubscriber) {
    this.isSubscriber = isSubscriber;
    return this;
  }

  /**
   * Boolean indicating if the user subscribed to OpenDota
   * @return isSubscriber
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_IS_SUBSCRIBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getIsSubscriber() {
    return isSubscriber;
  }


  @JsonProperty(JSON_PROPERTY_IS_SUBSCRIBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIsSubscriber(@jakarta.annotation.Nullable Boolean isSubscriber) {
    this.isSubscriber = isSubscriber;
  }


  /**
   * Return true if this PlayersResponse_profile object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PlayersResponseProfile playersResponseProfile = (PlayersResponseProfile) o;
    return Objects.equals(this.accountId, playersResponseProfile.accountId) &&
        equalsNullable(this.personaname, playersResponseProfile.personaname) &&
        equalsNullable(this.name, playersResponseProfile.name) &&
        Objects.equals(this.plus, playersResponseProfile.plus) &&
        equalsNullable(this.cheese, playersResponseProfile.cheese) &&
        equalsNullable(this.steamid, playersResponseProfile.steamid) &&
        equalsNullable(this.avatar, playersResponseProfile.avatar) &&
        equalsNullable(this.avatarmedium, playersResponseProfile.avatarmedium) &&
        equalsNullable(this.avatarfull, playersResponseProfile.avatarfull) &&
        equalsNullable(this.profileurl, playersResponseProfile.profileurl) &&
        equalsNullable(this.lastLogin, playersResponseProfile.lastLogin) &&
        equalsNullable(this.loccountrycode, playersResponseProfile.loccountrycode) &&
        Objects.equals(this.isContributor, playersResponseProfile.isContributor) &&
        Objects.equals(this.isSubscriber, playersResponseProfile.isSubscriber);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(accountId, hashCodeNullable(personaname), hashCodeNullable(name), plus, hashCodeNullable(cheese), hashCodeNullable(steamid), hashCodeNullable(avatar), hashCodeNullable(avatarmedium), hashCodeNullable(avatarfull), hashCodeNullable(profileurl), hashCodeNullable(lastLogin), hashCodeNullable(loccountrycode), isContributor, isSubscriber);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PlayersResponseProfile {\n");
    sb.append("    accountId: ").append(toIndentedString(accountId)).append("\n");
    sb.append("    personaname: ").append(toIndentedString(personaname)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    plus: ").append(toIndentedString(plus)).append("\n");
    sb.append("    cheese: ").append(toIndentedString(cheese)).append("\n");
    sb.append("    steamid: ").append(toIndentedString(steamid)).append("\n");
    sb.append("    avatar: ").append(toIndentedString(avatar)).append("\n");
    sb.append("    avatarmedium: ").append(toIndentedString(avatarmedium)).append("\n");
    sb.append("    avatarfull: ").append(toIndentedString(avatarfull)).append("\n");
    sb.append("    profileurl: ").append(toIndentedString(profileurl)).append("\n");
    sb.append("    lastLogin: ").append(toIndentedString(lastLogin)).append("\n");
    sb.append("    loccountrycode: ").append(toIndentedString(loccountrycode)).append("\n");
    sb.append("    isContributor: ").append(toIndentedString(isContributor)).append("\n");
    sb.append("    isSubscriber: ").append(toIndentedString(isSubscriber)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

