/*
 * OpenDota API
 * # Introduction The OpenDota API provides Dota 2 related data including advanced match data extracted from match replays.  You can find data that can be used to convert hero and ability IDs and other information provided by the API from the [dotaconstants](https://github.com/odota/dotaconstants) repository.  Without a key, you can make 2,000 free calls per day at a rate limit of 60 requests/minute. We also offer a Premium Tier with unlimited API calls and higher rate limits. Check out the [API page](https://www.opendota.com/api-keys) to learn more.     
 *
 * The version of the OpenAPI document: 26.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ako.dbuff.dotapi.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.ako.dbuff.dotapi.invoker.JSON;


/**
 * match
 */
@JsonPropertyOrder({
  PlayerRecentMatchesResponse.JSON_PROPERTY_MATCH_ID,
  PlayerRecentMatchesResponse.JSON_PROPERTY_PLAYER_SLOT,
  PlayerRecentMatchesResponse.JSON_PROPERTY_RADIANT_WIN,
  PlayerRecentMatchesResponse.JSON_PROPERTY_DURATION,
  PlayerRecentMatchesResponse.JSON_PROPERTY_GAME_MODE,
  PlayerRecentMatchesResponse.JSON_PROPERTY_LOBBY_TYPE,
  PlayerRecentMatchesResponse.JSON_PROPERTY_HERO_ID,
  PlayerRecentMatchesResponse.JSON_PROPERTY_START_TIME,
  PlayerRecentMatchesResponse.JSON_PROPERTY_VERSION,
  PlayerRecentMatchesResponse.JSON_PROPERTY_KILLS,
  PlayerRecentMatchesResponse.JSON_PROPERTY_DEATHS,
  PlayerRecentMatchesResponse.JSON_PROPERTY_ASSISTS,
  PlayerRecentMatchesResponse.JSON_PROPERTY_SKILL,
  PlayerRecentMatchesResponse.JSON_PROPERTY_AVERAGE_RANK,
  PlayerRecentMatchesResponse.JSON_PROPERTY_XP_PER_MIN,
  PlayerRecentMatchesResponse.JSON_PROPERTY_GOLD_PER_MIN,
  PlayerRecentMatchesResponse.JSON_PROPERTY_HERO_DAMAGE,
  PlayerRecentMatchesResponse.JSON_PROPERTY_HERO_HEALING,
  PlayerRecentMatchesResponse.JSON_PROPERTY_LAST_HITS,
  PlayerRecentMatchesResponse.JSON_PROPERTY_LANE,
  PlayerRecentMatchesResponse.JSON_PROPERTY_LANE_ROLE,
  PlayerRecentMatchesResponse.JSON_PROPERTY_IS_ROAMING,
  PlayerRecentMatchesResponse.JSON_PROPERTY_CLUSTER,
  PlayerRecentMatchesResponse.JSON_PROPERTY_LEAVER_STATUS,
  PlayerRecentMatchesResponse.JSON_PROPERTY_PARTY_SIZE,
  PlayerRecentMatchesResponse.JSON_PROPERTY_HERO_VARIANT
})
@com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class PlayerRecentMatchesResponse {
  public static final String JSON_PROPERTY_MATCH_ID = "match_id";
  @jakarta.annotation.Nullable
  private Long matchId;

  public static final String JSON_PROPERTY_PLAYER_SLOT = "player_slot";
  private JsonNullable<Long> playerSlot = JsonNullable.<Long>undefined();

  public static final String JSON_PROPERTY_RADIANT_WIN = "radiant_win";
  private JsonNullable<Boolean> radiantWin = JsonNullable.<Boolean>undefined();

  public static final String JSON_PROPERTY_DURATION = "duration";
  @jakarta.annotation.Nullable
  private Long duration;

  public static final String JSON_PROPERTY_GAME_MODE = "game_mode";
  @jakarta.annotation.Nullable
  private Long gameMode;

  public static final String JSON_PROPERTY_LOBBY_TYPE = "lobby_type";
  @jakarta.annotation.Nullable
  private Long lobbyType;

  public static final String JSON_PROPERTY_HERO_ID = "hero_id";
  @jakarta.annotation.Nullable
  private Long heroId;

  public static final String JSON_PROPERTY_START_TIME = "start_time";
  @jakarta.annotation.Nullable
  private Long startTime;

  public static final String JSON_PROPERTY_VERSION = "version";
  private JsonNullable<Long> version = JsonNullable.<Long>undefined();

  public static final String JSON_PROPERTY_KILLS = "kills";
  @jakarta.annotation.Nullable
  private Long kills;

  public static final String JSON_PROPERTY_DEATHS = "deaths";
  @jakarta.annotation.Nullable
  private Long deaths;

  public static final String JSON_PROPERTY_ASSISTS = "assists";
  @jakarta.annotation.Nullable
  private Long assists;

  public static final String JSON_PROPERTY_SKILL = "skill";
  private JsonNullable<Long> skill = JsonNullable.<Long>undefined();

  public static final String JSON_PROPERTY_AVERAGE_RANK = "average_rank";
  private JsonNullable<Long> averageRank = JsonNullable.<Long>undefined();

  public static final String JSON_PROPERTY_XP_PER_MIN = "xp_per_min";
  @jakarta.annotation.Nullable
  private Long xpPerMin;

  public static final String JSON_PROPERTY_GOLD_PER_MIN = "gold_per_min";
  @jakarta.annotation.Nullable
  private Long goldPerMin;

  public static final String JSON_PROPERTY_HERO_DAMAGE = "hero_damage";
  @jakarta.annotation.Nullable
  private Long heroDamage;

  public static final String JSON_PROPERTY_HERO_HEALING = "hero_healing";
  @jakarta.annotation.Nullable
  private Long heroHealing;

  public static final String JSON_PROPERTY_LAST_HITS = "last_hits";
  @jakarta.annotation.Nullable
  private Long lastHits;

  public static final String JSON_PROPERTY_LANE = "lane";
  private JsonNullable<Long> lane = JsonNullable.<Long>undefined();

  public static final String JSON_PROPERTY_LANE_ROLE = "lane_role";
  private JsonNullable<Long> laneRole = JsonNullable.<Long>undefined();

  public static final String JSON_PROPERTY_IS_ROAMING = "is_roaming";
  private JsonNullable<Boolean> isRoaming = JsonNullable.<Boolean>undefined();

  public static final String JSON_PROPERTY_CLUSTER = "cluster";
  @jakarta.annotation.Nullable
  private Long cluster;

  public static final String JSON_PROPERTY_LEAVER_STATUS = "leaver_status";
  @jakarta.annotation.Nullable
  private Long leaverStatus;

  public static final String JSON_PROPERTY_PARTY_SIZE = "party_size";
  private JsonNullable<Long> partySize = JsonNullable.<Long>undefined();

  public static final String JSON_PROPERTY_HERO_VARIANT = "hero_variant";
  @jakarta.annotation.Nullable
  private Long heroVariant;

  public PlayerRecentMatchesResponse() { 
  }

  public PlayerRecentMatchesResponse matchId(@jakarta.annotation.Nullable Long matchId) {
    this.matchId = matchId;
    return this;
  }

  /**
   * The ID number of the match assigned by Valve
   * @return matchId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MATCH_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getMatchId() {
    return matchId;
  }


  @JsonProperty(JSON_PROPERTY_MATCH_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMatchId(@jakarta.annotation.Nullable Long matchId) {
    this.matchId = matchId;
  }


  public PlayerRecentMatchesResponse playerSlot(@jakarta.annotation.Nullable Long playerSlot) {
    this.playerSlot = JsonNullable.<Long>of(playerSlot);
    return this;
  }

  /**
   * Which slot the player is in. 0-127 are Radiant, 128-255 are Dire
   * @return playerSlot
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Long getPlayerSlot() {
        return playerSlot.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_PLAYER_SLOT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Long> getPlayerSlot_JsonNullable() {
    return playerSlot;
  }
  
  @JsonProperty(JSON_PROPERTY_PLAYER_SLOT)
  public void setPlayerSlot_JsonNullable(JsonNullable<Long> playerSlot) {
    this.playerSlot = playerSlot;
  }

  public void setPlayerSlot(@jakarta.annotation.Nullable Long playerSlot) {
    this.playerSlot = JsonNullable.<Long>of(playerSlot);
  }


  public PlayerRecentMatchesResponse radiantWin(@jakarta.annotation.Nullable Boolean radiantWin) {
    this.radiantWin = JsonNullable.<Boolean>of(radiantWin);
    return this;
  }

  /**
   * Boolean indicating whether Radiant won the match
   * @return radiantWin
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Boolean getRadiantWin() {
        return radiantWin.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_RADIANT_WIN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Boolean> getRadiantWin_JsonNullable() {
    return radiantWin;
  }
  
  @JsonProperty(JSON_PROPERTY_RADIANT_WIN)
  public void setRadiantWin_JsonNullable(JsonNullable<Boolean> radiantWin) {
    this.radiantWin = radiantWin;
  }

  public void setRadiantWin(@jakarta.annotation.Nullable Boolean radiantWin) {
    this.radiantWin = JsonNullable.<Boolean>of(radiantWin);
  }


  public PlayerRecentMatchesResponse duration(@jakarta.annotation.Nullable Long duration) {
    this.duration = duration;
    return this;
  }

  /**
   * Duration of the game in seconds
   * @return duration
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DURATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getDuration() {
    return duration;
  }


  @JsonProperty(JSON_PROPERTY_DURATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDuration(@jakarta.annotation.Nullable Long duration) {
    this.duration = duration;
  }


  public PlayerRecentMatchesResponse gameMode(@jakarta.annotation.Nullable Long gameMode) {
    this.gameMode = gameMode;
    return this;
  }

  /**
   * Integer corresponding to game mode played. List of constants can be found here: https://github.com/odota/dotaconstants/blob/master/json/game_mode.json
   * @return gameMode
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_GAME_MODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getGameMode() {
    return gameMode;
  }


  @JsonProperty(JSON_PROPERTY_GAME_MODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setGameMode(@jakarta.annotation.Nullable Long gameMode) {
    this.gameMode = gameMode;
  }


  public PlayerRecentMatchesResponse lobbyType(@jakarta.annotation.Nullable Long lobbyType) {
    this.lobbyType = lobbyType;
    return this;
  }

  /**
   * Integer corresponding to lobby type of match. List of constants can be found here: https://github.com/odota/dotaconstants/blob/master/json/lobby_type.json
   * @return lobbyType
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LOBBY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getLobbyType() {
    return lobbyType;
  }


  @JsonProperty(JSON_PROPERTY_LOBBY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLobbyType(@jakarta.annotation.Nullable Long lobbyType) {
    this.lobbyType = lobbyType;
  }


  public PlayerRecentMatchesResponse heroId(@jakarta.annotation.Nullable Long heroId) {
    this.heroId = heroId;
    return this;
  }

  /**
   * The ID value of the hero played
   * @return heroId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_HERO_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getHeroId() {
    return heroId;
  }


  @JsonProperty(JSON_PROPERTY_HERO_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHeroId(@jakarta.annotation.Nullable Long heroId) {
    this.heroId = heroId;
  }


  public PlayerRecentMatchesResponse startTime(@jakarta.annotation.Nullable Long startTime) {
    this.startTime = startTime;
    return this;
  }

  /**
   * The Unix timestamp at which the game started
   * @return startTime
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_START_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getStartTime() {
    return startTime;
  }


  @JsonProperty(JSON_PROPERTY_START_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStartTime(@jakarta.annotation.Nullable Long startTime) {
    this.startTime = startTime;
  }


  public PlayerRecentMatchesResponse version(@jakarta.annotation.Nullable Long version) {
    this.version = JsonNullable.<Long>of(version);
    return this;
  }

  /**
   * version
   * @return version
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Long getVersion() {
        return version.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_VERSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Long> getVersion_JsonNullable() {
    return version;
  }
  
  @JsonProperty(JSON_PROPERTY_VERSION)
  public void setVersion_JsonNullable(JsonNullable<Long> version) {
    this.version = version;
  }

  public void setVersion(@jakarta.annotation.Nullable Long version) {
    this.version = JsonNullable.<Long>of(version);
  }


  public PlayerRecentMatchesResponse kills(@jakarta.annotation.Nullable Long kills) {
    this.kills = kills;
    return this;
  }

  /**
   * Total kills the player had at the end of the match
   * @return kills
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_KILLS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getKills() {
    return kills;
  }


  @JsonProperty(JSON_PROPERTY_KILLS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setKills(@jakarta.annotation.Nullable Long kills) {
    this.kills = kills;
  }


  public PlayerRecentMatchesResponse deaths(@jakarta.annotation.Nullable Long deaths) {
    this.deaths = deaths;
    return this;
  }

  /**
   * Total deaths the player had at the end of the match
   * @return deaths
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DEATHS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getDeaths() {
    return deaths;
  }


  @JsonProperty(JSON_PROPERTY_DEATHS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDeaths(@jakarta.annotation.Nullable Long deaths) {
    this.deaths = deaths;
  }


  public PlayerRecentMatchesResponse assists(@jakarta.annotation.Nullable Long assists) {
    this.assists = assists;
    return this;
  }

  /**
   * Total assists the player had at the end of the match
   * @return assists
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ASSISTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getAssists() {
    return assists;
  }


  @JsonProperty(JSON_PROPERTY_ASSISTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAssists(@jakarta.annotation.Nullable Long assists) {
    this.assists = assists;
  }


  public PlayerRecentMatchesResponse skill(@jakarta.annotation.Nullable Long skill) {
    this.skill = JsonNullable.<Long>of(skill);
    return this;
  }

  /**
   * Skill bracket assigned by Valve (Normal, High, Very High). If the skill is unknown, will return null.
   * @return skill
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Long getSkill() {
        return skill.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_SKILL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Long> getSkill_JsonNullable() {
    return skill;
  }
  
  @JsonProperty(JSON_PROPERTY_SKILL)
  public void setSkill_JsonNullable(JsonNullable<Long> skill) {
    this.skill = skill;
  }

  public void setSkill(@jakarta.annotation.Nullable Long skill) {
    this.skill = JsonNullable.<Long>of(skill);
  }


  public PlayerRecentMatchesResponse averageRank(@jakarta.annotation.Nullable Long averageRank) {
    this.averageRank = JsonNullable.<Long>of(averageRank);
    return this;
  }

  /**
   * Average rank of players with public match data
   * @return averageRank
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Long getAverageRank() {
        return averageRank.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_AVERAGE_RANK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Long> getAverageRank_JsonNullable() {
    return averageRank;
  }
  
  @JsonProperty(JSON_PROPERTY_AVERAGE_RANK)
  public void setAverageRank_JsonNullable(JsonNullable<Long> averageRank) {
    this.averageRank = averageRank;
  }

  public void setAverageRank(@jakarta.annotation.Nullable Long averageRank) {
    this.averageRank = JsonNullable.<Long>of(averageRank);
  }


  public PlayerRecentMatchesResponse xpPerMin(@jakarta.annotation.Nullable Long xpPerMin) {
    this.xpPerMin = xpPerMin;
    return this;
  }

  /**
   * Experience Per Minute obtained by the player
   * @return xpPerMin
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_XP_PER_MIN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getXpPerMin() {
    return xpPerMin;
  }


  @JsonProperty(JSON_PROPERTY_XP_PER_MIN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setXpPerMin(@jakarta.annotation.Nullable Long xpPerMin) {
    this.xpPerMin = xpPerMin;
  }


  public PlayerRecentMatchesResponse goldPerMin(@jakarta.annotation.Nullable Long goldPerMin) {
    this.goldPerMin = goldPerMin;
    return this;
  }

  /**
   * Average gold per minute of the player
   * @return goldPerMin
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_GOLD_PER_MIN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getGoldPerMin() {
    return goldPerMin;
  }


  @JsonProperty(JSON_PROPERTY_GOLD_PER_MIN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setGoldPerMin(@jakarta.annotation.Nullable Long goldPerMin) {
    this.goldPerMin = goldPerMin;
  }


  public PlayerRecentMatchesResponse heroDamage(@jakarta.annotation.Nullable Long heroDamage) {
    this.heroDamage = heroDamage;
    return this;
  }

  /**
   * Total hero damage to enemy heroes
   * @return heroDamage
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_HERO_DAMAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getHeroDamage() {
    return heroDamage;
  }


  @JsonProperty(JSON_PROPERTY_HERO_DAMAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHeroDamage(@jakarta.annotation.Nullable Long heroDamage) {
    this.heroDamage = heroDamage;
  }


  public PlayerRecentMatchesResponse heroHealing(@jakarta.annotation.Nullable Long heroHealing) {
    this.heroHealing = heroHealing;
    return this;
  }

  /**
   * Total healing of ally heroes
   * @return heroHealing
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_HERO_HEALING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getHeroHealing() {
    return heroHealing;
  }


  @JsonProperty(JSON_PROPERTY_HERO_HEALING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHeroHealing(@jakarta.annotation.Nullable Long heroHealing) {
    this.heroHealing = heroHealing;
  }


  public PlayerRecentMatchesResponse lastHits(@jakarta.annotation.Nullable Long lastHits) {
    this.lastHits = lastHits;
    return this;
  }

  /**
   * Total last hits the player had at the end of the match
   * @return lastHits
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LAST_HITS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getLastHits() {
    return lastHits;
  }


  @JsonProperty(JSON_PROPERTY_LAST_HITS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLastHits(@jakarta.annotation.Nullable Long lastHits) {
    this.lastHits = lastHits;
  }


  public PlayerRecentMatchesResponse lane(@jakarta.annotation.Nullable Long lane) {
    this.lane = JsonNullable.<Long>of(lane);
    return this;
  }

  /**
   * Integer corresponding to which lane the player laned in for the match
   * @return lane
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Long getLane() {
        return lane.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_LANE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Long> getLane_JsonNullable() {
    return lane;
  }
  
  @JsonProperty(JSON_PROPERTY_LANE)
  public void setLane_JsonNullable(JsonNullable<Long> lane) {
    this.lane = lane;
  }

  public void setLane(@jakarta.annotation.Nullable Long lane) {
    this.lane = JsonNullable.<Long>of(lane);
  }


  public PlayerRecentMatchesResponse laneRole(@jakarta.annotation.Nullable Long laneRole) {
    this.laneRole = JsonNullable.<Long>of(laneRole);
    return this;
  }

  /**
   * lane_role
   * @return laneRole
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Long getLaneRole() {
        return laneRole.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_LANE_ROLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Long> getLaneRole_JsonNullable() {
    return laneRole;
  }
  
  @JsonProperty(JSON_PROPERTY_LANE_ROLE)
  public void setLaneRole_JsonNullable(JsonNullable<Long> laneRole) {
    this.laneRole = laneRole;
  }

  public void setLaneRole(@jakarta.annotation.Nullable Long laneRole) {
    this.laneRole = JsonNullable.<Long>of(laneRole);
  }


  public PlayerRecentMatchesResponse isRoaming(@jakarta.annotation.Nullable Boolean isRoaming) {
    this.isRoaming = JsonNullable.<Boolean>of(isRoaming);
    return this;
  }

  /**
   * Boolean describing whether or not the player roamed
   * @return isRoaming
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Boolean getIsRoaming() {
        return isRoaming.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_IS_ROAMING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Boolean> getIsRoaming_JsonNullable() {
    return isRoaming;
  }
  
  @JsonProperty(JSON_PROPERTY_IS_ROAMING)
  public void setIsRoaming_JsonNullable(JsonNullable<Boolean> isRoaming) {
    this.isRoaming = isRoaming;
  }

  public void setIsRoaming(@jakarta.annotation.Nullable Boolean isRoaming) {
    this.isRoaming = JsonNullable.<Boolean>of(isRoaming);
  }


  public PlayerRecentMatchesResponse cluster(@jakarta.annotation.Nullable Long cluster) {
    this.cluster = cluster;
    return this;
  }

  /**
   * cluster
   * @return cluster
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CLUSTER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getCluster() {
    return cluster;
  }


  @JsonProperty(JSON_PROPERTY_CLUSTER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCluster(@jakarta.annotation.Nullable Long cluster) {
    this.cluster = cluster;
  }


  public PlayerRecentMatchesResponse leaverStatus(@jakarta.annotation.Nullable Long leaverStatus) {
    this.leaverStatus = leaverStatus;
    return this;
  }

  /**
   * Integer describing whether or not the player left the game. 0: didn&#39;t leave. 1: left safely. 2+: Abandoned
   * @return leaverStatus
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LEAVER_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getLeaverStatus() {
    return leaverStatus;
  }


  @JsonProperty(JSON_PROPERTY_LEAVER_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLeaverStatus(@jakarta.annotation.Nullable Long leaverStatus) {
    this.leaverStatus = leaverStatus;
  }


  public PlayerRecentMatchesResponse partySize(@jakarta.annotation.Nullable Long partySize) {
    this.partySize = JsonNullable.<Long>of(partySize);
    return this;
  }

  /**
   * Size of the players party. If not in a party, will return 1.
   * @return partySize
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Long getPartySize() {
        return partySize.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_PARTY_SIZE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Long> getPartySize_JsonNullable() {
    return partySize;
  }
  
  @JsonProperty(JSON_PROPERTY_PARTY_SIZE)
  public void setPartySize_JsonNullable(JsonNullable<Long> partySize) {
    this.partySize = partySize;
  }

  public void setPartySize(@jakarta.annotation.Nullable Long partySize) {
    this.partySize = JsonNullable.<Long>of(partySize);
  }


  public PlayerRecentMatchesResponse heroVariant(@jakarta.annotation.Nullable Long heroVariant) {
    this.heroVariant = heroVariant;
    return this;
  }

  /**
   * 1-indexed facet, see https://github.com/odota/dotaconstants/blob/master/build/hero_abilities.json
   * @return heroVariant
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_HERO_VARIANT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getHeroVariant() {
    return heroVariant;
  }


  @JsonProperty(JSON_PROPERTY_HERO_VARIANT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHeroVariant(@jakarta.annotation.Nullable Long heroVariant) {
    this.heroVariant = heroVariant;
  }


  /**
   * Return true if this PlayerRecentMatchesResponse object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PlayerRecentMatchesResponse playerRecentMatchesResponse = (PlayerRecentMatchesResponse) o;
    return Objects.equals(this.matchId, playerRecentMatchesResponse.matchId) &&
        equalsNullable(this.playerSlot, playerRecentMatchesResponse.playerSlot) &&
        equalsNullable(this.radiantWin, playerRecentMatchesResponse.radiantWin) &&
        Objects.equals(this.duration, playerRecentMatchesResponse.duration) &&
        Objects.equals(this.gameMode, playerRecentMatchesResponse.gameMode) &&
        Objects.equals(this.lobbyType, playerRecentMatchesResponse.lobbyType) &&
        Objects.equals(this.heroId, playerRecentMatchesResponse.heroId) &&
        Objects.equals(this.startTime, playerRecentMatchesResponse.startTime) &&
        equalsNullable(this.version, playerRecentMatchesResponse.version) &&
        Objects.equals(this.kills, playerRecentMatchesResponse.kills) &&
        Objects.equals(this.deaths, playerRecentMatchesResponse.deaths) &&
        Objects.equals(this.assists, playerRecentMatchesResponse.assists) &&
        equalsNullable(this.skill, playerRecentMatchesResponse.skill) &&
        equalsNullable(this.averageRank, playerRecentMatchesResponse.averageRank) &&
        Objects.equals(this.xpPerMin, playerRecentMatchesResponse.xpPerMin) &&
        Objects.equals(this.goldPerMin, playerRecentMatchesResponse.goldPerMin) &&
        Objects.equals(this.heroDamage, playerRecentMatchesResponse.heroDamage) &&
        Objects.equals(this.heroHealing, playerRecentMatchesResponse.heroHealing) &&
        Objects.equals(this.lastHits, playerRecentMatchesResponse.lastHits) &&
        equalsNullable(this.lane, playerRecentMatchesResponse.lane) &&
        equalsNullable(this.laneRole, playerRecentMatchesResponse.laneRole) &&
        equalsNullable(this.isRoaming, playerRecentMatchesResponse.isRoaming) &&
        Objects.equals(this.cluster, playerRecentMatchesResponse.cluster) &&
        Objects.equals(this.leaverStatus, playerRecentMatchesResponse.leaverStatus) &&
        equalsNullable(this.partySize, playerRecentMatchesResponse.partySize) &&
        Objects.equals(this.heroVariant, playerRecentMatchesResponse.heroVariant);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(matchId, hashCodeNullable(playerSlot), hashCodeNullable(radiantWin), duration, gameMode, lobbyType, heroId, startTime, hashCodeNullable(version), kills, deaths, assists, hashCodeNullable(skill), hashCodeNullable(averageRank), xpPerMin, goldPerMin, heroDamage, heroHealing, lastHits, hashCodeNullable(lane), hashCodeNullable(laneRole), hashCodeNullable(isRoaming), cluster, leaverStatus, hashCodeNullable(partySize), heroVariant);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PlayerRecentMatchesResponse {\n");
    sb.append("    matchId: ").append(toIndentedString(matchId)).append("\n");
    sb.append("    playerSlot: ").append(toIndentedString(playerSlot)).append("\n");
    sb.append("    radiantWin: ").append(toIndentedString(radiantWin)).append("\n");
    sb.append("    duration: ").append(toIndentedString(duration)).append("\n");
    sb.append("    gameMode: ").append(toIndentedString(gameMode)).append("\n");
    sb.append("    lobbyType: ").append(toIndentedString(lobbyType)).append("\n");
    sb.append("    heroId: ").append(toIndentedString(heroId)).append("\n");
    sb.append("    startTime: ").append(toIndentedString(startTime)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    kills: ").append(toIndentedString(kills)).append("\n");
    sb.append("    deaths: ").append(toIndentedString(deaths)).append("\n");
    sb.append("    assists: ").append(toIndentedString(assists)).append("\n");
    sb.append("    skill: ").append(toIndentedString(skill)).append("\n");
    sb.append("    averageRank: ").append(toIndentedString(averageRank)).append("\n");
    sb.append("    xpPerMin: ").append(toIndentedString(xpPerMin)).append("\n");
    sb.append("    goldPerMin: ").append(toIndentedString(goldPerMin)).append("\n");
    sb.append("    heroDamage: ").append(toIndentedString(heroDamage)).append("\n");
    sb.append("    heroHealing: ").append(toIndentedString(heroHealing)).append("\n");
    sb.append("    lastHits: ").append(toIndentedString(lastHits)).append("\n");
    sb.append("    lane: ").append(toIndentedString(lane)).append("\n");
    sb.append("    laneRole: ").append(toIndentedString(laneRole)).append("\n");
    sb.append("    isRoaming: ").append(toIndentedString(isRoaming)).append("\n");
    sb.append("    cluster: ").append(toIndentedString(cluster)).append("\n");
    sb.append("    leaverStatus: ").append(toIndentedString(leaverStatus)).append("\n");
    sb.append("    partySize: ").append(toIndentedString(partySize)).append("\n");
    sb.append("    heroVariant: ").append(toIndentedString(heroVariant)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

