/*
 * OpenDota API
 * # Introduction The OpenDota API provides Dota 2 related data including advanced match data extracted from match replays.  You can find data that can be used to convert hero and ability IDs and other information provided by the API from the [dotaconstants](https://github.com/odota/dotaconstants) repository.  You can use the API without a key, but registering for a key allows increased rate limits and usage. Check out the [API page](https://www.opendota.com/api-keys) to learn more.     
 *
 * The version of the OpenAPI document: 31.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ako.dbuff.dotapi.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.ako.dbuff.dotapi.invoker.JSON;


/**
 * PlayerWinLossResponse
 */
@JsonPropertyOrder({
  PlayerWinLossResponse.JSON_PROPERTY_WIN,
  PlayerWinLossResponse.JSON_PROPERTY_LOSE
})
@com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class PlayerWinLossResponse {
  public static final String JSON_PROPERTY_WIN = "win";
  @jakarta.annotation.Nullable
  private Long win;

  public static final String JSON_PROPERTY_LOSE = "lose";
  @jakarta.annotation.Nullable
  private Long lose;

  public PlayerWinLossResponse() { 
  }

  public PlayerWinLossResponse win(@jakarta.annotation.Nullable Long win) {
    this.win = win;
    return this;
  }

  /**
   * Number of wins
   * @return win
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_WIN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getWin() {
    return win;
  }


  @JsonProperty(JSON_PROPERTY_WIN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setWin(@jakarta.annotation.Nullable Long win) {
    this.win = win;
  }


  public PlayerWinLossResponse lose(@jakarta.annotation.Nullable Long lose) {
    this.lose = lose;
    return this;
  }

  /**
   * Number of loses
   * @return lose
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LOSE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getLose() {
    return lose;
  }


  @JsonProperty(JSON_PROPERTY_LOSE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLose(@jakarta.annotation.Nullable Long lose) {
    this.lose = lose;
  }


  /**
   * Return true if this PlayerWinLossResponse object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PlayerWinLossResponse playerWinLossResponse = (PlayerWinLossResponse) o;
    return Objects.equals(this.win, playerWinLossResponse.win) &&
        Objects.equals(this.lose, playerWinLossResponse.lose);
  }

  @Override
  public int hashCode() {
    return Objects.hash(win, lose);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PlayerWinLossResponse {\n");
    sb.append("    win: ").append(toIndentedString(win)).append("\n");
    sb.append("    lose: ").append(toIndentedString(lose)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

