/*
 * OpenDota API
 * # Introduction The OpenDota API provides Dota 2 related data including advanced match data extracted from match replays.  You can find data that can be used to convert hero and ability IDs and other information provided by the API from the [dotaconstants](https://github.com/odota/dotaconstants) repository.  Without a key, you can make 2,000 free calls per day at a rate limit of 60 requests/minute. We also offer a Premium Tier with unlimited API calls and higher rate limits. Check out the [API page](https://www.opendota.com/api-keys) to learn more.     
 *
 * The version of the OpenAPI document: 26.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ako.dbuff.dotapi.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.ako.dbuff.dotapi.invoker.JSON;


/**
 * PlayerObjectResponse
 */
@JsonPropertyOrder({
  PlayerObjectResponse.JSON_PROPERTY_ACCOUNT_ID,
  PlayerObjectResponse.JSON_PROPERTY_STEAMID,
  PlayerObjectResponse.JSON_PROPERTY_AVATAR,
  PlayerObjectResponse.JSON_PROPERTY_AVATARMEDIUM,
  PlayerObjectResponse.JSON_PROPERTY_AVATARFULL,
  PlayerObjectResponse.JSON_PROPERTY_PROFILEURL,
  PlayerObjectResponse.JSON_PROPERTY_PERSONANAME,
  PlayerObjectResponse.JSON_PROPERTY_LAST_LOGIN,
  PlayerObjectResponse.JSON_PROPERTY_FULL_HISTORY_TIME,
  PlayerObjectResponse.JSON_PROPERTY_CHEESE,
  PlayerObjectResponse.JSON_PROPERTY_FH_UNAVAILABLE,
  PlayerObjectResponse.JSON_PROPERTY_LOCCOUNTRYCODE,
  PlayerObjectResponse.JSON_PROPERTY_NAME,
  PlayerObjectResponse.JSON_PROPERTY_COUNTRY_CODE,
  PlayerObjectResponse.JSON_PROPERTY_FANTASY_ROLE,
  PlayerObjectResponse.JSON_PROPERTY_TEAM_ID,
  PlayerObjectResponse.JSON_PROPERTY_TEAM_NAME,
  PlayerObjectResponse.JSON_PROPERTY_TEAM_TAG,
  PlayerObjectResponse.JSON_PROPERTY_IS_LOCKED,
  PlayerObjectResponse.JSON_PROPERTY_IS_PRO,
  PlayerObjectResponse.JSON_PROPERTY_LOCKED_UNTIL
})
@com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class PlayerObjectResponse {
  public static final String JSON_PROPERTY_ACCOUNT_ID = "account_id";
  @jakarta.annotation.Nullable
  private Long accountId;

  public static final String JSON_PROPERTY_STEAMID = "steamid";
  @jakarta.annotation.Nullable
  private String steamid;

  public static final String JSON_PROPERTY_AVATAR = "avatar";
  @jakarta.annotation.Nullable
  private String avatar;

  public static final String JSON_PROPERTY_AVATARMEDIUM = "avatarmedium";
  @jakarta.annotation.Nullable
  private String avatarmedium;

  public static final String JSON_PROPERTY_AVATARFULL = "avatarfull";
  @jakarta.annotation.Nullable
  private String avatarfull;

  public static final String JSON_PROPERTY_PROFILEURL = "profileurl";
  @jakarta.annotation.Nullable
  private String profileurl;

  public static final String JSON_PROPERTY_PERSONANAME = "personaname";
  private JsonNullable<String> personaname = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_LAST_LOGIN = "last_login";
  @jakarta.annotation.Nullable
  private OffsetDateTime lastLogin;

  public static final String JSON_PROPERTY_FULL_HISTORY_TIME = "full_history_time";
  @jakarta.annotation.Nullable
  private OffsetDateTime fullHistoryTime;

  public static final String JSON_PROPERTY_CHEESE = "cheese";
  @jakarta.annotation.Nullable
  private Long cheese;

  public static final String JSON_PROPERTY_FH_UNAVAILABLE = "fh_unavailable";
  @jakarta.annotation.Nullable
  private Boolean fhUnavailable;

  public static final String JSON_PROPERTY_LOCCOUNTRYCODE = "loccountrycode";
  @jakarta.annotation.Nullable
  private String loccountrycode;

  public static final String JSON_PROPERTY_NAME = "name";
  @jakarta.annotation.Nullable
  private String name;

  public static final String JSON_PROPERTY_COUNTRY_CODE = "country_code";
  @jakarta.annotation.Nullable
  private String countryCode;

  public static final String JSON_PROPERTY_FANTASY_ROLE = "fantasy_role";
  @jakarta.annotation.Nullable
  private Long fantasyRole;

  public static final String JSON_PROPERTY_TEAM_ID = "team_id";
  @jakarta.annotation.Nullable
  private Long teamId;

  public static final String JSON_PROPERTY_TEAM_NAME = "team_name";
  private JsonNullable<String> teamName = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_TEAM_TAG = "team_tag";
  @jakarta.annotation.Nullable
  private String teamTag;

  public static final String JSON_PROPERTY_IS_LOCKED = "is_locked";
  @jakarta.annotation.Nullable
  private Boolean isLocked;

  public static final String JSON_PROPERTY_IS_PRO = "is_pro";
  @jakarta.annotation.Nullable
  private Boolean isPro;

  public static final String JSON_PROPERTY_LOCKED_UNTIL = "locked_until";
  @jakarta.annotation.Nullable
  private Long lockedUntil;

  public PlayerObjectResponse() { 
  }

  public PlayerObjectResponse accountId(@jakarta.annotation.Nullable Long accountId) {
    this.accountId = accountId;
    return this;
  }

  /**
   * The player account ID
   * @return accountId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ACCOUNT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getAccountId() {
    return accountId;
  }


  @JsonProperty(JSON_PROPERTY_ACCOUNT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAccountId(@jakarta.annotation.Nullable Long accountId) {
    this.accountId = accountId;
  }


  public PlayerObjectResponse steamid(@jakarta.annotation.Nullable String steamid) {
    this.steamid = steamid;
    return this;
  }

  /**
   * Player&#39;s steam identifier
   * @return steamid
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STEAMID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSteamid() {
    return steamid;
  }


  @JsonProperty(JSON_PROPERTY_STEAMID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSteamid(@jakarta.annotation.Nullable String steamid) {
    this.steamid = steamid;
  }


  public PlayerObjectResponse avatar(@jakarta.annotation.Nullable String avatar) {
    this.avatar = avatar;
    return this;
  }

  /**
   * Steam picture URL (small picture)
   * @return avatar
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_AVATAR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAvatar() {
    return avatar;
  }


  @JsonProperty(JSON_PROPERTY_AVATAR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAvatar(@jakarta.annotation.Nullable String avatar) {
    this.avatar = avatar;
  }


  public PlayerObjectResponse avatarmedium(@jakarta.annotation.Nullable String avatarmedium) {
    this.avatarmedium = avatarmedium;
    return this;
  }

  /**
   * Steam picture URL (medium picture)
   * @return avatarmedium
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_AVATARMEDIUM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAvatarmedium() {
    return avatarmedium;
  }


  @JsonProperty(JSON_PROPERTY_AVATARMEDIUM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAvatarmedium(@jakarta.annotation.Nullable String avatarmedium) {
    this.avatarmedium = avatarmedium;
  }


  public PlayerObjectResponse avatarfull(@jakarta.annotation.Nullable String avatarfull) {
    this.avatarfull = avatarfull;
    return this;
  }

  /**
   * Steam picture URL (full picture)
   * @return avatarfull
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_AVATARFULL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAvatarfull() {
    return avatarfull;
  }


  @JsonProperty(JSON_PROPERTY_AVATARFULL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAvatarfull(@jakarta.annotation.Nullable String avatarfull) {
    this.avatarfull = avatarfull;
  }


  public PlayerObjectResponse profileurl(@jakarta.annotation.Nullable String profileurl) {
    this.profileurl = profileurl;
    return this;
  }

  /**
   * Steam profile URL
   * @return profileurl
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PROFILEURL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getProfileurl() {
    return profileurl;
  }


  @JsonProperty(JSON_PROPERTY_PROFILEURL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProfileurl(@jakarta.annotation.Nullable String profileurl) {
    this.profileurl = profileurl;
  }


  public PlayerObjectResponse personaname(@jakarta.annotation.Nullable String personaname) {
    this.personaname = JsonNullable.<String>of(personaname);
    return this;
  }

  /**
   * Player&#39;s Steam name
   * @return personaname
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getPersonaname() {
        return personaname.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_PERSONANAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getPersonaname_JsonNullable() {
    return personaname;
  }
  
  @JsonProperty(JSON_PROPERTY_PERSONANAME)
  public void setPersonaname_JsonNullable(JsonNullable<String> personaname) {
    this.personaname = personaname;
  }

  public void setPersonaname(@jakarta.annotation.Nullable String personaname) {
    this.personaname = JsonNullable.<String>of(personaname);
  }


  public PlayerObjectResponse lastLogin(@jakarta.annotation.Nullable OffsetDateTime lastLogin) {
    this.lastLogin = lastLogin;
    return this;
  }

  /**
   * Date and time of last login to OpenDota
   * @return lastLogin
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LAST_LOGIN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getLastLogin() {
    return lastLogin;
  }


  @JsonProperty(JSON_PROPERTY_LAST_LOGIN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLastLogin(@jakarta.annotation.Nullable OffsetDateTime lastLogin) {
    this.lastLogin = lastLogin;
  }


  public PlayerObjectResponse fullHistoryTime(@jakarta.annotation.Nullable OffsetDateTime fullHistoryTime) {
    this.fullHistoryTime = fullHistoryTime;
    return this;
  }

  /**
   * Date and time of last request to refresh player&#39;s match history
   * @return fullHistoryTime
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FULL_HISTORY_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getFullHistoryTime() {
    return fullHistoryTime;
  }


  @JsonProperty(JSON_PROPERTY_FULL_HISTORY_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFullHistoryTime(@jakarta.annotation.Nullable OffsetDateTime fullHistoryTime) {
    this.fullHistoryTime = fullHistoryTime;
  }


  public PlayerObjectResponse cheese(@jakarta.annotation.Nullable Long cheese) {
    this.cheese = cheese;
    return this;
  }

  /**
   * Amount of dollars the player has donated to OpenDota
   * @return cheese
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CHEESE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getCheese() {
    return cheese;
  }


  @JsonProperty(JSON_PROPERTY_CHEESE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCheese(@jakarta.annotation.Nullable Long cheese) {
    this.cheese = cheese;
  }


  public PlayerObjectResponse fhUnavailable(@jakarta.annotation.Nullable Boolean fhUnavailable) {
    this.fhUnavailable = fhUnavailable;
    return this;
  }

  /**
   * Whether the refresh of player&#39; match history failed
   * @return fhUnavailable
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FH_UNAVAILABLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getFhUnavailable() {
    return fhUnavailable;
  }


  @JsonProperty(JSON_PROPERTY_FH_UNAVAILABLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFhUnavailable(@jakarta.annotation.Nullable Boolean fhUnavailable) {
    this.fhUnavailable = fhUnavailable;
  }


  public PlayerObjectResponse loccountrycode(@jakarta.annotation.Nullable String loccountrycode) {
    this.loccountrycode = loccountrycode;
    return this;
  }

  /**
   * Player&#39;s country identifier, e.g. US
   * @return loccountrycode
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LOCCOUNTRYCODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLoccountrycode() {
    return loccountrycode;
  }


  @JsonProperty(JSON_PROPERTY_LOCCOUNTRYCODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLoccountrycode(@jakarta.annotation.Nullable String loccountrycode) {
    this.loccountrycode = loccountrycode;
  }


  public PlayerObjectResponse name(@jakarta.annotation.Nullable String name) {
    this.name = name;
    return this;
  }

  /**
   * Verified player name, e.g. &#39;Miracle-&#39;
   * @return name
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(@jakarta.annotation.Nullable String name) {
    this.name = name;
  }


  public PlayerObjectResponse countryCode(@jakarta.annotation.Nullable String countryCode) {
    this.countryCode = countryCode;
    return this;
  }

  /**
   * Player&#39;s country code
   * @return countryCode
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_COUNTRY_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCountryCode() {
    return countryCode;
  }


  @JsonProperty(JSON_PROPERTY_COUNTRY_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCountryCode(@jakarta.annotation.Nullable String countryCode) {
    this.countryCode = countryCode;
  }


  public PlayerObjectResponse fantasyRole(@jakarta.annotation.Nullable Long fantasyRole) {
    this.fantasyRole = fantasyRole;
    return this;
  }

  /**
   * Player&#39;s ingame role (core: 1 or support: 2)
   * @return fantasyRole
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FANTASY_ROLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getFantasyRole() {
    return fantasyRole;
  }


  @JsonProperty(JSON_PROPERTY_FANTASY_ROLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFantasyRole(@jakarta.annotation.Nullable Long fantasyRole) {
    this.fantasyRole = fantasyRole;
  }


  public PlayerObjectResponse teamId(@jakarta.annotation.Nullable Long teamId) {
    this.teamId = teamId;
    return this;
  }

  /**
   * Player&#39;s team identifier
   * @return teamId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TEAM_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getTeamId() {
    return teamId;
  }


  @JsonProperty(JSON_PROPERTY_TEAM_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTeamId(@jakarta.annotation.Nullable Long teamId) {
    this.teamId = teamId;
  }


  public PlayerObjectResponse teamName(@jakarta.annotation.Nullable String teamName) {
    this.teamName = JsonNullable.<String>of(teamName);
    return this;
  }

  /**
   * Team name
   * @return teamName
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getTeamName() {
        return teamName.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_TEAM_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getTeamName_JsonNullable() {
    return teamName;
  }
  
  @JsonProperty(JSON_PROPERTY_TEAM_NAME)
  public void setTeamName_JsonNullable(JsonNullable<String> teamName) {
    this.teamName = teamName;
  }

  public void setTeamName(@jakarta.annotation.Nullable String teamName) {
    this.teamName = JsonNullable.<String>of(teamName);
  }


  public PlayerObjectResponse teamTag(@jakarta.annotation.Nullable String teamTag) {
    this.teamTag = teamTag;
    return this;
  }

  /**
   * Player&#39;s team shorthand tag, e.g. &#39;EG&#39;
   * @return teamTag
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TEAM_TAG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTeamTag() {
    return teamTag;
  }


  @JsonProperty(JSON_PROPERTY_TEAM_TAG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTeamTag(@jakarta.annotation.Nullable String teamTag) {
    this.teamTag = teamTag;
  }


  public PlayerObjectResponse isLocked(@jakarta.annotation.Nullable Boolean isLocked) {
    this.isLocked = isLocked;
    return this;
  }

  /**
   * Whether the roster lock is active
   * @return isLocked
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_IS_LOCKED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getIsLocked() {
    return isLocked;
  }


  @JsonProperty(JSON_PROPERTY_IS_LOCKED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIsLocked(@jakarta.annotation.Nullable Boolean isLocked) {
    this.isLocked = isLocked;
  }


  public PlayerObjectResponse isPro(@jakarta.annotation.Nullable Boolean isPro) {
    this.isPro = isPro;
    return this;
  }

  /**
   * Whether the player is professional or not
   * @return isPro
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_IS_PRO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getIsPro() {
    return isPro;
  }


  @JsonProperty(JSON_PROPERTY_IS_PRO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIsPro(@jakarta.annotation.Nullable Boolean isPro) {
    this.isPro = isPro;
  }


  public PlayerObjectResponse lockedUntil(@jakarta.annotation.Nullable Long lockedUntil) {
    this.lockedUntil = lockedUntil;
    return this;
  }

  /**
   * When the roster lock will end
   * @return lockedUntil
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LOCKED_UNTIL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getLockedUntil() {
    return lockedUntil;
  }


  @JsonProperty(JSON_PROPERTY_LOCKED_UNTIL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLockedUntil(@jakarta.annotation.Nullable Long lockedUntil) {
    this.lockedUntil = lockedUntil;
  }


  /**
   * Return true if this PlayerObjectResponse object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PlayerObjectResponse playerObjectResponse = (PlayerObjectResponse) o;
    return Objects.equals(this.accountId, playerObjectResponse.accountId) &&
        Objects.equals(this.steamid, playerObjectResponse.steamid) &&
        Objects.equals(this.avatar, playerObjectResponse.avatar) &&
        Objects.equals(this.avatarmedium, playerObjectResponse.avatarmedium) &&
        Objects.equals(this.avatarfull, playerObjectResponse.avatarfull) &&
        Objects.equals(this.profileurl, playerObjectResponse.profileurl) &&
        equalsNullable(this.personaname, playerObjectResponse.personaname) &&
        Objects.equals(this.lastLogin, playerObjectResponse.lastLogin) &&
        Objects.equals(this.fullHistoryTime, playerObjectResponse.fullHistoryTime) &&
        Objects.equals(this.cheese, playerObjectResponse.cheese) &&
        Objects.equals(this.fhUnavailable, playerObjectResponse.fhUnavailable) &&
        Objects.equals(this.loccountrycode, playerObjectResponse.loccountrycode) &&
        Objects.equals(this.name, playerObjectResponse.name) &&
        Objects.equals(this.countryCode, playerObjectResponse.countryCode) &&
        Objects.equals(this.fantasyRole, playerObjectResponse.fantasyRole) &&
        Objects.equals(this.teamId, playerObjectResponse.teamId) &&
        equalsNullable(this.teamName, playerObjectResponse.teamName) &&
        Objects.equals(this.teamTag, playerObjectResponse.teamTag) &&
        Objects.equals(this.isLocked, playerObjectResponse.isLocked) &&
        Objects.equals(this.isPro, playerObjectResponse.isPro) &&
        Objects.equals(this.lockedUntil, playerObjectResponse.lockedUntil);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(accountId, steamid, avatar, avatarmedium, avatarfull, profileurl, hashCodeNullable(personaname), lastLogin, fullHistoryTime, cheese, fhUnavailable, loccountrycode, name, countryCode, fantasyRole, teamId, hashCodeNullable(teamName), teamTag, isLocked, isPro, lockedUntil);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PlayerObjectResponse {\n");
    sb.append("    accountId: ").append(toIndentedString(accountId)).append("\n");
    sb.append("    steamid: ").append(toIndentedString(steamid)).append("\n");
    sb.append("    avatar: ").append(toIndentedString(avatar)).append("\n");
    sb.append("    avatarmedium: ").append(toIndentedString(avatarmedium)).append("\n");
    sb.append("    avatarfull: ").append(toIndentedString(avatarfull)).append("\n");
    sb.append("    profileurl: ").append(toIndentedString(profileurl)).append("\n");
    sb.append("    personaname: ").append(toIndentedString(personaname)).append("\n");
    sb.append("    lastLogin: ").append(toIndentedString(lastLogin)).append("\n");
    sb.append("    fullHistoryTime: ").append(toIndentedString(fullHistoryTime)).append("\n");
    sb.append("    cheese: ").append(toIndentedString(cheese)).append("\n");
    sb.append("    fhUnavailable: ").append(toIndentedString(fhUnavailable)).append("\n");
    sb.append("    loccountrycode: ").append(toIndentedString(loccountrycode)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    countryCode: ").append(toIndentedString(countryCode)).append("\n");
    sb.append("    fantasyRole: ").append(toIndentedString(fantasyRole)).append("\n");
    sb.append("    teamId: ").append(toIndentedString(teamId)).append("\n");
    sb.append("    teamName: ").append(toIndentedString(teamName)).append("\n");
    sb.append("    teamTag: ").append(toIndentedString(teamTag)).append("\n");
    sb.append("    isLocked: ").append(toIndentedString(isLocked)).append("\n");
    sb.append("    isPro: ").append(toIndentedString(isPro)).append("\n");
    sb.append("    lockedUntil: ").append(toIndentedString(lockedUntil)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

