/*
 * OpenDota API
 * # Introduction The OpenDota API provides Dota 2 related data including advanced match data extracted from match replays.  You can find data that can be used to convert hero and ability IDs and other information provided by the API from the [dotaconstants](https://github.com/odota/dotaconstants) repository.  Without a key, you can make 2,000 free calls per day at a rate limit of 60 requests/minute. We also offer a Premium Tier with unlimited API calls and higher rate limits. Check out the [API page](https://www.opendota.com/api-keys) to learn more.     
 *
 * The version of the OpenAPI document: 26.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ako.dbuff.dotapi.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.ako.dbuff.dotapi.invoker.JSON;


/**
 * PlayerWordCloudResponse
 */
@JsonPropertyOrder({
  PlayerWordCloudResponse.JSON_PROPERTY_MY_WORD_COUNTS,
  PlayerWordCloudResponse.JSON_PROPERTY_ALL_WORD_COUNTS
})
@com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class PlayerWordCloudResponse {
  public static final String JSON_PROPERTY_MY_WORD_COUNTS = "my_word_counts";
  @jakarta.annotation.Nullable
  private Object myWordCounts;

  public static final String JSON_PROPERTY_ALL_WORD_COUNTS = "all_word_counts";
  @jakarta.annotation.Nullable
  private Object allWordCounts;

  public PlayerWordCloudResponse() { 
  }

  public PlayerWordCloudResponse myWordCounts(@jakarta.annotation.Nullable Object myWordCounts) {
    this.myWordCounts = myWordCounts;
    return this;
  }

  /**
   * my_word_counts
   * @return myWordCounts
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MY_WORD_COUNTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Object getMyWordCounts() {
    return myWordCounts;
  }


  @JsonProperty(JSON_PROPERTY_MY_WORD_COUNTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMyWordCounts(@jakarta.annotation.Nullable Object myWordCounts) {
    this.myWordCounts = myWordCounts;
  }


  public PlayerWordCloudResponse allWordCounts(@jakarta.annotation.Nullable Object allWordCounts) {
    this.allWordCounts = allWordCounts;
    return this;
  }

  /**
   * all_word_counts
   * @return allWordCounts
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ALL_WORD_COUNTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Object getAllWordCounts() {
    return allWordCounts;
  }


  @JsonProperty(JSON_PROPERTY_ALL_WORD_COUNTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAllWordCounts(@jakarta.annotation.Nullable Object allWordCounts) {
    this.allWordCounts = allWordCounts;
  }


  /**
   * Return true if this PlayerWordCloudResponse object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PlayerWordCloudResponse playerWordCloudResponse = (PlayerWordCloudResponse) o;
    return Objects.equals(this.myWordCounts, playerWordCloudResponse.myWordCounts) &&
        Objects.equals(this.allWordCounts, playerWordCloudResponse.allWordCounts);
  }

  @Override
  public int hashCode() {
    return Objects.hash(myWordCounts, allWordCounts);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PlayerWordCloudResponse {\n");
    sb.append("    myWordCounts: ").append(toIndentedString(myWordCounts)).append("\n");
    sb.append("    allWordCounts: ").append(toIndentedString(allWordCounts)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

