/*
 * OpenDota API
 * # Introduction The OpenDota API provides Dota 2 related data including advanced match data extracted from match replays.  You can find data that can be used to convert hero and ability IDs and other information provided by the API from the [dotaconstants](https://github.com/odota/dotaconstants) repository.  Without a key, you can make 2,000 free calls per day at a rate limit of 60 requests/minute. We also offer a Premium Tier with unlimited API calls and higher rate limits. Check out the [API page](https://www.opendota.com/api-keys) to learn more.     
 *
 * The version of the OpenAPI document: 26.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ako.dbuff.dotapi.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.ako.dbuff.dotapi.invoker.JSON;


/**
 * PlayerProsResponse
 */
@JsonPropertyOrder({
  PlayerProsResponse.JSON_PROPERTY_ACCOUNT_ID,
  PlayerProsResponse.JSON_PROPERTY_NAME,
  PlayerProsResponse.JSON_PROPERTY_COUNTRY_CODE,
  PlayerProsResponse.JSON_PROPERTY_FANTASY_ROLE,
  PlayerProsResponse.JSON_PROPERTY_TEAM_ID,
  PlayerProsResponse.JSON_PROPERTY_TEAM_NAME,
  PlayerProsResponse.JSON_PROPERTY_TEAM_TAG,
  PlayerProsResponse.JSON_PROPERTY_IS_LOCKED,
  PlayerProsResponse.JSON_PROPERTY_IS_PRO,
  PlayerProsResponse.JSON_PROPERTY_LOCKED_UNTIL,
  PlayerProsResponse.JSON_PROPERTY_STEAMID,
  PlayerProsResponse.JSON_PROPERTY_AVATAR,
  PlayerProsResponse.JSON_PROPERTY_AVATARMEDIUM,
  PlayerProsResponse.JSON_PROPERTY_AVATARFULL,
  PlayerProsResponse.JSON_PROPERTY_PROFILEURL,
  PlayerProsResponse.JSON_PROPERTY_LAST_LOGIN,
  PlayerProsResponse.JSON_PROPERTY_FULL_HISTORY_TIME,
  PlayerProsResponse.JSON_PROPERTY_CHEESE,
  PlayerProsResponse.JSON_PROPERTY_FH_UNAVAILABLE,
  PlayerProsResponse.JSON_PROPERTY_LOCCOUNTRYCODE,
  PlayerProsResponse.JSON_PROPERTY_LAST_PLAYED,
  PlayerProsResponse.JSON_PROPERTY_WIN,
  PlayerProsResponse.JSON_PROPERTY_GAMES,
  PlayerProsResponse.JSON_PROPERTY_WITH_WIN,
  PlayerProsResponse.JSON_PROPERTY_WITH_GAMES,
  PlayerProsResponse.JSON_PROPERTY_AGAINST_WIN,
  PlayerProsResponse.JSON_PROPERTY_AGAINST_GAMES,
  PlayerProsResponse.JSON_PROPERTY_WITH_GPM_SUM,
  PlayerProsResponse.JSON_PROPERTY_WITH_XPM_SUM
})
@com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class PlayerProsResponse {
  public static final String JSON_PROPERTY_ACCOUNT_ID = "account_id";
  @jakarta.annotation.Nullable
  private Long accountId;

  public static final String JSON_PROPERTY_NAME = "name";
  private JsonNullable<String> name = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_COUNTRY_CODE = "country_code";
  @jakarta.annotation.Nullable
  private String countryCode;

  public static final String JSON_PROPERTY_FANTASY_ROLE = "fantasy_role";
  @jakarta.annotation.Nullable
  private Long fantasyRole;

  public static final String JSON_PROPERTY_TEAM_ID = "team_id";
  @jakarta.annotation.Nullable
  private Long teamId;

  public static final String JSON_PROPERTY_TEAM_NAME = "team_name";
  private JsonNullable<String> teamName = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_TEAM_TAG = "team_tag";
  private JsonNullable<String> teamTag = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_IS_LOCKED = "is_locked";
  @jakarta.annotation.Nullable
  private Boolean isLocked;

  public static final String JSON_PROPERTY_IS_PRO = "is_pro";
  @jakarta.annotation.Nullable
  private Boolean isPro;

  public static final String JSON_PROPERTY_LOCKED_UNTIL = "locked_until";
  private JsonNullable<Long> lockedUntil = JsonNullable.<Long>undefined();

  public static final String JSON_PROPERTY_STEAMID = "steamid";
  private JsonNullable<String> steamid = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_AVATAR = "avatar";
  private JsonNullable<String> avatar = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_AVATARMEDIUM = "avatarmedium";
  private JsonNullable<String> avatarmedium = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_AVATARFULL = "avatarfull";
  private JsonNullable<String> avatarfull = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_PROFILEURL = "profileurl";
  private JsonNullable<String> profileurl = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_LAST_LOGIN = "last_login";
  private JsonNullable<OffsetDateTime> lastLogin = JsonNullable.<OffsetDateTime>undefined();

  public static final String JSON_PROPERTY_FULL_HISTORY_TIME = "full_history_time";
  private JsonNullable<OffsetDateTime> fullHistoryTime = JsonNullable.<OffsetDateTime>undefined();

  public static final String JSON_PROPERTY_CHEESE = "cheese";
  private JsonNullable<Long> cheese = JsonNullable.<Long>undefined();

  public static final String JSON_PROPERTY_FH_UNAVAILABLE = "fh_unavailable";
  private JsonNullable<Boolean> fhUnavailable = JsonNullable.<Boolean>undefined();

  public static final String JSON_PROPERTY_LOCCOUNTRYCODE = "loccountrycode";
  private JsonNullable<String> loccountrycode = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_LAST_PLAYED = "last_played";
  private JsonNullable<Long> lastPlayed = JsonNullable.<Long>undefined();

  public static final String JSON_PROPERTY_WIN = "win";
  @jakarta.annotation.Nullable
  private Long win;

  public static final String JSON_PROPERTY_GAMES = "games";
  @jakarta.annotation.Nullable
  private Long games;

  public static final String JSON_PROPERTY_WITH_WIN = "with_win";
  @jakarta.annotation.Nullable
  private Long withWin;

  public static final String JSON_PROPERTY_WITH_GAMES = "with_games";
  @jakarta.annotation.Nullable
  private Long withGames;

  public static final String JSON_PROPERTY_AGAINST_WIN = "against_win";
  @jakarta.annotation.Nullable
  private Long againstWin;

  public static final String JSON_PROPERTY_AGAINST_GAMES = "against_games";
  @jakarta.annotation.Nullable
  private Long againstGames;

  public static final String JSON_PROPERTY_WITH_GPM_SUM = "with_gpm_sum";
  private JsonNullable<Long> withGpmSum = JsonNullable.<Long>undefined();

  public static final String JSON_PROPERTY_WITH_XPM_SUM = "with_xpm_sum";
  private JsonNullable<Long> withXpmSum = JsonNullable.<Long>undefined();

  public PlayerProsResponse() { 
  }

  public PlayerProsResponse accountId(@jakarta.annotation.Nullable Long accountId) {
    this.accountId = accountId;
    return this;
  }

  /**
   * The player account ID
   * @return accountId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ACCOUNT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getAccountId() {
    return accountId;
  }


  @JsonProperty(JSON_PROPERTY_ACCOUNT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAccountId(@jakarta.annotation.Nullable Long accountId) {
    this.accountId = accountId;
  }


  public PlayerProsResponse name(@jakarta.annotation.Nullable String name) {
    this.name = JsonNullable.<String>of(name);
    return this;
  }

  /**
   * name
   * @return name
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getName() {
        return name.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getName_JsonNullable() {
    return name;
  }
  
  @JsonProperty(JSON_PROPERTY_NAME)
  public void setName_JsonNullable(JsonNullable<String> name) {
    this.name = name;
  }

  public void setName(@jakarta.annotation.Nullable String name) {
    this.name = JsonNullable.<String>of(name);
  }


  public PlayerProsResponse countryCode(@jakarta.annotation.Nullable String countryCode) {
    this.countryCode = countryCode;
    return this;
  }

  /**
   * country_code
   * @return countryCode
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_COUNTRY_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCountryCode() {
    return countryCode;
  }


  @JsonProperty(JSON_PROPERTY_COUNTRY_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCountryCode(@jakarta.annotation.Nullable String countryCode) {
    this.countryCode = countryCode;
  }


  public PlayerProsResponse fantasyRole(@jakarta.annotation.Nullable Long fantasyRole) {
    this.fantasyRole = fantasyRole;
    return this;
  }

  /**
   * fantasy_role
   * @return fantasyRole
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FANTASY_ROLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getFantasyRole() {
    return fantasyRole;
  }


  @JsonProperty(JSON_PROPERTY_FANTASY_ROLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFantasyRole(@jakarta.annotation.Nullable Long fantasyRole) {
    this.fantasyRole = fantasyRole;
  }


  public PlayerProsResponse teamId(@jakarta.annotation.Nullable Long teamId) {
    this.teamId = teamId;
    return this;
  }

  /**
   * team_id
   * @return teamId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TEAM_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getTeamId() {
    return teamId;
  }


  @JsonProperty(JSON_PROPERTY_TEAM_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTeamId(@jakarta.annotation.Nullable Long teamId) {
    this.teamId = teamId;
  }


  public PlayerProsResponse teamName(@jakarta.annotation.Nullable String teamName) {
    this.teamName = JsonNullable.<String>of(teamName);
    return this;
  }

  /**
   * Team name
   * @return teamName
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getTeamName() {
        return teamName.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_TEAM_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getTeamName_JsonNullable() {
    return teamName;
  }
  
  @JsonProperty(JSON_PROPERTY_TEAM_NAME)
  public void setTeamName_JsonNullable(JsonNullable<String> teamName) {
    this.teamName = teamName;
  }

  public void setTeamName(@jakarta.annotation.Nullable String teamName) {
    this.teamName = JsonNullable.<String>of(teamName);
  }


  public PlayerProsResponse teamTag(@jakarta.annotation.Nullable String teamTag) {
    this.teamTag = JsonNullable.<String>of(teamTag);
    return this;
  }

  /**
   * team_tag
   * @return teamTag
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getTeamTag() {
        return teamTag.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_TEAM_TAG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getTeamTag_JsonNullable() {
    return teamTag;
  }
  
  @JsonProperty(JSON_PROPERTY_TEAM_TAG)
  public void setTeamTag_JsonNullable(JsonNullable<String> teamTag) {
    this.teamTag = teamTag;
  }

  public void setTeamTag(@jakarta.annotation.Nullable String teamTag) {
    this.teamTag = JsonNullable.<String>of(teamTag);
  }


  public PlayerProsResponse isLocked(@jakarta.annotation.Nullable Boolean isLocked) {
    this.isLocked = isLocked;
    return this;
  }

  /**
   * is_locked
   * @return isLocked
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_IS_LOCKED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getIsLocked() {
    return isLocked;
  }


  @JsonProperty(JSON_PROPERTY_IS_LOCKED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIsLocked(@jakarta.annotation.Nullable Boolean isLocked) {
    this.isLocked = isLocked;
  }


  public PlayerProsResponse isPro(@jakarta.annotation.Nullable Boolean isPro) {
    this.isPro = isPro;
    return this;
  }

  /**
   * is_pro
   * @return isPro
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_IS_PRO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getIsPro() {
    return isPro;
  }


  @JsonProperty(JSON_PROPERTY_IS_PRO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIsPro(@jakarta.annotation.Nullable Boolean isPro) {
    this.isPro = isPro;
  }


  public PlayerProsResponse lockedUntil(@jakarta.annotation.Nullable Long lockedUntil) {
    this.lockedUntil = JsonNullable.<Long>of(lockedUntil);
    return this;
  }

  /**
   * locked_until
   * @return lockedUntil
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Long getLockedUntil() {
        return lockedUntil.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_LOCKED_UNTIL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Long> getLockedUntil_JsonNullable() {
    return lockedUntil;
  }
  
  @JsonProperty(JSON_PROPERTY_LOCKED_UNTIL)
  public void setLockedUntil_JsonNullable(JsonNullable<Long> lockedUntil) {
    this.lockedUntil = lockedUntil;
  }

  public void setLockedUntil(@jakarta.annotation.Nullable Long lockedUntil) {
    this.lockedUntil = JsonNullable.<Long>of(lockedUntil);
  }


  public PlayerProsResponse steamid(@jakarta.annotation.Nullable String steamid) {
    this.steamid = JsonNullable.<String>of(steamid);
    return this;
  }

  /**
   * steamid
   * @return steamid
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getSteamid() {
        return steamid.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_STEAMID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getSteamid_JsonNullable() {
    return steamid;
  }
  
  @JsonProperty(JSON_PROPERTY_STEAMID)
  public void setSteamid_JsonNullable(JsonNullable<String> steamid) {
    this.steamid = steamid;
  }

  public void setSteamid(@jakarta.annotation.Nullable String steamid) {
    this.steamid = JsonNullable.<String>of(steamid);
  }


  public PlayerProsResponse avatar(@jakarta.annotation.Nullable String avatar) {
    this.avatar = JsonNullable.<String>of(avatar);
    return this;
  }

  /**
   * avatar
   * @return avatar
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getAvatar() {
        return avatar.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_AVATAR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getAvatar_JsonNullable() {
    return avatar;
  }
  
  @JsonProperty(JSON_PROPERTY_AVATAR)
  public void setAvatar_JsonNullable(JsonNullable<String> avatar) {
    this.avatar = avatar;
  }

  public void setAvatar(@jakarta.annotation.Nullable String avatar) {
    this.avatar = JsonNullable.<String>of(avatar);
  }


  public PlayerProsResponse avatarmedium(@jakarta.annotation.Nullable String avatarmedium) {
    this.avatarmedium = JsonNullable.<String>of(avatarmedium);
    return this;
  }

  /**
   * avatarmedium
   * @return avatarmedium
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getAvatarmedium() {
        return avatarmedium.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_AVATARMEDIUM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getAvatarmedium_JsonNullable() {
    return avatarmedium;
  }
  
  @JsonProperty(JSON_PROPERTY_AVATARMEDIUM)
  public void setAvatarmedium_JsonNullable(JsonNullable<String> avatarmedium) {
    this.avatarmedium = avatarmedium;
  }

  public void setAvatarmedium(@jakarta.annotation.Nullable String avatarmedium) {
    this.avatarmedium = JsonNullable.<String>of(avatarmedium);
  }


  public PlayerProsResponse avatarfull(@jakarta.annotation.Nullable String avatarfull) {
    this.avatarfull = JsonNullable.<String>of(avatarfull);
    return this;
  }

  /**
   * avatarfull
   * @return avatarfull
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getAvatarfull() {
        return avatarfull.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_AVATARFULL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getAvatarfull_JsonNullable() {
    return avatarfull;
  }
  
  @JsonProperty(JSON_PROPERTY_AVATARFULL)
  public void setAvatarfull_JsonNullable(JsonNullable<String> avatarfull) {
    this.avatarfull = avatarfull;
  }

  public void setAvatarfull(@jakarta.annotation.Nullable String avatarfull) {
    this.avatarfull = JsonNullable.<String>of(avatarfull);
  }


  public PlayerProsResponse profileurl(@jakarta.annotation.Nullable String profileurl) {
    this.profileurl = JsonNullable.<String>of(profileurl);
    return this;
  }

  /**
   * profileurl
   * @return profileurl
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getProfileurl() {
        return profileurl.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_PROFILEURL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getProfileurl_JsonNullable() {
    return profileurl;
  }
  
  @JsonProperty(JSON_PROPERTY_PROFILEURL)
  public void setProfileurl_JsonNullable(JsonNullable<String> profileurl) {
    this.profileurl = profileurl;
  }

  public void setProfileurl(@jakarta.annotation.Nullable String profileurl) {
    this.profileurl = JsonNullable.<String>of(profileurl);
  }


  public PlayerProsResponse lastLogin(@jakarta.annotation.Nullable OffsetDateTime lastLogin) {
    this.lastLogin = JsonNullable.<OffsetDateTime>of(lastLogin);
    return this;
  }

  /**
   * last_login
   * @return lastLogin
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public OffsetDateTime getLastLogin() {
        return lastLogin.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_LAST_LOGIN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<OffsetDateTime> getLastLogin_JsonNullable() {
    return lastLogin;
  }
  
  @JsonProperty(JSON_PROPERTY_LAST_LOGIN)
  public void setLastLogin_JsonNullable(JsonNullable<OffsetDateTime> lastLogin) {
    this.lastLogin = lastLogin;
  }

  public void setLastLogin(@jakarta.annotation.Nullable OffsetDateTime lastLogin) {
    this.lastLogin = JsonNullable.<OffsetDateTime>of(lastLogin);
  }


  public PlayerProsResponse fullHistoryTime(@jakarta.annotation.Nullable OffsetDateTime fullHistoryTime) {
    this.fullHistoryTime = JsonNullable.<OffsetDateTime>of(fullHistoryTime);
    return this;
  }

  /**
   * full_history_time
   * @return fullHistoryTime
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public OffsetDateTime getFullHistoryTime() {
        return fullHistoryTime.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_FULL_HISTORY_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<OffsetDateTime> getFullHistoryTime_JsonNullable() {
    return fullHistoryTime;
  }
  
  @JsonProperty(JSON_PROPERTY_FULL_HISTORY_TIME)
  public void setFullHistoryTime_JsonNullable(JsonNullable<OffsetDateTime> fullHistoryTime) {
    this.fullHistoryTime = fullHistoryTime;
  }

  public void setFullHistoryTime(@jakarta.annotation.Nullable OffsetDateTime fullHistoryTime) {
    this.fullHistoryTime = JsonNullable.<OffsetDateTime>of(fullHistoryTime);
  }


  public PlayerProsResponse cheese(@jakarta.annotation.Nullable Long cheese) {
    this.cheese = JsonNullable.<Long>of(cheese);
    return this;
  }

  /**
   * cheese
   * @return cheese
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Long getCheese() {
        return cheese.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_CHEESE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Long> getCheese_JsonNullable() {
    return cheese;
  }
  
  @JsonProperty(JSON_PROPERTY_CHEESE)
  public void setCheese_JsonNullable(JsonNullable<Long> cheese) {
    this.cheese = cheese;
  }

  public void setCheese(@jakarta.annotation.Nullable Long cheese) {
    this.cheese = JsonNullable.<Long>of(cheese);
  }


  public PlayerProsResponse fhUnavailable(@jakarta.annotation.Nullable Boolean fhUnavailable) {
    this.fhUnavailable = JsonNullable.<Boolean>of(fhUnavailable);
    return this;
  }

  /**
   * fh_unavailable
   * @return fhUnavailable
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Boolean getFhUnavailable() {
        return fhUnavailable.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_FH_UNAVAILABLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Boolean> getFhUnavailable_JsonNullable() {
    return fhUnavailable;
  }
  
  @JsonProperty(JSON_PROPERTY_FH_UNAVAILABLE)
  public void setFhUnavailable_JsonNullable(JsonNullable<Boolean> fhUnavailable) {
    this.fhUnavailable = fhUnavailable;
  }

  public void setFhUnavailable(@jakarta.annotation.Nullable Boolean fhUnavailable) {
    this.fhUnavailable = JsonNullable.<Boolean>of(fhUnavailable);
  }


  public PlayerProsResponse loccountrycode(@jakarta.annotation.Nullable String loccountrycode) {
    this.loccountrycode = JsonNullable.<String>of(loccountrycode);
    return this;
  }

  /**
   * loccountrycode
   * @return loccountrycode
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getLoccountrycode() {
        return loccountrycode.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_LOCCOUNTRYCODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getLoccountrycode_JsonNullable() {
    return loccountrycode;
  }
  
  @JsonProperty(JSON_PROPERTY_LOCCOUNTRYCODE)
  public void setLoccountrycode_JsonNullable(JsonNullable<String> loccountrycode) {
    this.loccountrycode = loccountrycode;
  }

  public void setLoccountrycode(@jakarta.annotation.Nullable String loccountrycode) {
    this.loccountrycode = JsonNullable.<String>of(loccountrycode);
  }


  public PlayerProsResponse lastPlayed(@jakarta.annotation.Nullable Long lastPlayed) {
    this.lastPlayed = JsonNullable.<Long>of(lastPlayed);
    return this;
  }

  /**
   * last_played
   * @return lastPlayed
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Long getLastPlayed() {
        return lastPlayed.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_LAST_PLAYED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Long> getLastPlayed_JsonNullable() {
    return lastPlayed;
  }
  
  @JsonProperty(JSON_PROPERTY_LAST_PLAYED)
  public void setLastPlayed_JsonNullable(JsonNullable<Long> lastPlayed) {
    this.lastPlayed = lastPlayed;
  }

  public void setLastPlayed(@jakarta.annotation.Nullable Long lastPlayed) {
    this.lastPlayed = JsonNullable.<Long>of(lastPlayed);
  }


  public PlayerProsResponse win(@jakarta.annotation.Nullable Long win) {
    this.win = win;
    return this;
  }

  /**
   * win
   * @return win
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_WIN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getWin() {
    return win;
  }


  @JsonProperty(JSON_PROPERTY_WIN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setWin(@jakarta.annotation.Nullable Long win) {
    this.win = win;
  }


  public PlayerProsResponse games(@jakarta.annotation.Nullable Long games) {
    this.games = games;
    return this;
  }

  /**
   * games
   * @return games
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_GAMES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getGames() {
    return games;
  }


  @JsonProperty(JSON_PROPERTY_GAMES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setGames(@jakarta.annotation.Nullable Long games) {
    this.games = games;
  }


  public PlayerProsResponse withWin(@jakarta.annotation.Nullable Long withWin) {
    this.withWin = withWin;
    return this;
  }

  /**
   * with_win
   * @return withWin
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_WITH_WIN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getWithWin() {
    return withWin;
  }


  @JsonProperty(JSON_PROPERTY_WITH_WIN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setWithWin(@jakarta.annotation.Nullable Long withWin) {
    this.withWin = withWin;
  }


  public PlayerProsResponse withGames(@jakarta.annotation.Nullable Long withGames) {
    this.withGames = withGames;
    return this;
  }

  /**
   * with_games
   * @return withGames
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_WITH_GAMES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getWithGames() {
    return withGames;
  }


  @JsonProperty(JSON_PROPERTY_WITH_GAMES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setWithGames(@jakarta.annotation.Nullable Long withGames) {
    this.withGames = withGames;
  }


  public PlayerProsResponse againstWin(@jakarta.annotation.Nullable Long againstWin) {
    this.againstWin = againstWin;
    return this;
  }

  /**
   * against_win
   * @return againstWin
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_AGAINST_WIN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getAgainstWin() {
    return againstWin;
  }


  @JsonProperty(JSON_PROPERTY_AGAINST_WIN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAgainstWin(@jakarta.annotation.Nullable Long againstWin) {
    this.againstWin = againstWin;
  }


  public PlayerProsResponse againstGames(@jakarta.annotation.Nullable Long againstGames) {
    this.againstGames = againstGames;
    return this;
  }

  /**
   * against_games
   * @return againstGames
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_AGAINST_GAMES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getAgainstGames() {
    return againstGames;
  }


  @JsonProperty(JSON_PROPERTY_AGAINST_GAMES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAgainstGames(@jakarta.annotation.Nullable Long againstGames) {
    this.againstGames = againstGames;
  }


  public PlayerProsResponse withGpmSum(@jakarta.annotation.Nullable Long withGpmSum) {
    this.withGpmSum = JsonNullable.<Long>of(withGpmSum);
    return this;
  }

  /**
   * with_gpm_sum
   * @return withGpmSum
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Long getWithGpmSum() {
        return withGpmSum.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_WITH_GPM_SUM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Long> getWithGpmSum_JsonNullable() {
    return withGpmSum;
  }
  
  @JsonProperty(JSON_PROPERTY_WITH_GPM_SUM)
  public void setWithGpmSum_JsonNullable(JsonNullable<Long> withGpmSum) {
    this.withGpmSum = withGpmSum;
  }

  public void setWithGpmSum(@jakarta.annotation.Nullable Long withGpmSum) {
    this.withGpmSum = JsonNullable.<Long>of(withGpmSum);
  }


  public PlayerProsResponse withXpmSum(@jakarta.annotation.Nullable Long withXpmSum) {
    this.withXpmSum = JsonNullable.<Long>of(withXpmSum);
    return this;
  }

  /**
   * with_xpm_sum
   * @return withXpmSum
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Long getWithXpmSum() {
        return withXpmSum.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_WITH_XPM_SUM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Long> getWithXpmSum_JsonNullable() {
    return withXpmSum;
  }
  
  @JsonProperty(JSON_PROPERTY_WITH_XPM_SUM)
  public void setWithXpmSum_JsonNullable(JsonNullable<Long> withXpmSum) {
    this.withXpmSum = withXpmSum;
  }

  public void setWithXpmSum(@jakarta.annotation.Nullable Long withXpmSum) {
    this.withXpmSum = JsonNullable.<Long>of(withXpmSum);
  }


  /**
   * Return true if this PlayerProsResponse object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PlayerProsResponse playerProsResponse = (PlayerProsResponse) o;
    return Objects.equals(this.accountId, playerProsResponse.accountId) &&
        equalsNullable(this.name, playerProsResponse.name) &&
        Objects.equals(this.countryCode, playerProsResponse.countryCode) &&
        Objects.equals(this.fantasyRole, playerProsResponse.fantasyRole) &&
        Objects.equals(this.teamId, playerProsResponse.teamId) &&
        equalsNullable(this.teamName, playerProsResponse.teamName) &&
        equalsNullable(this.teamTag, playerProsResponse.teamTag) &&
        Objects.equals(this.isLocked, playerProsResponse.isLocked) &&
        Objects.equals(this.isPro, playerProsResponse.isPro) &&
        equalsNullable(this.lockedUntil, playerProsResponse.lockedUntil) &&
        equalsNullable(this.steamid, playerProsResponse.steamid) &&
        equalsNullable(this.avatar, playerProsResponse.avatar) &&
        equalsNullable(this.avatarmedium, playerProsResponse.avatarmedium) &&
        equalsNullable(this.avatarfull, playerProsResponse.avatarfull) &&
        equalsNullable(this.profileurl, playerProsResponse.profileurl) &&
        equalsNullable(this.lastLogin, playerProsResponse.lastLogin) &&
        equalsNullable(this.fullHistoryTime, playerProsResponse.fullHistoryTime) &&
        equalsNullable(this.cheese, playerProsResponse.cheese) &&
        equalsNullable(this.fhUnavailable, playerProsResponse.fhUnavailable) &&
        equalsNullable(this.loccountrycode, playerProsResponse.loccountrycode) &&
        equalsNullable(this.lastPlayed, playerProsResponse.lastPlayed) &&
        Objects.equals(this.win, playerProsResponse.win) &&
        Objects.equals(this.games, playerProsResponse.games) &&
        Objects.equals(this.withWin, playerProsResponse.withWin) &&
        Objects.equals(this.withGames, playerProsResponse.withGames) &&
        Objects.equals(this.againstWin, playerProsResponse.againstWin) &&
        Objects.equals(this.againstGames, playerProsResponse.againstGames) &&
        equalsNullable(this.withGpmSum, playerProsResponse.withGpmSum) &&
        equalsNullable(this.withXpmSum, playerProsResponse.withXpmSum);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(accountId, hashCodeNullable(name), countryCode, fantasyRole, teamId, hashCodeNullable(teamName), hashCodeNullable(teamTag), isLocked, isPro, hashCodeNullable(lockedUntil), hashCodeNullable(steamid), hashCodeNullable(avatar), hashCodeNullable(avatarmedium), hashCodeNullable(avatarfull), hashCodeNullable(profileurl), hashCodeNullable(lastLogin), hashCodeNullable(fullHistoryTime), hashCodeNullable(cheese), hashCodeNullable(fhUnavailable), hashCodeNullable(loccountrycode), hashCodeNullable(lastPlayed), win, games, withWin, withGames, againstWin, againstGames, hashCodeNullable(withGpmSum), hashCodeNullable(withXpmSum));
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PlayerProsResponse {\n");
    sb.append("    accountId: ").append(toIndentedString(accountId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    countryCode: ").append(toIndentedString(countryCode)).append("\n");
    sb.append("    fantasyRole: ").append(toIndentedString(fantasyRole)).append("\n");
    sb.append("    teamId: ").append(toIndentedString(teamId)).append("\n");
    sb.append("    teamName: ").append(toIndentedString(teamName)).append("\n");
    sb.append("    teamTag: ").append(toIndentedString(teamTag)).append("\n");
    sb.append("    isLocked: ").append(toIndentedString(isLocked)).append("\n");
    sb.append("    isPro: ").append(toIndentedString(isPro)).append("\n");
    sb.append("    lockedUntil: ").append(toIndentedString(lockedUntil)).append("\n");
    sb.append("    steamid: ").append(toIndentedString(steamid)).append("\n");
    sb.append("    avatar: ").append(toIndentedString(avatar)).append("\n");
    sb.append("    avatarmedium: ").append(toIndentedString(avatarmedium)).append("\n");
    sb.append("    avatarfull: ").append(toIndentedString(avatarfull)).append("\n");
    sb.append("    profileurl: ").append(toIndentedString(profileurl)).append("\n");
    sb.append("    lastLogin: ").append(toIndentedString(lastLogin)).append("\n");
    sb.append("    fullHistoryTime: ").append(toIndentedString(fullHistoryTime)).append("\n");
    sb.append("    cheese: ").append(toIndentedString(cheese)).append("\n");
    sb.append("    fhUnavailable: ").append(toIndentedString(fhUnavailable)).append("\n");
    sb.append("    loccountrycode: ").append(toIndentedString(loccountrycode)).append("\n");
    sb.append("    lastPlayed: ").append(toIndentedString(lastPlayed)).append("\n");
    sb.append("    win: ").append(toIndentedString(win)).append("\n");
    sb.append("    games: ").append(toIndentedString(games)).append("\n");
    sb.append("    withWin: ").append(toIndentedString(withWin)).append("\n");
    sb.append("    withGames: ").append(toIndentedString(withGames)).append("\n");
    sb.append("    againstWin: ").append(toIndentedString(againstWin)).append("\n");
    sb.append("    againstGames: ").append(toIndentedString(againstGames)).append("\n");
    sb.append("    withGpmSum: ").append(toIndentedString(withGpmSum)).append("\n");
    sb.append("    withXpmSum: ").append(toIndentedString(withXpmSum)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

