/*
 * OpenDota API
 * # Introduction The OpenDota API provides Dota 2 related data including advanced match data extracted from match replays.  You can find data that can be used to convert hero and ability IDs and other information provided by the API from the [dotaconstants](https://github.com/odota/dotaconstants) repository.  You can use the API without a key, but registering for a key allows increased rate limits and usage. Check out the [API page](https://www.opendota.com/api-keys) to learn more.     
 *
 * The version of the OpenAPI document: 31.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ako.dbuff.dotapi.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.ako.dbuff.dotapi.invoker.JSON;


/**
 * PlayerRatingsResponse
 */
@JsonPropertyOrder({
  PlayerRatingsResponse.JSON_PROPERTY_ACCOUNT_ID,
  PlayerRatingsResponse.JSON_PROPERTY_MATCH_ID,
  PlayerRatingsResponse.JSON_PROPERTY_SOLO_COMPETITIVE_RANK,
  PlayerRatingsResponse.JSON_PROPERTY_COMPETITIVE_RANK,
  PlayerRatingsResponse.JSON_PROPERTY_TIME
})
@com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class PlayerRatingsResponse {
  public static final String JSON_PROPERTY_ACCOUNT_ID = "account_id";
  @jakarta.annotation.Nullable
  private Long accountId;

  public static final String JSON_PROPERTY_MATCH_ID = "match_id";
  @jakarta.annotation.Nullable
  private Long matchId;

  public static final String JSON_PROPERTY_SOLO_COMPETITIVE_RANK = "solo_competitive_rank";
  private JsonNullable<Long> soloCompetitiveRank = JsonNullable.<Long>undefined();

  public static final String JSON_PROPERTY_COMPETITIVE_RANK = "competitive_rank";
  @jakarta.annotation.Nullable
  private Long competitiveRank;

  public static final String JSON_PROPERTY_TIME = "time";
  @jakarta.annotation.Nullable
  private Long time;

  public PlayerRatingsResponse() { 
  }

  public PlayerRatingsResponse accountId(@jakarta.annotation.Nullable Long accountId) {
    this.accountId = accountId;
    return this;
  }

  /**
   * The player account ID
   * @return accountId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ACCOUNT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getAccountId() {
    return accountId;
  }


  @JsonProperty(JSON_PROPERTY_ACCOUNT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAccountId(@jakarta.annotation.Nullable Long accountId) {
    this.accountId = accountId;
  }


  public PlayerRatingsResponse matchId(@jakarta.annotation.Nullable Long matchId) {
    this.matchId = matchId;
    return this;
  }

  /**
   * The ID number of the match assigned by Valve
   * @return matchId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MATCH_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getMatchId() {
    return matchId;
  }


  @JsonProperty(JSON_PROPERTY_MATCH_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMatchId(@jakarta.annotation.Nullable Long matchId) {
    this.matchId = matchId;
  }


  public PlayerRatingsResponse soloCompetitiveRank(@jakarta.annotation.Nullable Long soloCompetitiveRank) {
    this.soloCompetitiveRank = JsonNullable.<Long>of(soloCompetitiveRank);
    return this;
  }

  /**
   * solo_competitive_rank
   * @return soloCompetitiveRank
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Long getSoloCompetitiveRank() {
        return soloCompetitiveRank.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_SOLO_COMPETITIVE_RANK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Long> getSoloCompetitiveRank_JsonNullable() {
    return soloCompetitiveRank;
  }
  
  @JsonProperty(JSON_PROPERTY_SOLO_COMPETITIVE_RANK)
  public void setSoloCompetitiveRank_JsonNullable(JsonNullable<Long> soloCompetitiveRank) {
    this.soloCompetitiveRank = soloCompetitiveRank;
  }

  public void setSoloCompetitiveRank(@jakarta.annotation.Nullable Long soloCompetitiveRank) {
    this.soloCompetitiveRank = JsonNullable.<Long>of(soloCompetitiveRank);
  }


  public PlayerRatingsResponse competitiveRank(@jakarta.annotation.Nullable Long competitiveRank) {
    this.competitiveRank = competitiveRank;
    return this;
  }

  /**
   * competitive_rank
   * @return competitiveRank
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_COMPETITIVE_RANK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getCompetitiveRank() {
    return competitiveRank;
  }


  @JsonProperty(JSON_PROPERTY_COMPETITIVE_RANK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCompetitiveRank(@jakarta.annotation.Nullable Long competitiveRank) {
    this.competitiveRank = competitiveRank;
  }


  public PlayerRatingsResponse time(@jakarta.annotation.Nullable Long time) {
    this.time = time;
    return this;
  }

  /**
   * time
   * @return time
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getTime() {
    return time;
  }


  @JsonProperty(JSON_PROPERTY_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTime(@jakarta.annotation.Nullable Long time) {
    this.time = time;
  }


  /**
   * Return true if this PlayerRatingsResponse object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PlayerRatingsResponse playerRatingsResponse = (PlayerRatingsResponse) o;
    return Objects.equals(this.accountId, playerRatingsResponse.accountId) &&
        Objects.equals(this.matchId, playerRatingsResponse.matchId) &&
        equalsNullable(this.soloCompetitiveRank, playerRatingsResponse.soloCompetitiveRank) &&
        Objects.equals(this.competitiveRank, playerRatingsResponse.competitiveRank) &&
        Objects.equals(this.time, playerRatingsResponse.time);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(accountId, matchId, hashCodeNullable(soloCompetitiveRank), competitiveRank, time);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PlayerRatingsResponse {\n");
    sb.append("    accountId: ").append(toIndentedString(accountId)).append("\n");
    sb.append("    matchId: ").append(toIndentedString(matchId)).append("\n");
    sb.append("    soloCompetitiveRank: ").append(toIndentedString(soloCompetitiveRank)).append("\n");
    sb.append("    competitiveRank: ").append(toIndentedString(competitiveRank)).append("\n");
    sb.append("    time: ").append(toIndentedString(time)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

