/*
 * OpenDota API
 * # Introduction The OpenDota API provides Dota 2 related data including advanced match data extracted from match replays.  You can find data that can be used to convert hero and ability IDs and other information provided by the API from the [dotaconstants](https://github.com/odota/dotaconstants) repository.  You can use the API without a key, but registering for a key allows increased rate limits and usage. Check out the [API page](https://www.opendota.com/api-keys) to learn more.     
 *
 * The version of the OpenAPI document: 31.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ako.dbuff.dotapi.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.ako.dbuff.dotapi.invoker.JSON;


/**
 * PublicMatchesResponse
 */
@JsonPropertyOrder({
  PublicMatchesResponse.JSON_PROPERTY_MATCH_ID,
  PublicMatchesResponse.JSON_PROPERTY_MATCH_SEQ_NUM,
  PublicMatchesResponse.JSON_PROPERTY_RADIANT_WIN,
  PublicMatchesResponse.JSON_PROPERTY_START_TIME,
  PublicMatchesResponse.JSON_PROPERTY_DURATION,
  PublicMatchesResponse.JSON_PROPERTY_LOBBY_TYPE,
  PublicMatchesResponse.JSON_PROPERTY_GAME_MODE,
  PublicMatchesResponse.JSON_PROPERTY_AVG_RANK_TIER,
  PublicMatchesResponse.JSON_PROPERTY_NUM_RANK_TIER,
  PublicMatchesResponse.JSON_PROPERTY_CLUSTER,
  PublicMatchesResponse.JSON_PROPERTY_RADIANT_TEAM,
  PublicMatchesResponse.JSON_PROPERTY_DIRE_TEAM
})
@com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class PublicMatchesResponse {
  public static final String JSON_PROPERTY_MATCH_ID = "match_id";
  @jakarta.annotation.Nullable
  private Long matchId;

  public static final String JSON_PROPERTY_MATCH_SEQ_NUM = "match_seq_num";
  @jakarta.annotation.Nullable
  private Long matchSeqNum;

  public static final String JSON_PROPERTY_RADIANT_WIN = "radiant_win";
  private JsonNullable<Boolean> radiantWin = JsonNullable.<Boolean>undefined();

  public static final String JSON_PROPERTY_START_TIME = "start_time";
  @jakarta.annotation.Nullable
  private Long startTime;

  public static final String JSON_PROPERTY_DURATION = "duration";
  @jakarta.annotation.Nullable
  private Long duration;

  public static final String JSON_PROPERTY_LOBBY_TYPE = "lobby_type";
  @jakarta.annotation.Nullable
  private Long lobbyType;

  public static final String JSON_PROPERTY_GAME_MODE = "game_mode";
  @jakarta.annotation.Nullable
  private Long gameMode;

  public static final String JSON_PROPERTY_AVG_RANK_TIER = "avg_rank_tier";
  @jakarta.annotation.Nullable
  private Long avgRankTier;

  public static final String JSON_PROPERTY_NUM_RANK_TIER = "num_rank_tier";
  @jakarta.annotation.Nullable
  private Long numRankTier;

  public static final String JSON_PROPERTY_CLUSTER = "cluster";
  @jakarta.annotation.Nullable
  private Long cluster;

  public static final String JSON_PROPERTY_RADIANT_TEAM = "radiant_team";
  @jakarta.annotation.Nullable
  private List<Long> radiantTeam = new ArrayList<>();

  public static final String JSON_PROPERTY_DIRE_TEAM = "dire_team";
  @jakarta.annotation.Nullable
  private List<Long> direTeam = new ArrayList<>();

  public PublicMatchesResponse() { 
  }

  public PublicMatchesResponse matchId(@jakarta.annotation.Nullable Long matchId) {
    this.matchId = matchId;
    return this;
  }

  /**
   * The ID number of the match assigned by Valve
   * @return matchId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MATCH_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getMatchId() {
    return matchId;
  }


  @JsonProperty(JSON_PROPERTY_MATCH_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMatchId(@jakarta.annotation.Nullable Long matchId) {
    this.matchId = matchId;
  }


  public PublicMatchesResponse matchSeqNum(@jakarta.annotation.Nullable Long matchSeqNum) {
    this.matchSeqNum = matchSeqNum;
    return this;
  }

  /**
   * match_seq_num
   * @return matchSeqNum
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MATCH_SEQ_NUM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getMatchSeqNum() {
    return matchSeqNum;
  }


  @JsonProperty(JSON_PROPERTY_MATCH_SEQ_NUM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMatchSeqNum(@jakarta.annotation.Nullable Long matchSeqNum) {
    this.matchSeqNum = matchSeqNum;
  }


  public PublicMatchesResponse radiantWin(@jakarta.annotation.Nullable Boolean radiantWin) {
    this.radiantWin = JsonNullable.<Boolean>of(radiantWin);
    return this;
  }

  /**
   * Boolean indicating whether Radiant won the match
   * @return radiantWin
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Boolean getRadiantWin() {
        return radiantWin.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_RADIANT_WIN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Boolean> getRadiantWin_JsonNullable() {
    return radiantWin;
  }
  
  @JsonProperty(JSON_PROPERTY_RADIANT_WIN)
  public void setRadiantWin_JsonNullable(JsonNullable<Boolean> radiantWin) {
    this.radiantWin = radiantWin;
  }

  public void setRadiantWin(@jakarta.annotation.Nullable Boolean radiantWin) {
    this.radiantWin = JsonNullable.<Boolean>of(radiantWin);
  }


  public PublicMatchesResponse startTime(@jakarta.annotation.Nullable Long startTime) {
    this.startTime = startTime;
    return this;
  }

  /**
   * The Unix timestamp at which the game started
   * @return startTime
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_START_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getStartTime() {
    return startTime;
  }


  @JsonProperty(JSON_PROPERTY_START_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStartTime(@jakarta.annotation.Nullable Long startTime) {
    this.startTime = startTime;
  }


  public PublicMatchesResponse duration(@jakarta.annotation.Nullable Long duration) {
    this.duration = duration;
    return this;
  }

  /**
   * Duration of the game in seconds
   * @return duration
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DURATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getDuration() {
    return duration;
  }


  @JsonProperty(JSON_PROPERTY_DURATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDuration(@jakarta.annotation.Nullable Long duration) {
    this.duration = duration;
  }


  public PublicMatchesResponse lobbyType(@jakarta.annotation.Nullable Long lobbyType) {
    this.lobbyType = lobbyType;
    return this;
  }

  /**
   * Get lobbyType
   * @return lobbyType
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LOBBY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getLobbyType() {
    return lobbyType;
  }


  @JsonProperty(JSON_PROPERTY_LOBBY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLobbyType(@jakarta.annotation.Nullable Long lobbyType) {
    this.lobbyType = lobbyType;
  }


  public PublicMatchesResponse gameMode(@jakarta.annotation.Nullable Long gameMode) {
    this.gameMode = gameMode;
    return this;
  }

  /**
   * Get gameMode
   * @return gameMode
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_GAME_MODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getGameMode() {
    return gameMode;
  }


  @JsonProperty(JSON_PROPERTY_GAME_MODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setGameMode(@jakarta.annotation.Nullable Long gameMode) {
    this.gameMode = gameMode;
  }


  public PublicMatchesResponse avgRankTier(@jakarta.annotation.Nullable Long avgRankTier) {
    this.avgRankTier = avgRankTier;
    return this;
  }

  /**
   * Get avgRankTier
   * @return avgRankTier
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_AVG_RANK_TIER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getAvgRankTier() {
    return avgRankTier;
  }


  @JsonProperty(JSON_PROPERTY_AVG_RANK_TIER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAvgRankTier(@jakarta.annotation.Nullable Long avgRankTier) {
    this.avgRankTier = avgRankTier;
  }


  public PublicMatchesResponse numRankTier(@jakarta.annotation.Nullable Long numRankTier) {
    this.numRankTier = numRankTier;
    return this;
  }

  /**
   * Get numRankTier
   * @return numRankTier
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NUM_RANK_TIER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getNumRankTier() {
    return numRankTier;
  }


  @JsonProperty(JSON_PROPERTY_NUM_RANK_TIER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNumRankTier(@jakarta.annotation.Nullable Long numRankTier) {
    this.numRankTier = numRankTier;
  }


  public PublicMatchesResponse cluster(@jakarta.annotation.Nullable Long cluster) {
    this.cluster = cluster;
    return this;
  }

  /**
   * Get cluster
   * @return cluster
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CLUSTER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getCluster() {
    return cluster;
  }


  @JsonProperty(JSON_PROPERTY_CLUSTER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCluster(@jakarta.annotation.Nullable Long cluster) {
    this.cluster = cluster;
  }


  public PublicMatchesResponse radiantTeam(@jakarta.annotation.Nullable List<Long> radiantTeam) {
    this.radiantTeam = radiantTeam;
    return this;
  }

  public PublicMatchesResponse addRadiantTeamItem(Long radiantTeamItem) {
    if (this.radiantTeam == null) {
      this.radiantTeam = new ArrayList<>();
    }
    this.radiantTeam.add(radiantTeamItem);
    return this;
  }

  /**
   * radiant_team
   * @return radiantTeam
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RADIANT_TEAM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Long> getRadiantTeam() {
    return radiantTeam;
  }


  @JsonProperty(JSON_PROPERTY_RADIANT_TEAM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRadiantTeam(@jakarta.annotation.Nullable List<Long> radiantTeam) {
    this.radiantTeam = radiantTeam;
  }


  public PublicMatchesResponse direTeam(@jakarta.annotation.Nullable List<Long> direTeam) {
    this.direTeam = direTeam;
    return this;
  }

  public PublicMatchesResponse addDireTeamItem(Long direTeamItem) {
    if (this.direTeam == null) {
      this.direTeam = new ArrayList<>();
    }
    this.direTeam.add(direTeamItem);
    return this;
  }

  /**
   * dire_team
   * @return direTeam
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DIRE_TEAM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Long> getDireTeam() {
    return direTeam;
  }


  @JsonProperty(JSON_PROPERTY_DIRE_TEAM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDireTeam(@jakarta.annotation.Nullable List<Long> direTeam) {
    this.direTeam = direTeam;
  }


  /**
   * Return true if this PublicMatchesResponse object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PublicMatchesResponse publicMatchesResponse = (PublicMatchesResponse) o;
    return Objects.equals(this.matchId, publicMatchesResponse.matchId) &&
        Objects.equals(this.matchSeqNum, publicMatchesResponse.matchSeqNum) &&
        equalsNullable(this.radiantWin, publicMatchesResponse.radiantWin) &&
        Objects.equals(this.startTime, publicMatchesResponse.startTime) &&
        Objects.equals(this.duration, publicMatchesResponse.duration) &&
        Objects.equals(this.lobbyType, publicMatchesResponse.lobbyType) &&
        Objects.equals(this.gameMode, publicMatchesResponse.gameMode) &&
        Objects.equals(this.avgRankTier, publicMatchesResponse.avgRankTier) &&
        Objects.equals(this.numRankTier, publicMatchesResponse.numRankTier) &&
        Objects.equals(this.cluster, publicMatchesResponse.cluster) &&
        Objects.equals(this.radiantTeam, publicMatchesResponse.radiantTeam) &&
        Objects.equals(this.direTeam, publicMatchesResponse.direTeam);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(matchId, matchSeqNum, hashCodeNullable(radiantWin), startTime, duration, lobbyType, gameMode, avgRankTier, numRankTier, cluster, radiantTeam, direTeam);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PublicMatchesResponse {\n");
    sb.append("    matchId: ").append(toIndentedString(matchId)).append("\n");
    sb.append("    matchSeqNum: ").append(toIndentedString(matchSeqNum)).append("\n");
    sb.append("    radiantWin: ").append(toIndentedString(radiantWin)).append("\n");
    sb.append("    startTime: ").append(toIndentedString(startTime)).append("\n");
    sb.append("    duration: ").append(toIndentedString(duration)).append("\n");
    sb.append("    lobbyType: ").append(toIndentedString(lobbyType)).append("\n");
    sb.append("    gameMode: ").append(toIndentedString(gameMode)).append("\n");
    sb.append("    avgRankTier: ").append(toIndentedString(avgRankTier)).append("\n");
    sb.append("    numRankTier: ").append(toIndentedString(numRankTier)).append("\n");
    sb.append("    cluster: ").append(toIndentedString(cluster)).append("\n");
    sb.append("    radiantTeam: ").append(toIndentedString(radiantTeam)).append("\n");
    sb.append("    direTeam: ").append(toIndentedString(direTeam)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

