/*
 * OpenDota API
 * # Introduction The OpenDota API provides Dota 2 related data including advanced match data extracted from match replays.  You can find data that can be used to convert hero and ability IDs and other information provided by the API from the [dotaconstants](https://github.com/odota/dotaconstants) repository.  Without a key, you can make 2,000 free calls per day at a rate limit of 60 requests/minute. We also offer a Premium Tier with unlimited API calls and higher rate limits. Check out the [API page](https://www.opendota.com/api-keys) to learn more.     
 *
 * The version of the OpenAPI document: 26.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ako.dbuff.dotapi.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.ako.dbuff.dotapi.model.RankingsResponseRankingsInner;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.ako.dbuff.dotapi.invoker.JSON;


/**
 * RankingsResponse
 */
@JsonPropertyOrder({
  RankingsResponse.JSON_PROPERTY_HERO_ID,
  RankingsResponse.JSON_PROPERTY_RANKINGS
})
@com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class RankingsResponse {
  public static final String JSON_PROPERTY_HERO_ID = "hero_id";
  @jakarta.annotation.Nullable
  private Long heroId;

  public static final String JSON_PROPERTY_RANKINGS = "rankings";
  @jakarta.annotation.Nullable
  private List<RankingsResponseRankingsInner> rankings = new ArrayList<>();

  public RankingsResponse() { 
  }

  public RankingsResponse heroId(@jakarta.annotation.Nullable Long heroId) {
    this.heroId = heroId;
    return this;
  }

  /**
   * The ID value of the hero played
   * @return heroId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_HERO_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getHeroId() {
    return heroId;
  }


  @JsonProperty(JSON_PROPERTY_HERO_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHeroId(@jakarta.annotation.Nullable Long heroId) {
    this.heroId = heroId;
  }


  public RankingsResponse rankings(@jakarta.annotation.Nullable List<RankingsResponseRankingsInner> rankings) {
    this.rankings = rankings;
    return this;
  }

  public RankingsResponse addRankingsItem(RankingsResponseRankingsInner rankingsItem) {
    if (this.rankings == null) {
      this.rankings = new ArrayList<>();
    }
    this.rankings.add(rankingsItem);
    return this;
  }

  /**
   * rankings
   * @return rankings
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RANKINGS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<RankingsResponseRankingsInner> getRankings() {
    return rankings;
  }


  @JsonProperty(JSON_PROPERTY_RANKINGS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRankings(@jakarta.annotation.Nullable List<RankingsResponseRankingsInner> rankings) {
    this.rankings = rankings;
  }


  /**
   * Return true if this RankingsResponse object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RankingsResponse rankingsResponse = (RankingsResponse) o;
    return Objects.equals(this.heroId, rankingsResponse.heroId) &&
        Objects.equals(this.rankings, rankingsResponse.rankings);
  }

  @Override
  public int hashCode() {
    return Objects.hash(heroId, rankings);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RankingsResponse {\n");
    sb.append("    heroId: ").append(toIndentedString(heroId)).append("\n");
    sb.append("    rankings: ").append(toIndentedString(rankings)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

