/*
 * OpenDota API
 * # Introduction The OpenDota API provides Dota 2 related data including advanced match data extracted from match replays.  You can find data that can be used to convert hero and ability IDs and other information provided by the API from the [dotaconstants](https://github.com/odota/dotaconstants) repository.  You can use the API without a key, but registering for a key allows increased rate limits and usage. Check out the [API page](https://www.opendota.com/api-keys) to learn more.     
 *
 * The version of the OpenAPI document: 31.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ako.dbuff.dotapi.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.ako.dbuff.dotapi.invoker.JSON;


/**
 * RecordsResponse
 */
@JsonPropertyOrder({
  RecordsResponse.JSON_PROPERTY_MATCH_ID,
  RecordsResponse.JSON_PROPERTY_START_TIME,
  RecordsResponse.JSON_PROPERTY_HERO_ID,
  RecordsResponse.JSON_PROPERTY_SCORE
})
@com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class RecordsResponse {
  public static final String JSON_PROPERTY_MATCH_ID = "match_id";
  @jakarta.annotation.Nullable
  private Long matchId;

  public static final String JSON_PROPERTY_START_TIME = "start_time";
  @jakarta.annotation.Nullable
  private Long startTime;

  public static final String JSON_PROPERTY_HERO_ID = "hero_id";
  @jakarta.annotation.Nullable
  private Long heroId;

  public static final String JSON_PROPERTY_SCORE = "score";
  @jakarta.annotation.Nullable
  private Long score;

  public RecordsResponse() { 
  }

  public RecordsResponse matchId(@jakarta.annotation.Nullable Long matchId) {
    this.matchId = matchId;
    return this;
  }

  /**
   * The ID number of the match assigned by Valve
   * @return matchId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MATCH_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getMatchId() {
    return matchId;
  }


  @JsonProperty(JSON_PROPERTY_MATCH_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMatchId(@jakarta.annotation.Nullable Long matchId) {
    this.matchId = matchId;
  }


  public RecordsResponse startTime(@jakarta.annotation.Nullable Long startTime) {
    this.startTime = startTime;
    return this;
  }

  /**
   * The Unix timestamp at which the game started
   * @return startTime
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_START_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getStartTime() {
    return startTime;
  }


  @JsonProperty(JSON_PROPERTY_START_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStartTime(@jakarta.annotation.Nullable Long startTime) {
    this.startTime = startTime;
  }


  public RecordsResponse heroId(@jakarta.annotation.Nullable Long heroId) {
    this.heroId = heroId;
    return this;
  }

  /**
   * The ID value of the hero played
   * @return heroId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_HERO_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getHeroId() {
    return heroId;
  }


  @JsonProperty(JSON_PROPERTY_HERO_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHeroId(@jakarta.annotation.Nullable Long heroId) {
    this.heroId = heroId;
  }


  public RecordsResponse score(@jakarta.annotation.Nullable Long score) {
    this.score = score;
    return this;
  }

  /**
   * Record score
   * @return score
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SCORE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getScore() {
    return score;
  }


  @JsonProperty(JSON_PROPERTY_SCORE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setScore(@jakarta.annotation.Nullable Long score) {
    this.score = score;
  }


  /**
   * Return true if this RecordsResponse object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RecordsResponse recordsResponse = (RecordsResponse) o;
    return Objects.equals(this.matchId, recordsResponse.matchId) &&
        Objects.equals(this.startTime, recordsResponse.startTime) &&
        Objects.equals(this.heroId, recordsResponse.heroId) &&
        Objects.equals(this.score, recordsResponse.score);
  }

  @Override
  public int hashCode() {
    return Objects.hash(matchId, startTime, heroId, score);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RecordsResponse {\n");
    sb.append("    matchId: ").append(toIndentedString(matchId)).append("\n");
    sb.append("    startTime: ").append(toIndentedString(startTime)).append("\n");
    sb.append("    heroId: ").append(toIndentedString(heroId)).append("\n");
    sb.append("    score: ").append(toIndentedString(score)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

