/*
 * OpenDota API
 * # Introduction The OpenDota API provides Dota 2 related data including advanced match data extracted from match replays.  You can find data that can be used to convert hero and ability IDs and other information provided by the API from the [dotaconstants](https://github.com/odota/dotaconstants) repository.  You can use the API without a key, but registering for a key allows increased rate limits and usage. Check out the [API page](https://www.opendota.com/api-keys) to learn more.     
 *
 * The version of the OpenAPI document: 31.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ako.dbuff.dotapi.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.ako.dbuff.dotapi.invoker.JSON;


/**
 * ScenarioLaneRolesResponse
 */
@JsonPropertyOrder({
  ScenarioLaneRolesResponse.JSON_PROPERTY_HERO_ID,
  ScenarioLaneRolesResponse.JSON_PROPERTY_LANE_ROLE,
  ScenarioLaneRolesResponse.JSON_PROPERTY_TIME,
  ScenarioLaneRolesResponse.JSON_PROPERTY_GAMES,
  ScenarioLaneRolesResponse.JSON_PROPERTY_WINS
})
@com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class ScenarioLaneRolesResponse {
  public static final String JSON_PROPERTY_HERO_ID = "hero_id";
  @jakarta.annotation.Nullable
  private Long heroId;

  public static final String JSON_PROPERTY_LANE_ROLE = "lane_role";
  @jakarta.annotation.Nullable
  private Long laneRole;

  public static final String JSON_PROPERTY_TIME = "time";
  @jakarta.annotation.Nullable
  private Long time;

  public static final String JSON_PROPERTY_GAMES = "games";
  @jakarta.annotation.Nullable
  private String games;

  public static final String JSON_PROPERTY_WINS = "wins";
  @jakarta.annotation.Nullable
  private String wins;

  public ScenarioLaneRolesResponse() { 
  }

  public ScenarioLaneRolesResponse heroId(@jakarta.annotation.Nullable Long heroId) {
    this.heroId = heroId;
    return this;
  }

  /**
   * The ID value of the hero played
   * @return heroId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_HERO_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getHeroId() {
    return heroId;
  }


  @JsonProperty(JSON_PROPERTY_HERO_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHeroId(@jakarta.annotation.Nullable Long heroId) {
    this.heroId = heroId;
  }


  public ScenarioLaneRolesResponse laneRole(@jakarta.annotation.Nullable Long laneRole) {
    this.laneRole = laneRole;
    return this;
  }

  /**
   * The hero&#39;s lane role
   * @return laneRole
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LANE_ROLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getLaneRole() {
    return laneRole;
  }


  @JsonProperty(JSON_PROPERTY_LANE_ROLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLaneRole(@jakarta.annotation.Nullable Long laneRole) {
    this.laneRole = laneRole;
  }


  public ScenarioLaneRolesResponse time(@jakarta.annotation.Nullable Long time) {
    this.time = time;
    return this;
  }

  /**
   * Maximum game length in seconds
   * @return time
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getTime() {
    return time;
  }


  @JsonProperty(JSON_PROPERTY_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTime(@jakarta.annotation.Nullable Long time) {
    this.time = time;
  }


  public ScenarioLaneRolesResponse games(@jakarta.annotation.Nullable String games) {
    this.games = games;
    return this;
  }

  /**
   * The number of games where the hero played in this lane role
   * @return games
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_GAMES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getGames() {
    return games;
  }


  @JsonProperty(JSON_PROPERTY_GAMES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setGames(@jakarta.annotation.Nullable String games) {
    this.games = games;
  }


  public ScenarioLaneRolesResponse wins(@jakarta.annotation.Nullable String wins) {
    this.wins = wins;
    return this;
  }

  /**
   * The number of games won where the hero played in this lane role
   * @return wins
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_WINS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getWins() {
    return wins;
  }


  @JsonProperty(JSON_PROPERTY_WINS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setWins(@jakarta.annotation.Nullable String wins) {
    this.wins = wins;
  }


  /**
   * Return true if this ScenarioLaneRolesResponse object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ScenarioLaneRolesResponse scenarioLaneRolesResponse = (ScenarioLaneRolesResponse) o;
    return Objects.equals(this.heroId, scenarioLaneRolesResponse.heroId) &&
        Objects.equals(this.laneRole, scenarioLaneRolesResponse.laneRole) &&
        Objects.equals(this.time, scenarioLaneRolesResponse.time) &&
        Objects.equals(this.games, scenarioLaneRolesResponse.games) &&
        Objects.equals(this.wins, scenarioLaneRolesResponse.wins);
  }

  @Override
  public int hashCode() {
    return Objects.hash(heroId, laneRole, time, games, wins);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ScenarioLaneRolesResponse {\n");
    sb.append("    heroId: ").append(toIndentedString(heroId)).append("\n");
    sb.append("    laneRole: ").append(toIndentedString(laneRole)).append("\n");
    sb.append("    time: ").append(toIndentedString(time)).append("\n");
    sb.append("    games: ").append(toIndentedString(games)).append("\n");
    sb.append("    wins: ").append(toIndentedString(wins)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

