/*
 * OpenDota API
 * # Introduction The OpenDota API provides Dota 2 related data including advanced match data extracted from match replays.  You can find data that can be used to convert hero and ability IDs and other information provided by the API from the [dotaconstants](https://github.com/odota/dotaconstants) repository.  Without a key, you can make 2,000 free calls per day at a rate limit of 60 requests/minute. We also offer a Premium Tier with unlimited API calls and higher rate limits. Check out the [API page](https://www.opendota.com/api-keys) to learn more.     
 *
 * The version of the OpenAPI document: 26.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ako.dbuff.dotapi.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.ako.dbuff.dotapi.invoker.JSON;


/**
 * SchemaResponse
 */
@JsonPropertyOrder({
  SchemaResponse.JSON_PROPERTY_TABLE_NAME,
  SchemaResponse.JSON_PROPERTY_COLUMN_NAME,
  SchemaResponse.JSON_PROPERTY_DATA_TYPE
})
@com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class SchemaResponse {
  public static final String JSON_PROPERTY_TABLE_NAME = "table_name";
  @jakarta.annotation.Nullable
  private String tableName;

  public static final String JSON_PROPERTY_COLUMN_NAME = "column_name";
  @jakarta.annotation.Nullable
  private String columnName;

  public static final String JSON_PROPERTY_DATA_TYPE = "data_type";
  @jakarta.annotation.Nullable
  private String dataType;

  public SchemaResponse() { 
  }

  public SchemaResponse tableName(@jakarta.annotation.Nullable String tableName) {
    this.tableName = tableName;
    return this;
  }

  /**
   * table_name
   * @return tableName
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TABLE_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTableName() {
    return tableName;
  }


  @JsonProperty(JSON_PROPERTY_TABLE_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTableName(@jakarta.annotation.Nullable String tableName) {
    this.tableName = tableName;
  }


  public SchemaResponse columnName(@jakarta.annotation.Nullable String columnName) {
    this.columnName = columnName;
    return this;
  }

  /**
   * column_name
   * @return columnName
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_COLUMN_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getColumnName() {
    return columnName;
  }


  @JsonProperty(JSON_PROPERTY_COLUMN_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setColumnName(@jakarta.annotation.Nullable String columnName) {
    this.columnName = columnName;
  }


  public SchemaResponse dataType(@jakarta.annotation.Nullable String dataType) {
    this.dataType = dataType;
    return this;
  }

  /**
   * data_type
   * @return dataType
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DATA_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDataType() {
    return dataType;
  }


  @JsonProperty(JSON_PROPERTY_DATA_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDataType(@jakarta.annotation.Nullable String dataType) {
    this.dataType = dataType;
  }


  /**
   * Return true if this SchemaResponse object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SchemaResponse schemaResponse = (SchemaResponse) o;
    return Objects.equals(this.tableName, schemaResponse.tableName) &&
        Objects.equals(this.columnName, schemaResponse.columnName) &&
        Objects.equals(this.dataType, schemaResponse.dataType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(tableName, columnName, dataType);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SchemaResponse {\n");
    sb.append("    tableName: ").append(toIndentedString(tableName)).append("\n");
    sb.append("    columnName: ").append(toIndentedString(columnName)).append("\n");
    sb.append("    dataType: ").append(toIndentedString(dataType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

