/*
 * OpenDota API
 * # Introduction The OpenDota API provides Dota 2 related data including advanced match data extracted from match replays.  You can find data that can be used to convert hero and ability IDs and other information provided by the API from the [dotaconstants](https://github.com/odota/dotaconstants) repository.  You can use the API without a key, but registering for a key allows increased rate limits and usage. Check out the [API page](https://www.opendota.com/api-keys) to learn more.     
 *
 * The version of the OpenAPI document: 31.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ako.dbuff.dotapi.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.ako.dbuff.dotapi.invoker.JSON;


/**
 * TeamObjectResponse
 */
@JsonPropertyOrder({
  TeamObjectResponse.JSON_PROPERTY_TEAM_ID,
  TeamObjectResponse.JSON_PROPERTY_RATING,
  TeamObjectResponse.JSON_PROPERTY_WINS,
  TeamObjectResponse.JSON_PROPERTY_LOSSES,
  TeamObjectResponse.JSON_PROPERTY_LAST_MATCH_TIME,
  TeamObjectResponse.JSON_PROPERTY_NAME,
  TeamObjectResponse.JSON_PROPERTY_TAG
})
@com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class TeamObjectResponse {
  public static final String JSON_PROPERTY_TEAM_ID = "team_id";
  @jakarta.annotation.Nullable
  private Long teamId;

  public static final String JSON_PROPERTY_RATING = "rating";
  @jakarta.annotation.Nullable
  private BigDecimal rating;

  public static final String JSON_PROPERTY_WINS = "wins";
  @jakarta.annotation.Nullable
  private Long wins;

  public static final String JSON_PROPERTY_LOSSES = "losses";
  @jakarta.annotation.Nullable
  private Long losses;

  public static final String JSON_PROPERTY_LAST_MATCH_TIME = "last_match_time";
  @jakarta.annotation.Nullable
  private Long lastMatchTime;

  public static final String JSON_PROPERTY_NAME = "name";
  private JsonNullable<String> name = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_TAG = "tag";
  @jakarta.annotation.Nullable
  private String tag;

  public TeamObjectResponse() { 
  }

  public TeamObjectResponse teamId(@jakarta.annotation.Nullable Long teamId) {
    this.teamId = teamId;
    return this;
  }

  /**
   * Team&#39;s identifier
   * @return teamId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TEAM_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getTeamId() {
    return teamId;
  }


  @JsonProperty(JSON_PROPERTY_TEAM_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTeamId(@jakarta.annotation.Nullable Long teamId) {
    this.teamId = teamId;
  }


  public TeamObjectResponse rating(@jakarta.annotation.Nullable BigDecimal rating) {
    this.rating = rating;
    return this;
  }

  /**
   * The Elo rating of the team
   * @return rating
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RATING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getRating() {
    return rating;
  }


  @JsonProperty(JSON_PROPERTY_RATING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRating(@jakarta.annotation.Nullable BigDecimal rating) {
    this.rating = rating;
  }


  public TeamObjectResponse wins(@jakarta.annotation.Nullable Long wins) {
    this.wins = wins;
    return this;
  }

  /**
   * The number of games won by this team
   * @return wins
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_WINS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getWins() {
    return wins;
  }


  @JsonProperty(JSON_PROPERTY_WINS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setWins(@jakarta.annotation.Nullable Long wins) {
    this.wins = wins;
  }


  public TeamObjectResponse losses(@jakarta.annotation.Nullable Long losses) {
    this.losses = losses;
    return this;
  }

  /**
   * The number of losses by this team
   * @return losses
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LOSSES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getLosses() {
    return losses;
  }


  @JsonProperty(JSON_PROPERTY_LOSSES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLosses(@jakarta.annotation.Nullable Long losses) {
    this.losses = losses;
  }


  public TeamObjectResponse lastMatchTime(@jakarta.annotation.Nullable Long lastMatchTime) {
    this.lastMatchTime = lastMatchTime;
    return this;
  }

  /**
   * The Unix timestamp of the last match played by this team
   * @return lastMatchTime
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LAST_MATCH_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getLastMatchTime() {
    return lastMatchTime;
  }


  @JsonProperty(JSON_PROPERTY_LAST_MATCH_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLastMatchTime(@jakarta.annotation.Nullable Long lastMatchTime) {
    this.lastMatchTime = lastMatchTime;
  }


  public TeamObjectResponse name(@jakarta.annotation.Nullable String name) {
    this.name = JsonNullable.<String>of(name);
    return this;
  }

  /**
   * Team name
   * @return name
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getName() {
        return name.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getName_JsonNullable() {
    return name;
  }
  
  @JsonProperty(JSON_PROPERTY_NAME)
  public void setName_JsonNullable(JsonNullable<String> name) {
    this.name = name;
  }

  public void setName(@jakarta.annotation.Nullable String name) {
    this.name = JsonNullable.<String>of(name);
  }


  public TeamObjectResponse tag(@jakarta.annotation.Nullable String tag) {
    this.tag = tag;
    return this;
  }

  /**
   * The team tag/abbreviation
   * @return tag
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TAG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTag() {
    return tag;
  }


  @JsonProperty(JSON_PROPERTY_TAG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTag(@jakarta.annotation.Nullable String tag) {
    this.tag = tag;
  }


  /**
   * Return true if this TeamObjectResponse object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TeamObjectResponse teamObjectResponse = (TeamObjectResponse) o;
    return Objects.equals(this.teamId, teamObjectResponse.teamId) &&
        Objects.equals(this.rating, teamObjectResponse.rating) &&
        Objects.equals(this.wins, teamObjectResponse.wins) &&
        Objects.equals(this.losses, teamObjectResponse.losses) &&
        Objects.equals(this.lastMatchTime, teamObjectResponse.lastMatchTime) &&
        equalsNullable(this.name, teamObjectResponse.name) &&
        Objects.equals(this.tag, teamObjectResponse.tag);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(teamId, rating, wins, losses, lastMatchTime, hashCodeNullable(name), tag);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TeamObjectResponse {\n");
    sb.append("    teamId: ").append(toIndentedString(teamId)).append("\n");
    sb.append("    rating: ").append(toIndentedString(rating)).append("\n");
    sb.append("    wins: ").append(toIndentedString(wins)).append("\n");
    sb.append("    losses: ").append(toIndentedString(losses)).append("\n");
    sb.append("    lastMatchTime: ").append(toIndentedString(lastMatchTime)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    tag: ").append(toIndentedString(tag)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

