/*
 * OpenDota API
 * # Introduction The OpenDota API provides Dota 2 related data including advanced match data extracted from match replays.  You can find data that can be used to convert hero and ability IDs and other information provided by the API from the [dotaconstants](https://github.com/odota/dotaconstants) repository.  You can use the API without a key, but registering for a key allows increased rate limits and usage. Check out the [API page](https://www.opendota.com/api-keys) to learn more.     
 *
 * The version of the OpenAPI document: 31.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ako.dbuff.dotapi.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.ako.dbuff.dotapi.invoker.JSON;


/**
 * TeamMatchObjectResponse
 */
@JsonPropertyOrder({
  TeamMatchObjectResponse.JSON_PROPERTY_MATCH_ID,
  TeamMatchObjectResponse.JSON_PROPERTY_RADIANT,
  TeamMatchObjectResponse.JSON_PROPERTY_RADIANT_WIN,
  TeamMatchObjectResponse.JSON_PROPERTY_RADIANT_SCORE,
  TeamMatchObjectResponse.JSON_PROPERTY_DIRE_SCORE,
  TeamMatchObjectResponse.JSON_PROPERTY_DURATION,
  TeamMatchObjectResponse.JSON_PROPERTY_START_TIME,
  TeamMatchObjectResponse.JSON_PROPERTY_LEAGUEID,
  TeamMatchObjectResponse.JSON_PROPERTY_LEAGUE_NAME,
  TeamMatchObjectResponse.JSON_PROPERTY_CLUSTER,
  TeamMatchObjectResponse.JSON_PROPERTY_OPPOSING_TEAM_ID,
  TeamMatchObjectResponse.JSON_PROPERTY_OPPOSING_TEAM_NAME,
  TeamMatchObjectResponse.JSON_PROPERTY_OPPOSING_TEAM_LOGO
})
@com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class TeamMatchObjectResponse {
  public static final String JSON_PROPERTY_MATCH_ID = "match_id";
  @jakarta.annotation.Nullable
  private Long matchId;

  public static final String JSON_PROPERTY_RADIANT = "radiant";
  @jakarta.annotation.Nullable
  private Boolean radiant;

  public static final String JSON_PROPERTY_RADIANT_WIN = "radiant_win";
  private JsonNullable<Boolean> radiantWin = JsonNullable.<Boolean>undefined();

  public static final String JSON_PROPERTY_RADIANT_SCORE = "radiant_score";
  @jakarta.annotation.Nullable
  private Long radiantScore;

  public static final String JSON_PROPERTY_DIRE_SCORE = "dire_score";
  @jakarta.annotation.Nullable
  private Long direScore;

  public static final String JSON_PROPERTY_DURATION = "duration";
  @jakarta.annotation.Nullable
  private Long duration;

  public static final String JSON_PROPERTY_START_TIME = "start_time";
  @jakarta.annotation.Nullable
  private Long startTime;

  public static final String JSON_PROPERTY_LEAGUEID = "leagueid";
  @jakarta.annotation.Nullable
  private Long leagueid;

  public static final String JSON_PROPERTY_LEAGUE_NAME = "league_name";
  @jakarta.annotation.Nullable
  private String leagueName;

  public static final String JSON_PROPERTY_CLUSTER = "cluster";
  @jakarta.annotation.Nullable
  private Long cluster;

  public static final String JSON_PROPERTY_OPPOSING_TEAM_ID = "opposing_team_id";
  @jakarta.annotation.Nullable
  private Long opposingTeamId;

  public static final String JSON_PROPERTY_OPPOSING_TEAM_NAME = "opposing_team_name";
  private JsonNullable<String> opposingTeamName = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_OPPOSING_TEAM_LOGO = "opposing_team_logo";
  @jakarta.annotation.Nullable
  private String opposingTeamLogo;

  public TeamMatchObjectResponse() { 
  }

  public TeamMatchObjectResponse matchId(@jakarta.annotation.Nullable Long matchId) {
    this.matchId = matchId;
    return this;
  }

  /**
   * The ID number of the match assigned by Valve
   * @return matchId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MATCH_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getMatchId() {
    return matchId;
  }


  @JsonProperty(JSON_PROPERTY_MATCH_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMatchId(@jakarta.annotation.Nullable Long matchId) {
    this.matchId = matchId;
  }


  public TeamMatchObjectResponse radiant(@jakarta.annotation.Nullable Boolean radiant) {
    this.radiant = radiant;
    return this;
  }

  /**
   * Whether the team/player/hero was on Radiant
   * @return radiant
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RADIANT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getRadiant() {
    return radiant;
  }


  @JsonProperty(JSON_PROPERTY_RADIANT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRadiant(@jakarta.annotation.Nullable Boolean radiant) {
    this.radiant = radiant;
  }


  public TeamMatchObjectResponse radiantWin(@jakarta.annotation.Nullable Boolean radiantWin) {
    this.radiantWin = JsonNullable.<Boolean>of(radiantWin);
    return this;
  }

  /**
   * Boolean indicating whether Radiant won the match
   * @return radiantWin
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Boolean getRadiantWin() {
        return radiantWin.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_RADIANT_WIN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Boolean> getRadiantWin_JsonNullable() {
    return radiantWin;
  }
  
  @JsonProperty(JSON_PROPERTY_RADIANT_WIN)
  public void setRadiantWin_JsonNullable(JsonNullable<Boolean> radiantWin) {
    this.radiantWin = radiantWin;
  }

  public void setRadiantWin(@jakarta.annotation.Nullable Boolean radiantWin) {
    this.radiantWin = JsonNullable.<Boolean>of(radiantWin);
  }


  public TeamMatchObjectResponse radiantScore(@jakarta.annotation.Nullable Long radiantScore) {
    this.radiantScore = radiantScore;
    return this;
  }

  /**
   * Number of kills the Radiant team had when the match ended
   * @return radiantScore
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RADIANT_SCORE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getRadiantScore() {
    return radiantScore;
  }


  @JsonProperty(JSON_PROPERTY_RADIANT_SCORE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRadiantScore(@jakarta.annotation.Nullable Long radiantScore) {
    this.radiantScore = radiantScore;
  }


  public TeamMatchObjectResponse direScore(@jakarta.annotation.Nullable Long direScore) {
    this.direScore = direScore;
    return this;
  }

  /**
   * Number of kills the Dire team had when the match ended
   * @return direScore
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DIRE_SCORE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getDireScore() {
    return direScore;
  }


  @JsonProperty(JSON_PROPERTY_DIRE_SCORE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDireScore(@jakarta.annotation.Nullable Long direScore) {
    this.direScore = direScore;
  }


  public TeamMatchObjectResponse duration(@jakarta.annotation.Nullable Long duration) {
    this.duration = duration;
    return this;
  }

  /**
   * Duration of the game in seconds
   * @return duration
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DURATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getDuration() {
    return duration;
  }


  @JsonProperty(JSON_PROPERTY_DURATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDuration(@jakarta.annotation.Nullable Long duration) {
    this.duration = duration;
  }


  public TeamMatchObjectResponse startTime(@jakarta.annotation.Nullable Long startTime) {
    this.startTime = startTime;
    return this;
  }

  /**
   * The Unix timestamp at which the game started
   * @return startTime
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_START_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getStartTime() {
    return startTime;
  }


  @JsonProperty(JSON_PROPERTY_START_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStartTime(@jakarta.annotation.Nullable Long startTime) {
    this.startTime = startTime;
  }


  public TeamMatchObjectResponse leagueid(@jakarta.annotation.Nullable Long leagueid) {
    this.leagueid = leagueid;
    return this;
  }

  /**
   * Identifier for the league the match took place in
   * @return leagueid
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LEAGUEID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getLeagueid() {
    return leagueid;
  }


  @JsonProperty(JSON_PROPERTY_LEAGUEID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLeagueid(@jakarta.annotation.Nullable Long leagueid) {
    this.leagueid = leagueid;
  }


  public TeamMatchObjectResponse leagueName(@jakarta.annotation.Nullable String leagueName) {
    this.leagueName = leagueName;
    return this;
  }

  /**
   * Name of league the match took place in
   * @return leagueName
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LEAGUE_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLeagueName() {
    return leagueName;
  }


  @JsonProperty(JSON_PROPERTY_LEAGUE_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLeagueName(@jakarta.annotation.Nullable String leagueName) {
    this.leagueName = leagueName;
  }


  public TeamMatchObjectResponse cluster(@jakarta.annotation.Nullable Long cluster) {
    this.cluster = cluster;
    return this;
  }

  /**
   * cluster
   * @return cluster
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CLUSTER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getCluster() {
    return cluster;
  }


  @JsonProperty(JSON_PROPERTY_CLUSTER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCluster(@jakarta.annotation.Nullable Long cluster) {
    this.cluster = cluster;
  }


  public TeamMatchObjectResponse opposingTeamId(@jakarta.annotation.Nullable Long opposingTeamId) {
    this.opposingTeamId = opposingTeamId;
    return this;
  }

  /**
   * Opposing team identifier
   * @return opposingTeamId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_OPPOSING_TEAM_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getOpposingTeamId() {
    return opposingTeamId;
  }


  @JsonProperty(JSON_PROPERTY_OPPOSING_TEAM_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOpposingTeamId(@jakarta.annotation.Nullable Long opposingTeamId) {
    this.opposingTeamId = opposingTeamId;
  }


  public TeamMatchObjectResponse opposingTeamName(@jakarta.annotation.Nullable String opposingTeamName) {
    this.opposingTeamName = JsonNullable.<String>of(opposingTeamName);
    return this;
  }

  /**
   * Opposing team name, e.g. &#39;Evil Geniuses&#39;
   * @return opposingTeamName
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getOpposingTeamName() {
        return opposingTeamName.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_OPPOSING_TEAM_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getOpposingTeamName_JsonNullable() {
    return opposingTeamName;
  }
  
  @JsonProperty(JSON_PROPERTY_OPPOSING_TEAM_NAME)
  public void setOpposingTeamName_JsonNullable(JsonNullable<String> opposingTeamName) {
    this.opposingTeamName = opposingTeamName;
  }

  public void setOpposingTeamName(@jakarta.annotation.Nullable String opposingTeamName) {
    this.opposingTeamName = JsonNullable.<String>of(opposingTeamName);
  }


  public TeamMatchObjectResponse opposingTeamLogo(@jakarta.annotation.Nullable String opposingTeamLogo) {
    this.opposingTeamLogo = opposingTeamLogo;
    return this;
  }

  /**
   * Opposing team logo url
   * @return opposingTeamLogo
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_OPPOSING_TEAM_LOGO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getOpposingTeamLogo() {
    return opposingTeamLogo;
  }


  @JsonProperty(JSON_PROPERTY_OPPOSING_TEAM_LOGO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOpposingTeamLogo(@jakarta.annotation.Nullable String opposingTeamLogo) {
    this.opposingTeamLogo = opposingTeamLogo;
  }


  /**
   * Return true if this TeamMatchObjectResponse object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TeamMatchObjectResponse teamMatchObjectResponse = (TeamMatchObjectResponse) o;
    return Objects.equals(this.matchId, teamMatchObjectResponse.matchId) &&
        Objects.equals(this.radiant, teamMatchObjectResponse.radiant) &&
        equalsNullable(this.radiantWin, teamMatchObjectResponse.radiantWin) &&
        Objects.equals(this.radiantScore, teamMatchObjectResponse.radiantScore) &&
        Objects.equals(this.direScore, teamMatchObjectResponse.direScore) &&
        Objects.equals(this.duration, teamMatchObjectResponse.duration) &&
        Objects.equals(this.startTime, teamMatchObjectResponse.startTime) &&
        Objects.equals(this.leagueid, teamMatchObjectResponse.leagueid) &&
        Objects.equals(this.leagueName, teamMatchObjectResponse.leagueName) &&
        Objects.equals(this.cluster, teamMatchObjectResponse.cluster) &&
        Objects.equals(this.opposingTeamId, teamMatchObjectResponse.opposingTeamId) &&
        equalsNullable(this.opposingTeamName, teamMatchObjectResponse.opposingTeamName) &&
        Objects.equals(this.opposingTeamLogo, teamMatchObjectResponse.opposingTeamLogo);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(matchId, radiant, hashCodeNullable(radiantWin), radiantScore, direScore, duration, startTime, leagueid, leagueName, cluster, opposingTeamId, hashCodeNullable(opposingTeamName), opposingTeamLogo);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TeamMatchObjectResponse {\n");
    sb.append("    matchId: ").append(toIndentedString(matchId)).append("\n");
    sb.append("    radiant: ").append(toIndentedString(radiant)).append("\n");
    sb.append("    radiantWin: ").append(toIndentedString(radiantWin)).append("\n");
    sb.append("    radiantScore: ").append(toIndentedString(radiantScore)).append("\n");
    sb.append("    direScore: ").append(toIndentedString(direScore)).append("\n");
    sb.append("    duration: ").append(toIndentedString(duration)).append("\n");
    sb.append("    startTime: ").append(toIndentedString(startTime)).append("\n");
    sb.append("    leagueid: ").append(toIndentedString(leagueid)).append("\n");
    sb.append("    leagueName: ").append(toIndentedString(leagueName)).append("\n");
    sb.append("    cluster: ").append(toIndentedString(cluster)).append("\n");
    sb.append("    opposingTeamId: ").append(toIndentedString(opposingTeamId)).append("\n");
    sb.append("    opposingTeamName: ").append(toIndentedString(opposingTeamName)).append("\n");
    sb.append("    opposingTeamLogo: ").append(toIndentedString(opposingTeamLogo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

