/*
 * OpenDota API
 * # Introduction The OpenDota API provides Dota 2 related data including advanced match data extracted from match replays.  You can find data that can be used to convert hero and ability IDs and other information provided by the API from the [dotaconstants](https://github.com/odota/dotaconstants) repository.  You can use the API without a key, but registering for a key allows increased rate limits and usage. Check out the [API page](https://www.opendota.com/api-keys) to learn more.     
 *
 * The version of the OpenAPI document: 31.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ako.dbuff.dotapi.api;

import com.ako.dbuff.dotapi.invoker.*;
import com.ako.dbuff.dotapi.invoker.auth.*;
import com.ako.dbuff.dotapi.model.GetConstantsByResource200Response;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ConstantsApi
 */
public class ConstantsApiTest {

    private final ConstantsApi api = new ConstantsApi();

    /**
     * GET /constants
     *
     * Get static game data mirrored from the dotaconstants repository.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getConstantsByResourceTest() throws ApiException {
        //String resource = null;
        //GetConstantsByResource200Response response = api.getConstantsByResource(resource);
        // TODO: test validations
    }

}
