/*
 * OpenDota API
 * # Introduction The OpenDota API provides Dota 2 related data including advanced match data extracted from match replays.  You can find data that can be used to convert hero and ability IDs and other information provided by the API from the [dotaconstants](https://github.com/odota/dotaconstants) repository.  Without a key, you can make 2,000 free calls per day at a rate limit of 60 requests/minute. We also offer a Premium Tier with unlimited API calls and higher rate limits. Check out the [API page](https://www.opendota.com/api-keys) to learn more.     
 *
 * The version of the OpenAPI document: 26.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ako.dbuff.dotapi.api;

import com.ako.dbuff.dotapi.invoker.*;
import com.ako.dbuff.dotapi.invoker.auth.*;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for LiveApi
 */
public class LiveApiTest {

    private final LiveApi api = new LiveApi();

    /**
     * GET /live
     *
     * Get top currently ongoing live games
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getLiveTest() throws ApiException {
        //List<Object> response = api.getLive();
        // TODO: test validations
    }

}
