/*
 * OpenDota API
 * # Introduction The OpenDota API provides Dota 2 related data including advanced match data extracted from match replays.  You can find data that can be used to convert hero and ability IDs and other information provided by the API from the [dotaconstants](https://github.com/odota/dotaconstants) repository.  Without a key, you can make 2,000 free calls per day at a rate limit of 60 requests/minute. We also offer a Premium Tier with unlimited API calls and higher rate limits. Check out the [API page](https://www.opendota.com/api-keys) to learn more.     
 *
 * The version of the OpenAPI document: 26.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ako.dbuff.dotapi.api;

import com.ako.dbuff.dotapi.invoker.*;
import com.ako.dbuff.dotapi.invoker.auth.*;
import com.ako.dbuff.dotapi.model.PublicMatchesResponse;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PublicMatchesApi
 */
public class PublicMatchesApiTest {

    private final PublicMatchesApi api = new PublicMatchesApi();

    /**
     * GET /publicMatches
     *
     * Get list of randomly sampled public matches
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getPublicMatchesTest() throws ApiException {
        //Long lessThanMatchId = null;
        //Long minRank = null;
        //Long maxRank = null;
        //Long mmrAscending = null;
        //Long mmrDescending = null;
        //List<PublicMatchesResponse> response = api.getPublicMatches(lessThanMatchId, minRank, maxRank, mmrAscending, mmrDescending);
        // TODO: test validations
    }

}
