/*
 * OpenDota API
 * # Introduction The OpenDota API provides Dota 2 related data including advanced match data extracted from match replays.  You can find data that can be used to convert hero and ability IDs and other information provided by the API from the [dotaconstants](https://github.com/odota/dotaconstants) repository.  Without a key, you can make 2,000 free calls per day at a rate limit of 60 requests/minute. We also offer a Premium Tier with unlimited API calls and higher rate limits. Check out the [API page](https://www.opendota.com/api-keys) to learn more.     
 *
 * The version of the OpenAPI document: 26.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ako.dbuff.dotapi.api;

import com.ako.dbuff.dotapi.invoker.*;
import com.ako.dbuff.dotapi.invoker.auth.*;
import com.ako.dbuff.dotapi.model.TeamHeroesResponse;
import com.ako.dbuff.dotapi.model.TeamMatchObjectResponse;
import com.ako.dbuff.dotapi.model.TeamObjectResponse;
import com.ako.dbuff.dotapi.model.TeamPlayersResponse;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for TeamsApi
 */
public class TeamsApiTest {

    private final TeamsApi api = new TeamsApi();

    /**
     * GET /teams
     *
     * Get team data
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getTeamsTest() throws ApiException {
        //Long page = null;
        //List<TeamObjectResponse> response = api.getTeams(page);
        // TODO: test validations
    }

    /**
     * GET /teams/{team_id}
     *
     * Get data for a team
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getTeamsByTeamIdTest() throws ApiException {
        //Long teamId = null;
        //TeamObjectResponse response = api.getTeamsByTeamId(teamId);
        // TODO: test validations
    }

    /**
     * GET /teams/{team_id}/heroes
     *
     * Get heroes for a team
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getTeamsByTeamIdSelectHeroesTest() throws ApiException {
        //Long teamId = null;
        //TeamHeroesResponse response = api.getTeamsByTeamIdSelectHeroes(teamId);
        // TODO: test validations
    }

    /**
     * GET /teams/{team_id}/matches
     *
     * Get matches for a team
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getTeamsByTeamIdSelectMatchesTest() throws ApiException {
        //Long teamId = null;
        //TeamMatchObjectResponse response = api.getTeamsByTeamIdSelectMatches(teamId);
        // TODO: test validations
    }

    /**
     * GET /teams/{team_id}/players
     *
     * Get players who have played for a team
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getTeamsByTeamIdSelectPlayersTest() throws ApiException {
        //Long teamId = null;
        //TeamPlayersResponse response = api.getTeamsByTeamIdSelectPlayers(teamId);
        // TODO: test validations
    }

}
