/*
 * OpenDota API
 * # Introduction The OpenDota API provides Dota 2 related data including advanced match data extracted from match replays.  You can find data that can be used to convert hero and ability IDs and other information provided by the API from the [dotaconstants](https://github.com/odota/dotaconstants) repository.  You can use the API without a key, but registering for a key allows increased rate limits and usage. Check out the [API page](https://www.opendota.com/api-keys) to learn more.     
 *
 * The version of the OpenAPI document: 31.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ako.dbuff.dotapi.api;

import com.ako.dbuff.dotapi.invoker.*;
import com.ako.dbuff.dotapi.invoker.auth.*;
import com.ako.dbuff.dotapi.model.PlayerObjectResponse;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for TopPlayersApi
 */
public class TopPlayersApiTest {

    private final TopPlayersApi api = new TopPlayersApi();

    /**
     * GET /topPlayers
     *
     * Get list of highly ranked players
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getTopPlayersTest() throws ApiException {
        //Long turbo = null;
        //List<PlayerObjectResponse> response = api.getTopPlayers(turbo);
        // TODO: test validations
    }

}
