/*
 * OpenDota API
 * # Introduction The OpenDota API provides Dota 2 related data including advanced match data extracted from match replays.  You can find data that can be used to convert hero and ability IDs and other information provided by the API from the [dotaconstants](https://github.com/odota/dotaconstants) repository.  You can use the API without a key, but registering for a key allows increased rate limits and usage. Check out the [API page](https://www.opendota.com/api-keys) to learn more.     
 *
 * The version of the OpenAPI document: 31.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ako.dbuff.dotapi.model;

import com.ako.dbuff.dotapi.model.HeroItemPopularityResponseEarlyGameItems;
import com.ako.dbuff.dotapi.model.HeroItemPopularityResponseLateGameItems;
import com.ako.dbuff.dotapi.model.HeroItemPopularityResponseMidGameItems;
import com.ako.dbuff.dotapi.model.HeroItemPopularityResponseStartGameItems;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for HeroItemPopularityResponse
 */
public class HeroItemPopularityResponseTest {
    private final HeroItemPopularityResponse model = new HeroItemPopularityResponse();

    /**
     * Model tests for HeroItemPopularityResponse
     */
    @Test
    public void testHeroItemPopularityResponse() {
        // TODO: test HeroItemPopularityResponse
    }

    /**
     * Test the property 'startGameItems'
     */
    @Test
    public void startGameItemsTest() {
        // TODO: test startGameItems
    }

    /**
     * Test the property 'earlyGameItems'
     */
    @Test
    public void earlyGameItemsTest() {
        // TODO: test earlyGameItems
    }

    /**
     * Test the property 'midGameItems'
     */
    @Test
    public void midGameItemsTest() {
        // TODO: test midGameItems
    }

    /**
     * Test the property 'lateGameItems'
     */
    @Test
    public void lateGameItemsTest() {
        // TODO: test lateGameItems
    }

}
