/*
 * OpenDota API
 * # Introduction The OpenDota API provides Dota 2 related data including advanced match data extracted from match replays.  You can find data that can be used to convert hero and ability IDs and other information provided by the API from the [dotaconstants](https://github.com/odota/dotaconstants) repository.  You can use the API without a key, but registering for a key allows increased rate limits and usage. Check out the [API page](https://www.opendota.com/api-keys) to learn more.     
 *
 * The version of the OpenAPI document: 31.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ako.dbuff.dotapi.model;

import com.ako.dbuff.dotapi.model.MatchResponseChatInner;
import com.ako.dbuff.dotapi.model.MatchResponseDraftTimingsInner;
import com.ako.dbuff.dotapi.model.MatchResponsePausesInner;
import com.ako.dbuff.dotapi.model.MatchResponsePicksBansInner;
import com.ako.dbuff.dotapi.model.MatchResponsePlayersInner;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for MatchResponse
 */
public class MatchResponseTest {
    private final MatchResponse model = new MatchResponse();

    /**
     * Model tests for MatchResponse
     */
    @Test
    public void testMatchResponse() {
        // TODO: test MatchResponse
    }

    /**
     * Test the property 'matchId'
     */
    @Test
    public void matchIdTest() {
        // TODO: test matchId
    }

    /**
     * Test the property 'barracksStatusDire'
     */
    @Test
    public void barracksStatusDireTest() {
        // TODO: test barracksStatusDire
    }

    /**
     * Test the property 'barracksStatusRadiant'
     */
    @Test
    public void barracksStatusRadiantTest() {
        // TODO: test barracksStatusRadiant
    }

    /**
     * Test the property 'chat'
     */
    @Test
    public void chatTest() {
        // TODO: test chat
    }

    /**
     * Test the property 'cluster'
     */
    @Test
    public void clusterTest() {
        // TODO: test cluster
    }

    /**
     * Test the property 'cosmetics'
     */
    @Test
    public void cosmeticsTest() {
        // TODO: test cosmetics
    }

    /**
     * Test the property 'direScore'
     */
    @Test
    public void direScoreTest() {
        // TODO: test direScore
    }

    /**
     * Test the property 'draftTimings'
     */
    @Test
    public void draftTimingsTest() {
        // TODO: test draftTimings
    }

    /**
     * Test the property 'duration'
     */
    @Test
    public void durationTest() {
        // TODO: test duration
    }

    /**
     * Test the property 'engine'
     */
    @Test
    public void engineTest() {
        // TODO: test engine
    }

    /**
     * Test the property 'firstBloodTime'
     */
    @Test
    public void firstBloodTimeTest() {
        // TODO: test firstBloodTime
    }

    /**
     * Test the property 'gameMode'
     */
    @Test
    public void gameModeTest() {
        // TODO: test gameMode
    }

    /**
     * Test the property 'humanPlayers'
     */
    @Test
    public void humanPlayersTest() {
        // TODO: test humanPlayers
    }

    /**
     * Test the property 'leagueid'
     */
    @Test
    public void leagueidTest() {
        // TODO: test leagueid
    }

    /**
     * Test the property 'lobbyType'
     */
    @Test
    public void lobbyTypeTest() {
        // TODO: test lobbyType
    }

    /**
     * Test the property 'matchSeqNum'
     */
    @Test
    public void matchSeqNumTest() {
        // TODO: test matchSeqNum
    }

    /**
     * Test the property 'negativeVotes'
     */
    @Test
    public void negativeVotesTest() {
        // TODO: test negativeVotes
    }

    /**
     * Test the property 'objectives'
     */
    @Test
    public void objectivesTest() {
        // TODO: test objectives
    }

    /**
     * Test the property 'picksBans'
     */
    @Test
    public void picksBansTest() {
        // TODO: test picksBans
    }

    /**
     * Test the property 'positiveVotes'
     */
    @Test
    public void positiveVotesTest() {
        // TODO: test positiveVotes
    }

    /**
     * Test the property 'radiantGoldAdv'
     */
    @Test
    public void radiantGoldAdvTest() {
        // TODO: test radiantGoldAdv
    }

    /**
     * Test the property 'radiantScore'
     */
    @Test
    public void radiantScoreTest() {
        // TODO: test radiantScore
    }

    /**
     * Test the property 'radiantWin'
     */
    @Test
    public void radiantWinTest() {
        // TODO: test radiantWin
    }

    /**
     * Test the property 'radiantXpAdv'
     */
    @Test
    public void radiantXpAdvTest() {
        // TODO: test radiantXpAdv
    }

    /**
     * Test the property 'startTime'
     */
    @Test
    public void startTimeTest() {
        // TODO: test startTime
    }

    /**
     * Test the property 'teamfights'
     */
    @Test
    public void teamfightsTest() {
        // TODO: test teamfights
    }

    /**
     * Test the property 'towerStatusDire'
     */
    @Test
    public void towerStatusDireTest() {
        // TODO: test towerStatusDire
    }

    /**
     * Test the property 'towerStatusRadiant'
     */
    @Test
    public void towerStatusRadiantTest() {
        // TODO: test towerStatusRadiant
    }

    /**
     * Test the property 'version'
     */
    @Test
    public void versionTest() {
        // TODO: test version
    }

    /**
     * Test the property 'replaySalt'
     */
    @Test
    public void replaySaltTest() {
        // TODO: test replaySalt
    }

    /**
     * Test the property 'seriesId'
     */
    @Test
    public void seriesIdTest() {
        // TODO: test seriesId
    }

    /**
     * Test the property 'seriesType'
     */
    @Test
    public void seriesTypeTest() {
        // TODO: test seriesType
    }

    /**
     * Test the property 'radiantTeam'
     */
    @Test
    public void radiantTeamTest() {
        // TODO: test radiantTeam
    }

    /**
     * Test the property 'direTeam'
     */
    @Test
    public void direTeamTest() {
        // TODO: test direTeam
    }

    /**
     * Test the property 'league'
     */
    @Test
    public void leagueTest() {
        // TODO: test league
    }

    /**
     * Test the property 'skill'
     */
    @Test
    public void skillTest() {
        // TODO: test skill
    }

    /**
     * Test the property 'players'
     */
    @Test
    public void playersTest() {
        // TODO: test players
    }

    /**
     * Test the property 'patch'
     */
    @Test
    public void patchTest() {
        // TODO: test patch
    }

    /**
     * Test the property 'region'
     */
    @Test
    public void regionTest() {
        // TODO: test region
    }

    /**
     * Test the property 'allWordCounts'
     */
    @Test
    public void allWordCountsTest() {
        // TODO: test allWordCounts
    }

    /**
     * Test the property 'myWordCounts'
     */
    @Test
    public void myWordCountsTest() {
        // TODO: test myWordCounts
    }

    /**
     * Test the property '_throw'
     */
    @Test
    public void _throwTest() {
        // TODO: test _throw
    }

    /**
     * Test the property 'comeback'
     */
    @Test
    public void comebackTest() {
        // TODO: test comeback
    }

    /**
     * Test the property 'loss'
     */
    @Test
    public void lossTest() {
        // TODO: test loss
    }

    /**
     * Test the property 'win'
     */
    @Test
    public void winTest() {
        // TODO: test win
    }

    /**
     * Test the property 'replayUrl'
     */
    @Test
    public void replayUrlTest() {
        // TODO: test replayUrl
    }

    /**
     * Test the property 'pauses'
     */
    @Test
    public void pausesTest() {
        // TODO: test pauses
    }

}
