/*
 * OpenDota API
 * # Introduction The OpenDota API provides Dota 2 related data including advanced match data extracted from match replays.  You can find data that can be used to convert hero and ability IDs and other information provided by the API from the [dotaconstants](https://github.com/odota/dotaconstants) repository.  You can use the API without a key, but registering for a key allows increased rate limits and usage. Check out the [API page](https://www.opendota.com/api-keys) to learn more.     
 *
 * The version of the OpenAPI document: 31.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ako.dbuff.dotapi.model;

import com.ako.dbuff.dotapi.model.MatchResponsePlayersInnerBuybackLogInner;
import com.ako.dbuff.dotapi.model.MatchResponsePlayersInnerConnectionLogInner;
import com.ako.dbuff.dotapi.model.MatchResponsePlayersInnerCosmeticsInner;
import com.ako.dbuff.dotapi.model.MatchResponsePlayersInnerKillsLogInner;
import com.ako.dbuff.dotapi.model.MatchResponsePlayersInnerNeutralItemHistoryInner;
import com.ako.dbuff.dotapi.model.MatchResponsePlayersInnerNeutralTokensLogInner;
import com.ako.dbuff.dotapi.model.MatchResponsePlayersInnerPurchaseLogInner;
import com.ako.dbuff.dotapi.model.MatchResponsePlayersInnerRunesLogInner;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for MatchResponsePlayersInner
 */
public class MatchResponsePlayersInnerTest {
    private final MatchResponsePlayersInner model = new MatchResponsePlayersInner();

    /**
     * Model tests for MatchResponsePlayersInner
     */
    @Test
    public void testMatchResponsePlayersInner() {
        // TODO: test MatchResponsePlayersInner
    }

    /**
     * Test the property 'matchId'
     */
    @Test
    public void matchIdTest() {
        // TODO: test matchId
    }

    /**
     * Test the property 'playerSlot'
     */
    @Test
    public void playerSlotTest() {
        // TODO: test playerSlot
    }

    /**
     * Test the property 'abilityUpgradesArr'
     */
    @Test
    public void abilityUpgradesArrTest() {
        // TODO: test abilityUpgradesArr
    }

    /**
     * Test the property 'abilityUses'
     */
    @Test
    public void abilityUsesTest() {
        // TODO: test abilityUses
    }

    /**
     * Test the property 'abilityTargets'
     */
    @Test
    public void abilityTargetsTest() {
        // TODO: test abilityTargets
    }

    /**
     * Test the property 'damageTargets'
     */
    @Test
    public void damageTargetsTest() {
        // TODO: test damageTargets
    }

    /**
     * Test the property 'accountId'
     */
    @Test
    public void accountIdTest() {
        // TODO: test accountId
    }

    /**
     * Test the property 'actions'
     */
    @Test
    public void actionsTest() {
        // TODO: test actions
    }

    /**
     * Test the property 'additionalUnits'
     */
    @Test
    public void additionalUnitsTest() {
        // TODO: test additionalUnits
    }

    /**
     * Test the property 'assists'
     */
    @Test
    public void assistsTest() {
        // TODO: test assists
    }

    /**
     * Test the property 'backpack0'
     */
    @Test
    public void backpack0Test() {
        // TODO: test backpack0
    }

    /**
     * Test the property 'backpack1'
     */
    @Test
    public void backpack1Test() {
        // TODO: test backpack1
    }

    /**
     * Test the property 'backpack2'
     */
    @Test
    public void backpack2Test() {
        // TODO: test backpack2
    }

    /**
     * Test the property 'buybackLog'
     */
    @Test
    public void buybackLogTest() {
        // TODO: test buybackLog
    }

    /**
     * Test the property 'campsStacked'
     */
    @Test
    public void campsStackedTest() {
        // TODO: test campsStacked
    }

    /**
     * Test the property 'connectionLog'
     */
    @Test
    public void connectionLogTest() {
        // TODO: test connectionLog
    }

    /**
     * Test the property 'creepsStacked'
     */
    @Test
    public void creepsStackedTest() {
        // TODO: test creepsStacked
    }

    /**
     * Test the property 'damage'
     */
    @Test
    public void damageTest() {
        // TODO: test damage
    }

    /**
     * Test the property 'damageInflictor'
     */
    @Test
    public void damageInflictorTest() {
        // TODO: test damageInflictor
    }

    /**
     * Test the property 'damageInflictorReceived'
     */
    @Test
    public void damageInflictorReceivedTest() {
        // TODO: test damageInflictorReceived
    }

    /**
     * Test the property 'damageTaken'
     */
    @Test
    public void damageTakenTest() {
        // TODO: test damageTaken
    }

    /**
     * Test the property 'deaths'
     */
    @Test
    public void deathsTest() {
        // TODO: test deaths
    }

    /**
     * Test the property 'denies'
     */
    @Test
    public void deniesTest() {
        // TODO: test denies
    }

    /**
     * Test the property 'dnT'
     */
    @Test
    public void dnTTest() {
        // TODO: test dnT
    }

    /**
     * Test the property 'gold'
     */
    @Test
    public void goldTest() {
        // TODO: test gold
    }

    /**
     * Test the property 'goldPerMin'
     */
    @Test
    public void goldPerMinTest() {
        // TODO: test goldPerMin
    }

    /**
     * Test the property 'goldReasons'
     */
    @Test
    public void goldReasonsTest() {
        // TODO: test goldReasons
    }

    /**
     * Test the property 'goldSpent'
     */
    @Test
    public void goldSpentTest() {
        // TODO: test goldSpent
    }

    /**
     * Test the property 'goldT'
     */
    @Test
    public void goldTTest() {
        // TODO: test goldT
    }

    /**
     * Test the property 'heroDamage'
     */
    @Test
    public void heroDamageTest() {
        // TODO: test heroDamage
    }

    /**
     * Test the property 'heroHealing'
     */
    @Test
    public void heroHealingTest() {
        // TODO: test heroHealing
    }

    /**
     * Test the property 'heroHits'
     */
    @Test
    public void heroHitsTest() {
        // TODO: test heroHits
    }

    /**
     * Test the property 'heroId'
     */
    @Test
    public void heroIdTest() {
        // TODO: test heroId
    }

    /**
     * Test the property 'item0'
     */
    @Test
    public void item0Test() {
        // TODO: test item0
    }

    /**
     * Test the property 'item1'
     */
    @Test
    public void item1Test() {
        // TODO: test item1
    }

    /**
     * Test the property 'item2'
     */
    @Test
    public void item2Test() {
        // TODO: test item2
    }

    /**
     * Test the property 'item3'
     */
    @Test
    public void item3Test() {
        // TODO: test item3
    }

    /**
     * Test the property 'item4'
     */
    @Test
    public void item4Test() {
        // TODO: test item4
    }

    /**
     * Test the property 'item5'
     */
    @Test
    public void item5Test() {
        // TODO: test item5
    }

    /**
     * Test the property 'itemUses'
     */
    @Test
    public void itemUsesTest() {
        // TODO: test itemUses
    }

    /**
     * Test the property 'killStreaks'
     */
    @Test
    public void killStreaksTest() {
        // TODO: test killStreaks
    }

    /**
     * Test the property 'killed'
     */
    @Test
    public void killedTest() {
        // TODO: test killed
    }

    /**
     * Test the property 'killedBy'
     */
    @Test
    public void killedByTest() {
        // TODO: test killedBy
    }

    /**
     * Test the property 'kills'
     */
    @Test
    public void killsTest() {
        // TODO: test kills
    }

    /**
     * Test the property 'killsLog'
     */
    @Test
    public void killsLogTest() {
        // TODO: test killsLog
    }

    /**
     * Test the property 'lanePos'
     */
    @Test
    public void lanePosTest() {
        // TODO: test lanePos
    }

    /**
     * Test the property 'lastHits'
     */
    @Test
    public void lastHitsTest() {
        // TODO: test lastHits
    }

    /**
     * Test the property 'leaverStatus'
     */
    @Test
    public void leaverStatusTest() {
        // TODO: test leaverStatus
    }

    /**
     * Test the property 'level'
     */
    @Test
    public void levelTest() {
        // TODO: test level
    }

    /**
     * Test the property 'lhT'
     */
    @Test
    public void lhTTest() {
        // TODO: test lhT
    }

    /**
     * Test the property 'lifeState'
     */
    @Test
    public void lifeStateTest() {
        // TODO: test lifeState
    }

    /**
     * Test the property 'maxHeroHit'
     */
    @Test
    public void maxHeroHitTest() {
        // TODO: test maxHeroHit
    }

    /**
     * Test the property 'multiKills'
     */
    @Test
    public void multiKillsTest() {
        // TODO: test multiKills
    }

    /**
     * Test the property 'obs'
     */
    @Test
    public void obsTest() {
        // TODO: test obs
    }

    /**
     * Test the property 'obsLeftLog'
     */
    @Test
    public void obsLeftLogTest() {
        // TODO: test obsLeftLog
    }

    /**
     * Test the property 'obsLog'
     */
    @Test
    public void obsLogTest() {
        // TODO: test obsLog
    }

    /**
     * Test the property 'obsPlaced'
     */
    @Test
    public void obsPlacedTest() {
        // TODO: test obsPlaced
    }

    /**
     * Test the property 'partyId'
     */
    @Test
    public void partyIdTest() {
        // TODO: test partyId
    }

    /**
     * Test the property 'permanentBuffs'
     */
    @Test
    public void permanentBuffsTest() {
        // TODO: test permanentBuffs
    }

    /**
     * Test the property 'heroVariant'
     */
    @Test
    public void heroVariantTest() {
        // TODO: test heroVariant
    }

    /**
     * Test the property 'pings'
     */
    @Test
    public void pingsTest() {
        // TODO: test pings
    }

    /**
     * Test the property 'purchase'
     */
    @Test
    public void purchaseTest() {
        // TODO: test purchase
    }

    /**
     * Test the property 'purchaseLog'
     */
    @Test
    public void purchaseLogTest() {
        // TODO: test purchaseLog
    }

    /**
     * Test the property 'runePickups'
     */
    @Test
    public void runePickupsTest() {
        // TODO: test runePickups
    }

    /**
     * Test the property 'runes'
     */
    @Test
    public void runesTest() {
        // TODO: test runes
    }

    /**
     * Test the property 'runesLog'
     */
    @Test
    public void runesLogTest() {
        // TODO: test runesLog
    }

    /**
     * Test the property 'sen'
     */
    @Test
    public void senTest() {
        // TODO: test sen
    }

    /**
     * Test the property 'senLeftLog'
     */
    @Test
    public void senLeftLogTest() {
        // TODO: test senLeftLog
    }

    /**
     * Test the property 'senLog'
     */
    @Test
    public void senLogTest() {
        // TODO: test senLog
    }

    /**
     * Test the property 'senPlaced'
     */
    @Test
    public void senPlacedTest() {
        // TODO: test senPlaced
    }

    /**
     * Test the property 'stuns'
     */
    @Test
    public void stunsTest() {
        // TODO: test stuns
    }

    /**
     * Test the property 'times'
     */
    @Test
    public void timesTest() {
        // TODO: test times
    }

    /**
     * Test the property 'towerDamage'
     */
    @Test
    public void towerDamageTest() {
        // TODO: test towerDamage
    }

    /**
     * Test the property 'xpPerMin'
     */
    @Test
    public void xpPerMinTest() {
        // TODO: test xpPerMin
    }

    /**
     * Test the property 'xpReasons'
     */
    @Test
    public void xpReasonsTest() {
        // TODO: test xpReasons
    }

    /**
     * Test the property 'xpT'
     */
    @Test
    public void xpTTest() {
        // TODO: test xpT
    }

    /**
     * Test the property 'personaname'
     */
    @Test
    public void personanameTest() {
        // TODO: test personaname
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'lastLogin'
     */
    @Test
    public void lastLoginTest() {
        // TODO: test lastLogin
    }

    /**
     * Test the property 'radiantWin'
     */
    @Test
    public void radiantWinTest() {
        // TODO: test radiantWin
    }

    /**
     * Test the property 'startTime'
     */
    @Test
    public void startTimeTest() {
        // TODO: test startTime
    }

    /**
     * Test the property 'duration'
     */
    @Test
    public void durationTest() {
        // TODO: test duration
    }

    /**
     * Test the property 'cluster'
     */
    @Test
    public void clusterTest() {
        // TODO: test cluster
    }

    /**
     * Test the property 'lobbyType'
     */
    @Test
    public void lobbyTypeTest() {
        // TODO: test lobbyType
    }

    /**
     * Test the property 'gameMode'
     */
    @Test
    public void gameModeTest() {
        // TODO: test gameMode
    }

    /**
     * Test the property 'patch'
     */
    @Test
    public void patchTest() {
        // TODO: test patch
    }

    /**
     * Test the property 'region'
     */
    @Test
    public void regionTest() {
        // TODO: test region
    }

    /**
     * Test the property 'isRadiant'
     */
    @Test
    public void isRadiantTest() {
        // TODO: test isRadiant
    }

    /**
     * Test the property 'win'
     */
    @Test
    public void winTest() {
        // TODO: test win
    }

    /**
     * Test the property 'lose'
     */
    @Test
    public void loseTest() {
        // TODO: test lose
    }

    /**
     * Test the property 'totalGold'
     */
    @Test
    public void totalGoldTest() {
        // TODO: test totalGold
    }

    /**
     * Test the property 'totalXp'
     */
    @Test
    public void totalXpTest() {
        // TODO: test totalXp
    }

    /**
     * Test the property 'killsPerMin'
     */
    @Test
    public void killsPerMinTest() {
        // TODO: test killsPerMin
    }

    /**
     * Test the property 'kda'
     */
    @Test
    public void kdaTest() {
        // TODO: test kda
    }

    /**
     * Test the property 'abandons'
     */
    @Test
    public void abandonsTest() {
        // TODO: test abandons
    }

    /**
     * Test the property 'neutralKills'
     */
    @Test
    public void neutralKillsTest() {
        // TODO: test neutralKills
    }

    /**
     * Test the property 'towerKills'
     */
    @Test
    public void towerKillsTest() {
        // TODO: test towerKills
    }

    /**
     * Test the property 'courierKills'
     */
    @Test
    public void courierKillsTest() {
        // TODO: test courierKills
    }

    /**
     * Test the property 'laneKills'
     */
    @Test
    public void laneKillsTest() {
        // TODO: test laneKills
    }

    /**
     * Test the property 'heroKills'
     */
    @Test
    public void heroKillsTest() {
        // TODO: test heroKills
    }

    /**
     * Test the property 'observerKills'
     */
    @Test
    public void observerKillsTest() {
        // TODO: test observerKills
    }

    /**
     * Test the property 'sentryKills'
     */
    @Test
    public void sentryKillsTest() {
        // TODO: test sentryKills
    }

    /**
     * Test the property 'roshanKills'
     */
    @Test
    public void roshanKillsTest() {
        // TODO: test roshanKills
    }

    /**
     * Test the property 'necronomiconKills'
     */
    @Test
    public void necronomiconKillsTest() {
        // TODO: test necronomiconKills
    }

    /**
     * Test the property 'ancientKills'
     */
    @Test
    public void ancientKillsTest() {
        // TODO: test ancientKills
    }

    /**
     * Test the property 'buybackCount'
     */
    @Test
    public void buybackCountTest() {
        // TODO: test buybackCount
    }

    /**
     * Test the property 'observerUses'
     */
    @Test
    public void observerUsesTest() {
        // TODO: test observerUses
    }

    /**
     * Test the property 'sentryUses'
     */
    @Test
    public void sentryUsesTest() {
        // TODO: test sentryUses
    }

    /**
     * Test the property 'laneEfficiency'
     */
    @Test
    public void laneEfficiencyTest() {
        // TODO: test laneEfficiency
    }

    /**
     * Test the property 'laneEfficiencyPct'
     */
    @Test
    public void laneEfficiencyPctTest() {
        // TODO: test laneEfficiencyPct
    }

    /**
     * Test the property 'lane'
     */
    @Test
    public void laneTest() {
        // TODO: test lane
    }

    /**
     * Test the property 'laneRole'
     */
    @Test
    public void laneRoleTest() {
        // TODO: test laneRole
    }

    /**
     * Test the property 'isRoaming'
     */
    @Test
    public void isRoamingTest() {
        // TODO: test isRoaming
    }

    /**
     * Test the property 'purchaseTime'
     */
    @Test
    public void purchaseTimeTest() {
        // TODO: test purchaseTime
    }

    /**
     * Test the property 'firstPurchaseTime'
     */
    @Test
    public void firstPurchaseTimeTest() {
        // TODO: test firstPurchaseTime
    }

    /**
     * Test the property 'itemWin'
     */
    @Test
    public void itemWinTest() {
        // TODO: test itemWin
    }

    /**
     * Test the property 'itemUsage'
     */
    @Test
    public void itemUsageTest() {
        // TODO: test itemUsage
    }

    /**
     * Test the property 'purchaseTpscroll'
     */
    @Test
    public void purchaseTpscrollTest() {
        // TODO: test purchaseTpscroll
    }

    /**
     * Test the property 'actionsPerMin'
     */
    @Test
    public void actionsPerMinTest() {
        // TODO: test actionsPerMin
    }

    /**
     * Test the property 'lifeStateDead'
     */
    @Test
    public void lifeStateDeadTest() {
        // TODO: test lifeStateDead
    }

    /**
     * Test the property 'rankTier'
     */
    @Test
    public void rankTierTest() {
        // TODO: test rankTier
    }

    /**
     * Test the property 'cosmetics'
     */
    @Test
    public void cosmeticsTest() {
        // TODO: test cosmetics
    }

    /**
     * Test the property 'benchmarks'
     */
    @Test
    public void benchmarksTest() {
        // TODO: test benchmarks
    }

    /**
     * Test the property 'neutralTokensLog'
     */
    @Test
    public void neutralTokensLogTest() {
        // TODO: test neutralTokensLog
    }

    /**
     * Test the property 'neutralItemHistory'
     */
    @Test
    public void neutralItemHistoryTest() {
        // TODO: test neutralItemHistory
    }

    /**
     * Test the property 'aghanimsScepter'
     */
    @Test
    public void aghanimsScepterTest() {
        // TODO: test aghanimsScepter
    }

    /**
     * Test the property 'aghanimsShard'
     */
    @Test
    public void aghanimsShardTest() {
        // TODO: test aghanimsShard
    }

    /**
     * Test the property 'moonshard'
     */
    @Test
    public void moonshardTest() {
        // TODO: test moonshard
    }

    /**
     * Test the property 'firstbloodClaimed'
     */
    @Test
    public void firstbloodClaimedTest() {
        // TODO: test firstbloodClaimed
    }

    /**
     * Test the property 'teamfightParticipation'
     */
    @Test
    public void teamfightParticipationTest() {
        // TODO: test teamfightParticipation
    }

    /**
     * Test the property 'towersKilled'
     */
    @Test
    public void towersKilledTest() {
        // TODO: test towersKilled
    }

    /**
     * Test the property 'roshansKilled'
     */
    @Test
    public void roshansKilledTest() {
        // TODO: test roshansKilled
    }

    /**
     * Test the property 'observersPlaced'
     */
    @Test
    public void observersPlacedTest() {
        // TODO: test observersPlaced
    }

    /**
     * Test the property 'healing'
     */
    @Test
    public void healingTest() {
        // TODO: test healing
    }

    /**
     * Test the property 'randomed'
     */
    @Test
    public void randomedTest() {
        // TODO: test randomed
    }

    /**
     * Test the property 'predVict'
     */
    @Test
    public void predVictTest() {
        // TODO: test predVict
    }

    /**
     * Test the property 'partySize'
     */
    @Test
    public void partySizeTest() {
        // TODO: test partySize
    }

    /**
     * Test the property 'teamNumber'
     */
    @Test
    public void teamNumberTest() {
        // TODO: test teamNumber
    }

    /**
     * Test the property 'teamSlot'
     */
    @Test
    public void teamSlotTest() {
        // TODO: test teamSlot
    }

    /**
     * Test the property 'itemNeutral'
     */
    @Test
    public void itemNeutralTest() {
        // TODO: test itemNeutral
    }

    /**
     * Test the property 'itemNeutral2'
     */
    @Test
    public void itemNeutral2Test() {
        // TODO: test itemNeutral2
    }

    /**
     * Test the property 'netWorth'
     */
    @Test
    public void netWorthTest() {
        // TODO: test netWorth
    }

    /**
     * Test the property 'computedMmr'
     */
    @Test
    public void computedMmrTest() {
        // TODO: test computedMmr
    }

    /**
     * Test the property 'isSubscriber'
     */
    @Test
    public void isSubscriberTest() {
        // TODO: test isSubscriber
    }

    /**
     * Test the property 'isContributor'
     */
    @Test
    public void isContributorTest() {
        // TODO: test isContributor
    }

}
