/*
 * OpenDota API
 * # Introduction The OpenDota API provides Dota 2 related data including advanced match data extracted from match replays.  You can find data that can be used to convert hero and ability IDs and other information provided by the API from the [dotaconstants](https://github.com/odota/dotaconstants) repository.  Without a key, you can make 2,000 free calls per day at a rate limit of 60 requests/minute. We also offer a Premium Tier with unlimited API calls and higher rate limits. Check out the [API page](https://www.opendota.com/api-keys) to learn more.     
 *
 * The version of the OpenAPI document: 26.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ako.dbuff.dotapi.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PlayerHeroesResponse
 */
public class PlayerHeroesResponseTest {
    private final PlayerHeroesResponse model = new PlayerHeroesResponse();

    /**
     * Model tests for PlayerHeroesResponse
     */
    @Test
    public void testPlayerHeroesResponse() {
        // TODO: test PlayerHeroesResponse
    }

    /**
     * Test the property 'heroId'
     */
    @Test
    public void heroIdTest() {
        // TODO: test heroId
    }

    /**
     * Test the property 'lastPlayed'
     */
    @Test
    public void lastPlayedTest() {
        // TODO: test lastPlayed
    }

    /**
     * Test the property 'games'
     */
    @Test
    public void gamesTest() {
        // TODO: test games
    }

    /**
     * Test the property 'win'
     */
    @Test
    public void winTest() {
        // TODO: test win
    }

    /**
     * Test the property 'withGames'
     */
    @Test
    public void withGamesTest() {
        // TODO: test withGames
    }

    /**
     * Test the property 'withWin'
     */
    @Test
    public void withWinTest() {
        // TODO: test withWin
    }

    /**
     * Test the property 'againstGames'
     */
    @Test
    public void againstGamesTest() {
        // TODO: test againstGames
    }

    /**
     * Test the property 'againstWin'
     */
    @Test
    public void againstWinTest() {
        // TODO: test againstWin
    }

}
