/*
 * OpenDota API
 * # Introduction The OpenDota API provides Dota 2 related data including advanced match data extracted from match replays.  You can find data that can be used to convert hero and ability IDs and other information provided by the API from the [dotaconstants](https://github.com/odota/dotaconstants) repository.  Without a key, you can make 2,000 free calls per day at a rate limit of 60 requests/minute. We also offer a Premium Tier with unlimited API calls and higher rate limits. Check out the [API page](https://www.opendota.com/api-keys) to learn more.     
 *
 * The version of the OpenAPI document: 26.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ako.dbuff.dotapi.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PlayerMatchesResponse
 */
public class PlayerMatchesResponseTest {
    private final PlayerMatchesResponse model = new PlayerMatchesResponse();

    /**
     * Model tests for PlayerMatchesResponse
     */
    @Test
    public void testPlayerMatchesResponse() {
        // TODO: test PlayerMatchesResponse
    }

    /**
     * Test the property 'matchId'
     */
    @Test
    public void matchIdTest() {
        // TODO: test matchId
    }

    /**
     * Test the property 'playerSlot'
     */
    @Test
    public void playerSlotTest() {
        // TODO: test playerSlot
    }

    /**
     * Test the property 'radiantWin'
     */
    @Test
    public void radiantWinTest() {
        // TODO: test radiantWin
    }

    /**
     * Test the property 'duration'
     */
    @Test
    public void durationTest() {
        // TODO: test duration
    }

    /**
     * Test the property 'gameMode'
     */
    @Test
    public void gameModeTest() {
        // TODO: test gameMode
    }

    /**
     * Test the property 'lobbyType'
     */
    @Test
    public void lobbyTypeTest() {
        // TODO: test lobbyType
    }

    /**
     * Test the property 'heroId'
     */
    @Test
    public void heroIdTest() {
        // TODO: test heroId
    }

    /**
     * Test the property 'startTime'
     */
    @Test
    public void startTimeTest() {
        // TODO: test startTime
    }

    /**
     * Test the property 'version'
     */
    @Test
    public void versionTest() {
        // TODO: test version
    }

    /**
     * Test the property 'kills'
     */
    @Test
    public void killsTest() {
        // TODO: test kills
    }

    /**
     * Test the property 'deaths'
     */
    @Test
    public void deathsTest() {
        // TODO: test deaths
    }

    /**
     * Test the property 'assists'
     */
    @Test
    public void assistsTest() {
        // TODO: test assists
    }

    /**
     * Test the property 'skill'
     */
    @Test
    public void skillTest() {
        // TODO: test skill
    }

    /**
     * Test the property 'averageRank'
     */
    @Test
    public void averageRankTest() {
        // TODO: test averageRank
    }

    /**
     * Test the property 'leaverStatus'
     */
    @Test
    public void leaverStatusTest() {
        // TODO: test leaverStatus
    }

    /**
     * Test the property 'partySize'
     */
    @Test
    public void partySizeTest() {
        // TODO: test partySize
    }

    /**
     * Test the property 'heroVariant'
     */
    @Test
    public void heroVariantTest() {
        // TODO: test heroVariant
    }

}
