/*
 * OpenDota API
 * # Introduction The OpenDota API provides Dota 2 related data including advanced match data extracted from match replays.  You can find data that can be used to convert hero and ability IDs and other information provided by the API from the [dotaconstants](https://github.com/odota/dotaconstants) repository.  Without a key, you can make 2,000 free calls per day at a rate limit of 60 requests/minute. We also offer a Premium Tier with unlimited API calls and higher rate limits. Check out the [API page](https://www.opendota.com/api-keys) to learn more.     
 *
 * The version of the OpenAPI document: 26.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ako.dbuff.dotapi.model;

import com.ako.dbuff.dotapi.model.PlayersResponseProfile;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PlayersResponse
 */
public class PlayersResponseTest {
    private final PlayersResponse model = new PlayersResponse();

    /**
     * Model tests for PlayersResponse
     */
    @Test
    public void testPlayersResponse() {
        // TODO: test PlayersResponse
    }

    /**
     * Test the property 'soloCompetitiveRank'
     */
    @Test
    public void soloCompetitiveRankTest() {
        // TODO: test soloCompetitiveRank
    }

    /**
     * Test the property 'competitiveRank'
     */
    @Test
    public void competitiveRankTest() {
        // TODO: test competitiveRank
    }

    /**
     * Test the property 'rankTier'
     */
    @Test
    public void rankTierTest() {
        // TODO: test rankTier
    }

    /**
     * Test the property 'leaderboardRank'
     */
    @Test
    public void leaderboardRankTest() {
        // TODO: test leaderboardRank
    }

    /**
     * Test the property 'profile'
     */
    @Test
    public void profileTest() {
        // TODO: test profile
    }

}
