/*
 * OpenDota API
 * # Introduction The OpenDota API provides Dota 2 related data including advanced match data extracted from match replays.  You can find data that can be used to convert hero and ability IDs and other information provided by the API from the [dotaconstants](https://github.com/odota/dotaconstants) repository.  Without a key, you can make 2,000 free calls per day at a rate limit of 60 requests/minute. We also offer a Premium Tier with unlimited API calls and higher rate limits. Check out the [API page](https://www.opendota.com/api-keys) to learn more.     
 *
 * The version of the OpenAPI document: 26.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ako.dbuff.dotapi.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PlayerProsResponse
 */
public class PlayerProsResponseTest {
    private final PlayerProsResponse model = new PlayerProsResponse();

    /**
     * Model tests for PlayerProsResponse
     */
    @Test
    public void testPlayerProsResponse() {
        // TODO: test PlayerProsResponse
    }

    /**
     * Test the property 'accountId'
     */
    @Test
    public void accountIdTest() {
        // TODO: test accountId
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'countryCode'
     */
    @Test
    public void countryCodeTest() {
        // TODO: test countryCode
    }

    /**
     * Test the property 'fantasyRole'
     */
    @Test
    public void fantasyRoleTest() {
        // TODO: test fantasyRole
    }

    /**
     * Test the property 'teamId'
     */
    @Test
    public void teamIdTest() {
        // TODO: test teamId
    }

    /**
     * Test the property 'teamName'
     */
    @Test
    public void teamNameTest() {
        // TODO: test teamName
    }

    /**
     * Test the property 'teamTag'
     */
    @Test
    public void teamTagTest() {
        // TODO: test teamTag
    }

    /**
     * Test the property 'isLocked'
     */
    @Test
    public void isLockedTest() {
        // TODO: test isLocked
    }

    /**
     * Test the property 'isPro'
     */
    @Test
    public void isProTest() {
        // TODO: test isPro
    }

    /**
     * Test the property 'lockedUntil'
     */
    @Test
    public void lockedUntilTest() {
        // TODO: test lockedUntil
    }

    /**
     * Test the property 'steamid'
     */
    @Test
    public void steamidTest() {
        // TODO: test steamid
    }

    /**
     * Test the property 'avatar'
     */
    @Test
    public void avatarTest() {
        // TODO: test avatar
    }

    /**
     * Test the property 'avatarmedium'
     */
    @Test
    public void avatarmediumTest() {
        // TODO: test avatarmedium
    }

    /**
     * Test the property 'avatarfull'
     */
    @Test
    public void avatarfullTest() {
        // TODO: test avatarfull
    }

    /**
     * Test the property 'profileurl'
     */
    @Test
    public void profileurlTest() {
        // TODO: test profileurl
    }

    /**
     * Test the property 'lastLogin'
     */
    @Test
    public void lastLoginTest() {
        // TODO: test lastLogin
    }

    /**
     * Test the property 'fullHistoryTime'
     */
    @Test
    public void fullHistoryTimeTest() {
        // TODO: test fullHistoryTime
    }

    /**
     * Test the property 'cheese'
     */
    @Test
    public void cheeseTest() {
        // TODO: test cheese
    }

    /**
     * Test the property 'fhUnavailable'
     */
    @Test
    public void fhUnavailableTest() {
        // TODO: test fhUnavailable
    }

    /**
     * Test the property 'loccountrycode'
     */
    @Test
    public void loccountrycodeTest() {
        // TODO: test loccountrycode
    }

    /**
     * Test the property 'lastPlayed'
     */
    @Test
    public void lastPlayedTest() {
        // TODO: test lastPlayed
    }

    /**
     * Test the property 'win'
     */
    @Test
    public void winTest() {
        // TODO: test win
    }

    /**
     * Test the property 'games'
     */
    @Test
    public void gamesTest() {
        // TODO: test games
    }

    /**
     * Test the property 'withWin'
     */
    @Test
    public void withWinTest() {
        // TODO: test withWin
    }

    /**
     * Test the property 'withGames'
     */
    @Test
    public void withGamesTest() {
        // TODO: test withGames
    }

    /**
     * Test the property 'againstWin'
     */
    @Test
    public void againstWinTest() {
        // TODO: test againstWin
    }

    /**
     * Test the property 'againstGames'
     */
    @Test
    public void againstGamesTest() {
        // TODO: test againstGames
    }

    /**
     * Test the property 'withGpmSum'
     */
    @Test
    public void withGpmSumTest() {
        // TODO: test withGpmSum
    }

    /**
     * Test the property 'withXpmSum'
     */
    @Test
    public void withXpmSumTest() {
        // TODO: test withXpmSum
    }

}
