/*
 * OpenDota API
 * # Introduction The OpenDota API provides Dota 2 related data including advanced match data extracted from match replays.  You can find data that can be used to convert hero and ability IDs and other information provided by the API from the [dotaconstants](https://github.com/odota/dotaconstants) repository.  Without a key, you can make 2,000 free calls per day at a rate limit of 60 requests/minute. We also offer a Premium Tier with unlimited API calls and higher rate limits. Check out the [API page](https://www.opendota.com/api-keys) to learn more.     
 *
 * The version of the OpenAPI document: 26.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ako.dbuff.dotapi.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PlayersResponseProfile
 */
public class PlayersResponseProfileTest {
    private final PlayersResponseProfile model = new PlayersResponseProfile();

    /**
     * Model tests for PlayersResponseProfile
     */
    @Test
    public void testPlayersResponseProfile() {
        // TODO: test PlayersResponseProfile
    }

    /**
     * Test the property 'accountId'
     */
    @Test
    public void accountIdTest() {
        // TODO: test accountId
    }

    /**
     * Test the property 'personaname'
     */
    @Test
    public void personanameTest() {
        // TODO: test personaname
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'plus'
     */
    @Test
    public void plusTest() {
        // TODO: test plus
    }

    /**
     * Test the property 'cheese'
     */
    @Test
    public void cheeseTest() {
        // TODO: test cheese
    }

    /**
     * Test the property 'steamid'
     */
    @Test
    public void steamidTest() {
        // TODO: test steamid
    }

    /**
     * Test the property 'avatar'
     */
    @Test
    public void avatarTest() {
        // TODO: test avatar
    }

    /**
     * Test the property 'avatarmedium'
     */
    @Test
    public void avatarmediumTest() {
        // TODO: test avatarmedium
    }

    /**
     * Test the property 'avatarfull'
     */
    @Test
    public void avatarfullTest() {
        // TODO: test avatarfull
    }

    /**
     * Test the property 'profileurl'
     */
    @Test
    public void profileurlTest() {
        // TODO: test profileurl
    }

    /**
     * Test the property 'lastLogin'
     */
    @Test
    public void lastLoginTest() {
        // TODO: test lastLogin
    }

    /**
     * Test the property 'loccountrycode'
     */
    @Test
    public void loccountrycodeTest() {
        // TODO: test loccountrycode
    }

    /**
     * Test the property 'isContributor'
     */
    @Test
    public void isContributorTest() {
        // TODO: test isContributor
    }

    /**
     * Test the property 'isSubscriber'
     */
    @Test
    public void isSubscriberTest() {
        // TODO: test isSubscriber
    }

}
