/*
 * OpenDota API
 * # Introduction The OpenDota API provides Dota 2 related data including advanced match data extracted from match replays.  You can find data that can be used to convert hero and ability IDs and other information provided by the API from the [dotaconstants](https://github.com/odota/dotaconstants) repository.  You can use the API without a key, but registering for a key allows increased rate limits and usage. Check out the [API page](https://www.opendota.com/api-keys) to learn more.     
 *
 * The version of the OpenAPI document: 31.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ako.dbuff.dotapi.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for RankingsResponseRankingsInner
 */
public class RankingsResponseRankingsInnerTest {
    private final RankingsResponseRankingsInner model = new RankingsResponseRankingsInner();

    /**
     * Model tests for RankingsResponseRankingsInner
     */
    @Test
    public void testRankingsResponseRankingsInner() {
        // TODO: test RankingsResponseRankingsInner
    }

    /**
     * Test the property 'accountId'
     */
    @Test
    public void accountIdTest() {
        // TODO: test accountId
    }

    /**
     * Test the property 'score'
     */
    @Test
    public void scoreTest() {
        // TODO: test score
    }

    /**
     * Test the property 'steamid'
     */
    @Test
    public void steamidTest() {
        // TODO: test steamid
    }

    /**
     * Test the property 'avatar'
     */
    @Test
    public void avatarTest() {
        // TODO: test avatar
    }

    /**
     * Test the property 'avatarmedium'
     */
    @Test
    public void avatarmediumTest() {
        // TODO: test avatarmedium
    }

    /**
     * Test the property 'avatarfull'
     */
    @Test
    public void avatarfullTest() {
        // TODO: test avatarfull
    }

    /**
     * Test the property 'profileurl'
     */
    @Test
    public void profileurlTest() {
        // TODO: test profileurl
    }

    /**
     * Test the property 'personaname'
     */
    @Test
    public void personanameTest() {
        // TODO: test personaname
    }

    /**
     * Test the property 'lastLogin'
     */
    @Test
    public void lastLoginTest() {
        // TODO: test lastLogin
    }

    /**
     * Test the property 'fullHistoryTime'
     */
    @Test
    public void fullHistoryTimeTest() {
        // TODO: test fullHistoryTime
    }

    /**
     * Test the property 'cheese'
     */
    @Test
    public void cheeseTest() {
        // TODO: test cheese
    }

    /**
     * Test the property 'fhUnavailable'
     */
    @Test
    public void fhUnavailableTest() {
        // TODO: test fhUnavailable
    }

    /**
     * Test the property 'loccountrycode'
     */
    @Test
    public void loccountrycodeTest() {
        // TODO: test loccountrycode
    }

    /**
     * Test the property 'rankTier'
     */
    @Test
    public void rankTierTest() {
        // TODO: test rankTier
    }

}
