/*
 * OpenDota API
 * # Introduction The OpenDota API provides Dota 2 related data including advanced match data extracted from match replays.  You can find data that can be used to convert hero and ability IDs and other information provided by the API from the [dotaconstants](https://github.com/odota/dotaconstants) repository.  You can use the API without a key, but registering for a key allows increased rate limits and usage. Check out the [API page](https://www.opendota.com/api-keys) to learn more.     
 *
 * The version of the OpenAPI document: 31.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ako.dbuff.dotapi.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ScenarioLaneRolesResponse
 */
public class ScenarioLaneRolesResponseTest {
    private final ScenarioLaneRolesResponse model = new ScenarioLaneRolesResponse();

    /**
     * Model tests for ScenarioLaneRolesResponse
     */
    @Test
    public void testScenarioLaneRolesResponse() {
        // TODO: test ScenarioLaneRolesResponse
    }

    /**
     * Test the property 'heroId'
     */
    @Test
    public void heroIdTest() {
        // TODO: test heroId
    }

    /**
     * Test the property 'laneRole'
     */
    @Test
    public void laneRoleTest() {
        // TODO: test laneRole
    }

    /**
     * Test the property 'time'
     */
    @Test
    public void timeTest() {
        // TODO: test time
    }

    /**
     * Test the property 'games'
     */
    @Test
    public void gamesTest() {
        // TODO: test games
    }

    /**
     * Test the property 'wins'
     */
    @Test
    public void winsTest() {
        // TODO: test wins
    }

}
