/*
 * OpenDota API
 * # Introduction The OpenDota API provides Dota 2 related data including advanced match data extracted from match replays.  You can find data that can be used to convert hero and ability IDs and other information provided by the API from the [dotaconstants](https://github.com/odota/dotaconstants) repository.  You can use the API without a key, but registering for a key allows increased rate limits and usage. Check out the [API page](https://www.opendota.com/api-keys) to learn more.     
 *
 * The version of the OpenAPI document: 31.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ako.dbuff.dotapi.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for TeamMatchObjectResponse
 */
public class TeamMatchObjectResponseTest {
    private final TeamMatchObjectResponse model = new TeamMatchObjectResponse();

    /**
     * Model tests for TeamMatchObjectResponse
     */
    @Test
    public void testTeamMatchObjectResponse() {
        // TODO: test TeamMatchObjectResponse
    }

    /**
     * Test the property 'matchId'
     */
    @Test
    public void matchIdTest() {
        // TODO: test matchId
    }

    /**
     * Test the property 'radiant'
     */
    @Test
    public void radiantTest() {
        // TODO: test radiant
    }

    /**
     * Test the property 'radiantWin'
     */
    @Test
    public void radiantWinTest() {
        // TODO: test radiantWin
    }

    /**
     * Test the property 'radiantScore'
     */
    @Test
    public void radiantScoreTest() {
        // TODO: test radiantScore
    }

    /**
     * Test the property 'direScore'
     */
    @Test
    public void direScoreTest() {
        // TODO: test direScore
    }

    /**
     * Test the property 'duration'
     */
    @Test
    public void durationTest() {
        // TODO: test duration
    }

    /**
     * Test the property 'startTime'
     */
    @Test
    public void startTimeTest() {
        // TODO: test startTime
    }

    /**
     * Test the property 'leagueid'
     */
    @Test
    public void leagueidTest() {
        // TODO: test leagueid
    }

    /**
     * Test the property 'leagueName'
     */
    @Test
    public void leagueNameTest() {
        // TODO: test leagueName
    }

    /**
     * Test the property 'cluster'
     */
    @Test
    public void clusterTest() {
        // TODO: test cluster
    }

    /**
     * Test the property 'opposingTeamId'
     */
    @Test
    public void opposingTeamIdTest() {
        // TODO: test opposingTeamId
    }

    /**
     * Test the property 'opposingTeamName'
     */
    @Test
    public void opposingTeamNameTest() {
        // TODO: test opposingTeamName
    }

    /**
     * Test the property 'opposingTeamLogo'
     */
    @Test
    public void opposingTeamLogoTest() {
        // TODO: test opposingTeamLogo
    }

}
